function c(a){throw a;}var h=void 0,i=null;function aa(){return function(a){return a}}function k(a){return function(){return this[a]}}function ba(a){return function(){return a}}var l,n=this;function ca(){}
function p(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var d=Object.prototype.toString.call(a);if(d=="[object Window]")return"object";if(d=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(d=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function da(a){return p(a)=="array"}function ea(a){var b=p(a);return b=="array"||b=="object"&&typeof a.length=="number"}function q(a){return typeof a=="string"}function fa(a){return typeof a=="number"}function ga(a){return p(a)=="function"}function ha(a){a=p(a);return a=="object"||a=="array"||a=="function"}function ia(a){return a[ja]||(a[ja]=++ka)}var ja="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),ka=0;
function la(a,b,d){return a.call.apply(a.bind,arguments)}function ma(a,b,d){var e=b||n;if(arguments.length>2){var f=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,f);return a.apply(e,b)}}else return function(){return a.apply(e,arguments)}}function na(a,b,d){na=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?la:ma;return na.apply(i,arguments)}var oa=Date.now||function(){return+new Date};
function s(a,b){function d(){}d.prototype=b.prototype;a.l=b.prototype;a.prototype=new d;a.prototype.constructor=a};function pa(a){var b=a.length-1;return b>=0&&a.indexOf("%",b)==b}function ra(a){if(!sa.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(ta,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(ua,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(va,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(wa,"&quot;"));return a}var ta=/&/g,ua=/</g,va=/>/g,wa=/\"/g,sa=/[&<>\"]/,xa={"\000":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\x0B",'"':'\\"',"\\":"\\\\"},ya={"'":"\\'"};
function za(a){var o;a=String(a);if(a.quote)return a.quote();else{for(var b=['"'],d=0;d<a.length;d++){var e=a.charAt(d),f=e.charCodeAt(0),g=b,j=d+1,m;if(!(m=xa[e])){if(!(f>31&&f<127))if(e in ya)e=ya[e];else if(e in xa)o=ya[e]=xa[e],e=o;else{f=e;m=e.charCodeAt(0);if(m>31&&m<127)f=e;else{if(m<256){if(f="\\x",m<16||m>256)f+="0"}else f="\\u",m<4096&&(f+="0");f+=m.toString(16).toUpperCase()}e=ya[e]=f}m=e}g[j]=m}b.push('"');return b.join("")}}
function Aa(a,b){for(var d=0,e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),g=Math.max(e.length,f.length),j=0;d==0&&j<g;j++){var m=e[j]||"",o=f[j]||"",r=RegExp("(\\d*)(\\D*)","g"),w=RegExp("(\\d*)(\\D*)","g");do{var C=r.exec(m)||["","",""],U=w.exec(o)||["","",""];if(C[0].length==0&&U[0].length==0)break;d=Ba(C[1].length==0?0:parseInt(C[1],10),U[1].length==0?0:parseInt(U[1],10))||Ba(C[2].length==0,U[2].length==0)||Ba(C[2],U[2])}while(d==
0)}return d}function Ba(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}function Ca(a){for(var b=0,d=0;d<a.length;++d)b=31*b+a.charCodeAt(d),b%=4294967296;return b}var Da=Math.random()*2147483648|0;var Ea,Fa,Ga,Ha,Ia,Ja,Ka=(Ja="ScriptEngine"in n&&n.ScriptEngine()=="JScript")?n.ScriptEngineMajorVersion()+"."+n.ScriptEngineMinorVersion()+"."+n.ScriptEngineBuildVersion():"0";function La(a,b){this.v=Ja?[]:"";a!=i&&this.append.apply(this,arguments)}Ja?(La.prototype.Xa=0,La.prototype.append=function(a,b,d){b==i?this.v[this.Xa++]=a:(this.v.push.apply(this.v,arguments),this.Xa=this.v.length);return this}):La.prototype.append=function(a,b,d){this.v+=a;if(b!=i)for(var e=1;e<arguments.length;e++)this.v+=arguments[e];return this};La.prototype.clear=function(){Ja?this.Xa=this.v.length=0:this.v=""};
La.prototype.toString=function(){if(Ja){var a=this.v.join("");this.clear();a&&this.append(a);return a}else return this.v};var Ma;function Na(){}Na.prototype.qb=!1;Na.prototype.oa=function(){if(!this.qb)this.qb=!0,this.g()};Na.prototype.g=function(){};var t=Array.prototype,Oa=t.indexOf?function(a,b,d){return t.indexOf.call(a,b,d)}:function(a,b,d){d=d==i?0:d<0?Math.max(0,a.length+d):d;if(q(a))return!q(b)||b.length!=1?-1:a.indexOf(b,d);for(;d<a.length;d++)if(d in a&&a[d]===b)return d;return-1},Pa=t.forEach?function(a,b,d){t.forEach.call(a,b,d)}:function(a,b,d){for(var e=a.length,f=q(a)?a.split(""):a,g=0;g<e;g++)g in f&&b.call(d,f[g],g,a)},Qa=t.map?function(a,b,d){return t.map.call(a,b,d)}:function(a,b,d){for(var e=a.length,f=Array(e),g=q(a)?a.split(""):
a,j=0;j<e;j++)j in g&&(f[j]=b.call(d,g[j],j,a));return f};function Ra(a){return t.concat.apply(t,arguments)}function Sa(a){if(da(a))return Ra(a);else{for(var b=[],d=0,e=a.length;d<e;d++)b[d]=a[d];return b}}function Ta(a,b,d){return arguments.length<=2?t.slice.call(a,b):t.slice.call(a,b,d)};function Ua(){return n.navigator?n.navigator.userAgent:i}Ia=Ha=Ga=Fa=Ea=!1;var Va;if(Va=Ua()){var Wa=n.navigator;Ea=Va.indexOf("Opera")==0;Fa=!Ea&&Va.indexOf("MSIE")!=-1;Ha=(Ga=!Ea&&Va.indexOf("WebKit")!=-1)&&Va.indexOf("Mobile")!=-1;Ia=!Ea&&!Ga&&Wa.product=="Gecko"}var Xa=Fa,Ya=Ia,Za=Ga,$a=Ha,ab=n.navigator,bb=(ab&&ab.platform||"").indexOf("Mac")!=-1,cb;
a:{var db="",eb;if(Ea&&n.opera)var fb=n.opera.version,db=typeof fb=="function"?fb():fb;else if(Ya?eb=/rv\:([^\);]+)(\)|;)/:Xa?eb=/MSIE\s+([^\);]+)(\)|;)/:Za&&(eb=/WebKit\/(\S+)/),eb)var gb=eb.exec(Ua()),db=gb?gb[1]:"";if(Xa){var hb,ib=n.document;hb=ib?ib.documentMode:h;if(hb>parseFloat(db)){cb=String(hb);break a}}cb=db}var jb={};function kb(a){return jb[a]||(jb[a]=Aa(cb,a)>=0)};!Xa||kb("9");Xa&&kb("8");function lb(a,b){this.type=a;this.currentTarget=this.target=b}s(lb,Na);lb.prototype.g=function(){delete this.type;delete this.target;delete this.currentTarget};lb.prototype.ta=!1;lb.prototype.Ua=!0;var mb=new Function("a","return a");function nb(a,b){a&&this.Qa(a,b)}s(nb,lb);l=nb.prototype;l.target=i;l.relatedTarget=i;l.offsetX=0;l.offsetY=0;l.clientX=0;l.clientY=0;l.screenX=0;l.screenY=0;l.button=0;l.keyCode=0;l.charCode=0;l.ctrlKey=!1;l.altKey=!1;l.shiftKey=!1;l.metaKey=!1;l.Pb=!1;l.rb=i;
l.Qa=function(a,b){var d=this.type=a.type;lb.call(this,d);this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;if(e){if(Ya)try{mb(e.nodeName)}catch(f){e=i}}else if(d=="mouseover")e=a.fromElement;else if(d=="mouseout")e=a.toElement;this.relatedTarget=e;this.offsetX=a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(d=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Pb=bb?a.metaKey:a.ctrlKey;this.state=a.state;this.rb=a;delete this.Ua;delete this.ta};l.g=function(){nb.l.g.call(this);this.relatedTarget=this.currentTarget=this.target=this.rb=i};function ob(){}var pb=0;l=ob.prototype;l.key=0;l.ua=!1;l.lb=!1;l.Qa=function(a,b,d,e,f,g){ga(a)?this.ub=!0:a&&a.handleEvent&&ga(a.handleEvent)?this.ub=!1:c(Error("Invalid listener argument"));this.ra=a;this.xb=b;this.src=d;this.type=e;this.capture=!!f;this.Pa=g;this.lb=!1;this.key=++pb;this.ua=!1};l.handleEvent=function(a){return this.ub?this.ra.call(this.Pa||this.src,a):this.ra.handleEvent.call(this.ra,a)};function qb(a,b){this.vb=b;this.aa=[];a>this.vb&&c(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var d=0;d<a;d++)this.aa.push(this.I?this.I():{})}s(qb,Na);qb.prototype.I=i;qb.prototype.pb=i;qb.prototype.getObject=function(){return this.aa.length?this.aa.pop():this.I?this.I():{}};function rb(a,b){a.aa.length<a.vb?a.aa.push(b):sb(a,b)}function sb(a,b){if(a.pb)a.pb(b);else if(ha(b))if(ga(b.oa))b.oa();else for(var d in b)delete b[d]}
qb.prototype.g=function(){qb.l.g.call(this);for(var a=this.aa;a.length;)sb(this,a.pop());delete this.aa};var tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db;
(function(){function a(){return{e:0,u:0}}function b(){return[]}function d(){function a(b){return j.call(a.src,a.key,b)}return a}function e(){return new ob}function f(){return new nb}var g=Ja&&!(Aa(Ka,"5.7")>=0),j;yb=function(a){j=a};if(g){tb=function(){return m.getObject()};ub=function(a){rb(m,a)};vb=function(){return o.getObject()};wb=function(a){rb(o,a)};xb=function(){return r.getObject()};zb=function(){rb(r,d())};Ab=function(){return w.getObject()};Bb=function(a){rb(w,a)};Cb=function(){return C.getObject()};
Db=function(a){rb(C,a)};var m=new qb(0,600);m.I=a;var o=new qb(0,600);o.I=b;var r=new qb(0,600);r.I=d;var w=new qb(0,600);w.I=e;var C=new qb(0,600);C.I=f}else tb=a,ub=ca,vb=b,wb=ca,xb=d,zb=ca,Ab=e,Bb=ca,Cb=f,Db=ca})();function Eb(a,b,d){for(var e in a)b.call(d,a[e],e,a)}function Fb(a){var b={},d;for(d in a)b[d]=a[d];return b}var Gb=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];function Hb(a,b){for(var d,e,f=1;f<arguments.length;f++){e=arguments[f];for(d in e)a[d]=e[d];for(var g=0;g<Gb.length;g++)d=Gb[g],Object.prototype.hasOwnProperty.call(e,d)&&(a[d]=e[d])}};var Ib={},u={},Jb={},Kb={};
function Lb(a,b,d,e,f){if(b)if(da(b)){for(var g=0;g<b.length;g++)Lb(a,b[g],d,e,f);return i}else{var e=!!e,j=u;b in j||(j[b]=tb());j=j[b];e in j||(j[e]=tb(),j.e++);var j=j[e],m=ia(a),o;j.u++;if(j[m]){o=j[m];for(g=0;g<o.length;g++)if(j=o[g],j.ra==d&&j.Pa==f){if(j.ua)break;return o[g].key}}else o=j[m]=vb(),j.e++;g=xb();g.src=a;j=Ab();j.Qa(d,g,a,b,e,f);d=j.key;g.key=d;o.push(j);Ib[d]=j;Jb[m]||(Jb[m]=vb());Jb[m].push(j);a.addEventListener?(a==n||!a.Ya)&&a.addEventListener(b,g,e):a.attachEvent(b in Kb?
Kb[b]:Kb[b]="on"+b,g);return d}else c(Error("Invalid event type"))}function Mb(a,b,d,e,f){if(da(b))for(var g=0;g<b.length;g++)Mb(a,b[g],d,e,f);else if(e=!!e,a=Nb(a,b,e))for(g=0;g<a.length;g++)if(a[g].ra==d&&a[g].capture==e&&a[g].Pa==f){Ob(a[g].key);break}}
function Ob(a){if(Ib[a]){var b=Ib[a];if(!b.ua){var d=b.src,e=b.type,f=b.xb,g=b.capture;d.removeEventListener?(d==n||!d.Ya)&&d.removeEventListener(e,f,g):d.detachEvent&&d.detachEvent(e in Kb?Kb[e]:Kb[e]="on"+e,f);d=ia(d);f=u[e][g][d];if(Jb[d]){var j=Jb[d],m=Oa(j,b);m>=0&&t.splice.call(j,m,1);j.length==0&&delete Jb[d]}b.ua=!0;f.wb=!0;Pb(e,g,d,f);delete Ib[a]}}}
function Pb(a,b,d,e){if(!e.Sa&&e.wb){for(var f=0,g=0;f<e.length;f++)if(e[f].ua){var j=e[f].xb;j.src=i;zb(j);Bb(e[f])}else f!=g&&(e[g]=e[f]),g++;e.length=g;e.wb=!1;g==0&&(wb(e),delete u[a][b][d],u[a][b].e--,u[a][b].e==0&&(ub(u[a][b]),delete u[a][b],u[a].e--),u[a].e==0&&(ub(u[a]),delete u[a]))}}
function Qb(a){var b,d=0,e=b==i;b=!!b;if(a==i)Eb(Jb,function(a){for(var f=a.length-1;f>=0;f--){var g=a[f];if(e||b==g.capture)Ob(g.key),d++}});else if(a=ia(a),Jb[a])for(var a=Jb[a],f=a.length-1;f>=0;f--){var g=a[f];if(e||b==g.capture)Ob(g.key),d++}}function Nb(a,b,d){var e=u;return b in e&&(e=e[b],d in e&&(e=e[d],a=ia(a),e[a]))?e[a]:i}
function Rb(a,b,d,e,f){var g=1,b=ia(b);if(a[b]){a.u--;a=a[b];a.Sa?a.Sa++:a.Sa=1;try{for(var j=a.length,m=0;m<j;m++){var o=a[m];o&&!o.ua&&(g&=Sb(o,f)!==!1)}}finally{a.Sa--,Pb(d,e,b,a)}}return Boolean(g)}function Sb(a,b){var d=a.handleEvent(b);a.lb&&Ob(a.key);return d}
yb(function(a,b){if(!Ib[a])return!0;var d=Ib[a],e=d.type,f=u;if(!(e in f))return!0;var f=f[e],g,j;Ma===h&&(Ma=Xa&&!n.addEventListener);if(Ma){var m;if(!(m=b))a:{m="window.event".split(".");for(var o=n;g=m.shift();)if(o[g]!=i)o=o[g];else{m=i;break a}m=o}g=m;m=!0 in f;o=!1 in f;if(m){if(g.keyCode<0||g.returnValue!=h)return!0;a:{var r=!1;if(g.keyCode==0)try{g.keyCode=-1;break a}catch(w){r=!0}if(r||g.returnValue==h)g.returnValue=!0}}r=Cb();r.Qa(g,this);g=!0;try{if(m){for(var C=vb(),U=r.currentTarget;U;U=
U.parentNode)C.push(U);j=f[!0];j.u=j.e;for(var qa=C.length-1;!r.ta&&qa>=0&&j.u;qa--)r.currentTarget=C[qa],g&=Rb(j,C[qa],e,!0,r);if(o){j=f[!1];j.u=j.e;for(qa=0;!r.ta&&qa<C.length&&j.u;qa++)r.currentTarget=C[qa],g&=Rb(j,C[qa],e,!1,r)}}else g=Sb(d,r)}finally{if(C)C.length=0,wb(C);r.oa();Db(r)}return g}e=new nb(b,this);try{g=Sb(d,e)}finally{e.oa()}return g});function Tb(a){this.ba=a}s(Tb,Na);var Ub=new qb(0,100),Vb=[];function Wb(a,b,d,e){da(d)||(Vb[0]=d,d=Vb);for(var f=0;f<d.length;f++){var g=a,j=Lb(b,d[f],e||a,!1,a.ba||a);g.t?g.t[j]=!0:g.W?(g.t=Ub.getObject(),g.t[g.W]=!0,g.W=i,g.t[j]=!0):g.W=j}}
function Xb(a,b,d,e,f,g){if(a.W||a.t)if(da(d))for(var j=0;j<d.length;j++)Xb(a,b,d[j],e,f,g);else{a:{e=e||a;g=g||a.ba||a;f=!!f;if(b=Nb(b,d,f))for(d=0;d<b.length;d++)if(b[d].ra==e&&b[d].capture==f&&b[d].Pa==g){b=b[d];break a}b=i}if(b)if(b=b.key,Ob(b),a.t)a=a.t,b in a&&delete a[b];else if(a.W==b)a.W=i}}function Yb(a){if(a.t){for(var b in a.t)Ob(b),delete a.t[b];rb(Ub,a.t);a.t=i}else a.W&&Ob(a.W)}Tb.prototype.g=function(){Tb.l.g.call(this);Yb(this)};Tb.prototype.handleEvent=function(){c(Error("EventHandler.handleEvent not implemented"))};var Zb,$b=!Xa||kb("9");!Ya&&!Xa||Xa&&kb("9")||Ya&&kb("1.9.1");Xa&&kb("9");function ac(a,b){var d;d=(d=a.className)&&typeof d.split=="function"?d.split(/\s+/):[];var e=Ta(arguments,1),f;f=d;for(var g=0,j=0;j<e.length;j++)Oa(f,e[j])>=0||(f.push(e[j]),g++);f=g==e.length;a.className=d.join(" ");return f};function bc(a,b){this.width=a;this.height=b}l=bc.prototype;l.Ma=function(){return new bc(this.width,this.height)};l.toString=function(){return"("+this.width+" x "+this.height+")"};l.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};l.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};l.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
l.scale=function(a){this.width*=a;this.height*=a;return this};function cc(a){return q(a)?document.getElementById(a):a}function dc(a,b){Eb(b,function(b,e){e=="style"?a.style.cssText=b:e=="class"?a.className=b:e=="for"?a.htmlFor=b:e in ec?a.setAttribute(ec[e],b):a[e]=b})}var ec={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function fc(a,b,d,e){function f(d){d&&b.appendChild(q(d)?a.createTextNode(d):d)}for(;e<d.length;e++){var g=d[e];ea(g)&&!(ha(g)&&g.nodeType>0)?Pa(gc(g)?Sa(g):g,f):f(g)}}function hc(a){for(var b;b=a.firstChild;)a.removeChild(b)}function ic(a){a&&a.parentNode&&a.parentNode.removeChild(a)}function gc(a){if(a&&typeof a.length=="number")if(ha(a))return typeof a.item=="function"||typeof a.item=="string";else if(ga(a))return typeof a.item=="function";return!1}
function jc(a){this.$=a||n.document||document}l=jc.prototype;l.a=function(a){return q(a)?this.$.getElementById(a):a};l.B=function(a,b,d){var e=this.$,f=arguments,g=f[0],j=f[1];if(!$b&&j&&(j.name||j.type)){g=["<",g];j.name&&g.push(' name="',ra(j.name),'"');if(j.type){g.push(' type="',ra(j.type),'"');var m={};Hb(m,j);j=m;delete j.type}g.push(">");g=g.join("")}g=e.createElement(g);if(j)q(j)?g.className=j:da(j)?ac.apply(i,[g].concat(j)):dc(g,j);f.length>2&&fc(e,g,f,2);return g};l.createElement=function(a){return this.$.createElement(a)};
l.createTextNode=function(a){return this.$.createTextNode(a)};l.appendChild=function(a,b){a.appendChild(b)};l.append=function(a,b){fc(a.nodeType==9?a:a.ownerDocument||a.document,a,arguments,1)};function kc(){}s(kc,Na);l=kc.prototype;l.Ya=!0;l.Ta=i;l.gb=function(a){this.Ta=a};l.addEventListener=function(a,b,d,e){Lb(this,a,b,d,e)};l.removeEventListener=function(a,b,d,e){Mb(this,a,b,d,e)};
l.dispatchEvent=function(a){var b=a.type||a,d=u;if(b in d){if(q(a))a=new lb(a,this);else if(a instanceof lb)a.target=a.target||this;else{var e=a,a=new lb(b,this);Hb(a,e)}var e=1,f,d=d[b],b=!0 in d,g;if(b){f=[];for(g=this;g;g=g.Ta)f.push(g);g=d[!0];g.u=g.e;for(var j=f.length-1;!a.ta&&j>=0&&g.u;j--)a.currentTarget=f[j],e&=Rb(g,f[j],a.type,!0,a)&&a.Ua!=!1}if(!1 in d)if(g=d[!1],g.u=g.e,b)for(j=0;!a.ta&&j<f.length&&g.u;j++)a.currentTarget=f[j],e&=Rb(g,f[j],a.type,!1,a)&&a.Ua!=!1;else for(f=this;!a.ta&&
f&&g.u;f=f.Ta)a.currentTarget=f,e&=Rb(g,f,a.type,!1,a)&&a.Ua!=!1;a=Boolean(e)}else a=!0;return a};l.g=function(){kc.l.g.call(this);Qb(this);this.Ta=i};function lc(a){return a*Math.PI/180};function mc(a,b,d,e,f,g){arguments.length==6?this.setTransform(a,b,d,e,f,g):arguments.length!=0?c(Error("Insufficient matrix parameters")):(this.K=this.M=1,this.D=this.L=this.X=this.Y=0)}l=mc.prototype;l.Ma=function(){return new mc(this.K,this.D,this.L,this.M,this.X,this.Y)};l.setTransform=function(a,b,d,e,f,g){(!fa(a)||!fa(b)||!fa(d)||!fa(e)||!fa(f)||!fa(g))&&c(Error("Invalid transform parameters"));this.K=a;this.D=b;this.L=d;this.M=e;this.X=f;this.Y=g;return this};
l.scale=function(a,b){this.K*=a;this.D*=a;this.L*=b;this.M*=b;return this};l.translate=function(a,b){this.X+=a*this.K+b*this.L;this.Y+=a*this.D+b*this.M;return this};l.rotate=function(a,b,d){var e=new mc,f=Math.cos(a),a=Math.sin(a),b=e.setTransform(f,a,-a,f,b-b*f+d*a,d-b*a-d*f),d=this.K,e=this.L;this.K=b.K*d+b.D*e;this.L=b.L*d+b.M*e;this.X+=b.X*d+b.Y*e;d=this.D;e=this.M;this.D=b.K*d+b.D*e;this.M=b.L*d+b.M*e;this.Y+=b.X*d+b.Y*e;return this};
l.toString=function(){return"matrix("+[this.K,this.D,this.L,this.M,this.X,this.Y].join(",")+")"};function v(a,b){this.h=a;this.U=b;this.Ya=!1}s(v,kc);l=v.prototype;l.U=i;l.h=i;l.Ab=i;l.a=k("h");l.addEventListener=function(a,b,d,e){Lb(this.h,a,b,d,e)};l.removeEventListener=function(a,b,d,e){Mb(this.h,a,b,d,e)};l.g=function(){v.l.g.call(this);Qb(this.h)};function x(a,b,d,e){v.call(this,a,b);this.ib=d;this.U.fb(this,d);this.fill=e;this.U.eb(this,e)}s(x,v);x.prototype.fill=i;x.prototype.ib=i;x.prototype.Gb=k("fill");x.prototype.Hb=k("ib");function nc(a,b,d,e){x.call(this,a,b,d,e)}s(nc,x);function oc(a,b){v.call(this,a,b)}s(oc,v);function pc(a,b){v.call(this,a,b)}s(pc,v);function qc(a,b,d,e){x.call(this,a,b,d,e)}s(qc,x);function rc(a,b,d,e){x.call(this,a,b,d,e)}s(rc,x);function sc(a,b){v.call(this,a,b)}s(sc,oc);sc.prototype.clear=function(){hc(this.a())};function tc(a,b,d,e){x.call(this,a,b,d,e)}s(tc,nc);function uc(a,b,d,e){x.call(this,a,b,d,e)}s(uc,rc);function vc(a,b,d,e){x.call(this,a,b,d,e)}s(vc,qc);vc.prototype.hb=function(a){var b=this.a(),a={d:wc(a)},d;for(d in a)b.setAttribute(d,a[d])};function xc(a,b){v.call(this,a,b)}s(xc,pc);function yc(){return this.h=this.U.J.a(this.V)||this.h}function zc(a,b){this.V=a.id;v.call(this,a,b)}s(zc,oc);zc.prototype.a=yc;zc.prototype.clear=function(){hc(this.a())};function Ac(a,b,d,e,f,g,j,m){this.V=a.id;x.call(this,a,b,j,m);this.Wb=d;this.Xb=e;this.fc=f;this.gc=g}s(Ac,nc);Ac.prototype.a=yc;function Bc(a,b,d,e){this.V=a.id;x.call(this,a,b,d,e)}s(Bc,rc);Bc.prototype.a=yc;function Cc(a,b,d,e){this.V=a.id;x.call(this,a,b,d,e)}s(Cc,qc);Cc.prototype.a=yc;
Cc.prototype.hb=function(a){var b=this.a(),a=Dc(a);Ec?b.path=a:b.setAttribute("path",a)};function Fc(a,b){this.V=a.id;v.call(this,a,b)}s(Fc,pc);Fc.prototype.a=yc;function y(){this.j=[];this.e=[];this.F=[]}y.prototype.la=i;y.prototype.m=i;y.prototype.wa=!0;var Gc=[2,2,6,6,0];l=y.prototype;l.clear=function(){this.j.length=0;this.e.length=0;this.F.length=0;delete this.la;delete this.m;delete this.wa;return this};l.moveTo=function(a,b){this.j[this.j.length-1]==0?this.F.length-=2:(this.j.push(0),this.e.push(1));this.F.push(a,b);this.m=this.la=[a,b];return this};
l.lineTo=function(a){var b=this.j[this.j.length-1];b==i&&c(Error("Path cannot start with lineTo"));b!=1&&(this.j.push(1),this.e.push(0));for(b=0;b<arguments.length;b+=2){var d=arguments[b],e=arguments[b+1];this.F.push(d,e)}this.e[this.e.length-1]+=b/2;this.m=[d,e];return this};
l.nb=function(a){var b=this.j[this.j.length-1];b==i&&c(Error("Path cannot start with curve"));b!=2&&(this.j.push(2),this.e.push(0));for(b=0;b<arguments.length;b+=6){var d=arguments[b+4],e=arguments[b+5];this.F.push(arguments[b],arguments[b+1],arguments[b+2],arguments[b+3],d,e)}this.e[this.e.length-1]+=b/6;this.m=[d,e];return this};l.close=function(){var a=this.j[this.j.length-1];a==i&&c(Error("Path cannot start with close"));if(a!=4)this.j.push(4),this.e.push(1),this.m=this.la;return this};
l.arcTo=function(a,b,d,e){var f=this.m[0]-a*Math.cos(lc(d))+a*Math.cos(lc(d+e)),g=this.m[1]-b*Math.sin(lc(d))+b*Math.sin(lc(d+e));this.j.push(3);this.e.push(1);this.F.push(a,b,d,e,f,g);this.wa=!1;this.m=[f,g];return this};
l.Bb=function(a,b,d,e){var f=this.m[0]-a*Math.cos(lc(d)),g=this.m[1]-b*Math.sin(lc(d)),j=lc(e),e=Math.ceil(Math.abs(j)/Math.PI*2);j/=e;for(var d=lc(d),m=0;m<e;m++){var o=Math.cos(d),r=Math.sin(d),w=4/3*Math.sin(j/2)/(1+Math.cos(j/2)),C=f+(o-w*r)*a,U=g+(r+w*o)*b;d+=j;o=Math.cos(d);r=Math.sin(d);this.nb(C,U,f+(o+w*r)*a,g+(r-w*o)*b,f+o*a,g+r*b)}return this};function Hc(a,b){for(var d=a.F,e=0,f=0,g=a.j.length;f<g;f++){var j=a.j[f],m=Gc[j]*a.e[f];b(j,d.slice(e,e+m));e+=m}}
l.Ma=function(){var a=new this.constructor;a.j=this.j.concat();a.e=this.e.concat();a.F=this.F.concat();a.la=this.la&&this.la.concat();a.m=this.m&&this.m.concat();a.wa=this.wa;return a};var Ic={};Ic[0]=y.prototype.moveTo;Ic[1]=y.prototype.lineTo;Ic[4]=y.prototype.close;Ic[2]=y.prototype.nb;Ic[3]=y.prototype.Bb;function Jc(a){if(a.wa)return a.Ma();var b=new y;Hc(a,function(a,e){Ic[a].apply(b,e)});return b};function Kc(a){v.call(this,i,a);this.w=[]}s(Kc,oc);Kc.prototype.clear=function(){if(this.w.length)this.w.length=0,Lc(this.U)};Kc.prototype.appendChild=function(a){this.w.push(a)};Kc.prototype.C=function(){for(var a=0,b=this.w.length;a<b;a++)Mc(this.U,this.w[a])};
function Nc(a,b,d,e,f,g,j,m){x.call(this,a,b,j,m);this.Eb=d;this.Fb=e;this.yb=f;this.zb=g;this.da=new y;this.da.clear();this.da.moveTo(this.Eb+this.yb*Math.cos(lc(0)),this.Fb+this.zb*Math.sin(lc(0)));this.da.arcTo(this.yb,this.zb,0,360);this.da.close();this.Ob=new Oc(i,b,this.da,j,m)}s(Nc,nc);Nc.prototype.C=function(a){this.Ob.C(a)};function Pc(a,b,d,e,f,g,j,m){x.call(this,a,b,j,m);this.xa=d;this.ya=e;this.Ja=f;this.Fa=g}s(Pc,rc);Pc.prototype.pa=!1;
Pc.prototype.C=function(a){this.pa=!0;a.beginPath();a.moveTo(this.xa,this.ya);a.lineTo(this.xa,this.ya+this.Fa);a.lineTo(this.xa+this.Ja,this.ya+this.Fa);a.lineTo(this.xa+this.Ja,this.ya);a.closePath()};function Oc(a,b,d,e,f){x.call(this,a,b,e,f);this.hb(d)}s(Oc,qc);Oc.prototype.pa=!1;Oc.prototype.hb=function(a){this.da=a.wa?a:Jc(a);this.pa&&Lc(this.U)};
Oc.prototype.C=function(a){this.pa=!0;a.beginPath();Hc(this.da,function(b,d){switch(b){case 0:a.moveTo(d[0],d[1]);break;case 1:for(var e=0;e<d.length;e+=2)a.lineTo(d[e],d[e+1]);break;case 2:for(e=0;e<d.length;e+=6)a.bezierCurveTo(d[e],d[e+1],d[e+2],d[e+3],d[e+4],d[e+5]);break;case 3:c(Error("Canvas paths cannot contain arcs"));case 4:a.closePath()}})};function Qc(a,b,d,e,f,g,j){v.call(this,a,b);this.xa=d;this.ya=e;this.Ja=f;this.Fa=g;this.Sb=j}s(Qc,pc);Qc.prototype.pa=!1;
Qc.prototype.C=function(a){this.tb?(this.Ja&&this.Fa&&a.drawImage(this.tb,this.xa,this.ya,this.Ja,this.Fa),this.pa=!0):(a=new Image,a.onload=na(this.Ib,this,a),a.src=this.Sb)};Qc.prototype.Ib=function(a){this.tb=a;Lc(this.U)};function Rc(a,b,d){b instanceof bc?(d=b.height,b=b.width):d==h&&c(Error("missing height argument"));a.style.width=Sc(b);a.style.height=Sc(d)}function Sc(a){typeof a=="number"&&(a=Math.round(a)+"px");return a}
function Tc(a){var b;a:{b=a.nodeType==9?a:a.ownerDocument||a.document;if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,i))){b=b.display||b.getPropertyValue("display");break a}b=""}if((b||(a.currentStyle?a.currentStyle.display:i)||a.style.display)!="none")return new bc(a.offsetWidth,a.offsetHeight);b=a.style;var d=b.display,e=b.visibility,f=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";var g=a.offsetWidth,a=a.offsetHeight;b.display=d;
b.position=f;b.visibility=e;return new bc(g,a)};function Uc(){}(function(a){a.sb=function(){return a.Kb||(a.Kb=new a)}})(Uc);Uc.prototype.Nb=0;Uc.sb();function Vc(a){this.J=a||Zb||(Zb=new jc);this.Rb=Wc}s(Vc,kc);Vc.prototype.Jb=Uc.sb();var Wc=i;l=Vc.prototype;l.V=i;l.n=!1;l.h=i;l.Rb=i;l.Mb=i;l.sa=i;l.w=i;l.Aa=i;l.Vb=!1;l.a=k("h");l.gb=function(a){this.sa&&this.sa!=a&&c(Error("Method not supported"));Vc.l.gb.call(this,a)};l.B=function(){this.h=this.J.createElement("div")};l.T=function(){this.n=!0;Xc(this,function(a){!a.n&&a.a()&&a.T()})};l.Da=function(){Xc(this,function(a){a.n&&a.Da()});this.Oa&&Yb(this.Oa);this.n=!1};
l.g=function(){Vc.l.g.call(this);this.n&&this.Da();this.Oa&&(this.Oa.oa(),delete this.Oa);Xc(this,function(a){a.oa()});!this.Vb&&this.h&&ic(this.h);this.sa=this.Mb=this.h=this.Aa=this.w=i};function Xc(a,b){a.w&&Pa(a.w,b,h)}
l.removeChild=function(a,b){if(a){var d=q(a)?a:a.V||(a.V=":"+(a.Jb.Nb++).toString(36)),a=this.Aa&&d?(d in this.Aa?this.Aa[d]:h)||i:i;if(d&&a){var e=this.Aa;d in e&&delete e[d];d=this.w;e=Oa(d,a);e>=0&&t.splice.call(d,e,1);b&&(a.Da(),a.h&&ic(a.h));d=a;d==i&&c(Error("Unable to set parent component"));d.sa=i;Vc.l.gb.call(d,i)}}a||c(Error("Child is not in parent component"));return a};function Yc(a,b,d,e,f){Vc.call(this,f);this.width=a;this.height=b;this.q=d||i;this.na=e||i}s(Yc,Vc);Yc.prototype.k=i;Yc.prototype.S=0;Yc.prototype.Z=0;Yc.prototype.r=function(){return this.n?Tc(this.a()):fa(this.width)&&fa(this.height)?new bc(this.width,this.height):i};function Zc(a){var b=a.r();return b?b.width/(a.q?new bc(a.q,a.na):a.r()).width:0};function $c(){};function z(a){this.kb=1;this.A=a};function ad(a,b){this.Ra=a||1;this.Ia=b||bd;this.Wa=na(this.Tb,this);this.bb=oa()}s(ad,kc);ad.prototype.enabled=!1;var bd=n.window;l=ad.prototype;l.ea=i;l.Tb=function(){if(this.enabled){var a=oa()-this.bb;if(a>0&&a<this.Ra*0.8)this.ea=this.Ia.setTimeout(this.Wa,this.Ra-a);else if(this.dispatchEvent(cd),this.enabled)this.ea=this.Ia.setTimeout(this.Wa,this.Ra),this.bb=oa()}};l.start=function(){this.enabled=!0;if(!this.ea)this.ea=this.Ia.setTimeout(this.Wa,this.Ra),this.bb=oa()};
l.stop=function(){this.enabled=!1;if(this.ea)this.Ia.clearTimeout(this.ea),this.ea=i};l.g=function(){ad.l.g.call(this);this.stop();delete this.Ia};var cd="tick";function dd(a,b){this.A=a;this.Ga=b||1}s(dd,$c);function ed(a,b,d,e,f){Yc.call(this,a,b,d,e,f);this.ba=new Tb(this)}s(ed,Yc);var Ec=document.documentMode&&document.documentMode>=8;function A(a){return Math.round(parseFloat(a.toString())*100)}function fd(a,b){var d=a.J.createElement("g_vml_:"+b);d.id="goog_"+Da++;return d}function gd(a){if(Ec&&a.n)a.a().innerHTML=a.a().innerHTML}ed.prototype.o=function(a,b){(b||this.k).a().appendChild(a.a());gd(this)};
ed.prototype.eb=function(a,b){var d=a.a();d.fillcolor="";for(var e=0;e<d.childNodes.length;e++){var f=d.childNodes[e];f.tagName=="fill"&&d.removeChild(f)}b instanceof dd?b.A=="transparent"?d.filled=!1:b.Ga!=1?(d.filled=!0,e=fd(this,"fill"),e.opacity=Math.round(b.Ga*100)+"%",e.color=b.A,d.appendChild(e)):(d.filled=!0,d.fillcolor=b.A):d.filled=!1;gd(this)};
ed.prototype.fb=function(a,b){var d=a.a();if(b){d.stroked=!0;var e=b.kb;q(e)&&e.indexOf("px")==-1?e=parseFloat(e):e*=Zc(this);var f=d.getElementsByTagName("stroke")[0];e<1?(f=f||fd(this,"stroke"),f.opacity=e,f.hc="1px",f.color=b.A,d.appendChild(f)):(f&&d.removeChild(f),d.strokecolor=b.A,d.strokeweight=e+"px")}else d.stroked=!1;gd(this)};
function hd(a,b,d,e,f){var g=a.style;g.position="absolute";g.left=Math.round((parseFloat(b.toString())-0.5)*100)+"px";g.top=Math.round((parseFloat(d.toString())-0.5)*100)+"px";g.width=A(e)+"px";g.height=A(f)+"px";if(a.tagName=="shape")a.coordsize=A(e)+" "+A(f)}try{eval("document.namespaces")}catch(id){}l=ed.prototype;
l.B=function(){var a=this.J.$;if(!a.namespaces.g_vml_)Ec?a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML"):a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml"),a.createStyleSheet().cssText="g_vml_\\:*{behavior:url(#default#VML)}";var a=this.width,b=this.height,d=this.J.B("div",{style:"overflow:hidden;position:relative;width:"+(q(a)&&pa(a)?a:parseFloat(a.toString())+"px")+";height:"+(q(b)&&pa(b)?b:parseFloat(b.toString())+"px")});this.h=d;var e=fd(this,"group"),f=e.style;
f.position="absolute";f.left=f.top=0;f.width=this.width;f.height=this.height;e.coordsize=this.q?A(this.q)+" "+A(this.na):A(a)+" "+A(b);e.coordorigin=this.S!==h?A(this.S)+" "+A(this.Z):"0 0";d.appendChild(e);this.k=new zc(e,this);Lb(d,"resize",na(this.ab,this))};
l.ab=function(){var a=Tc(this.a()),b=this.k.a().style;if(a.width)b.width=a.width+"px",b.height=a.height+"px";else{for(a=this.a();a&&a.currentStyle&&a.currentStyle.display!="none";)a=a.parentNode;a&&a.currentStyle&&Wb(this.ba,a,"propertychange",this.ab)}this.dispatchEvent("resize")};l.r=function(){var a=this.a();return new bc(a.style.pixelWidth||a.offsetWidth||1,a.style.pixelHeight||a.offsetHeight||1)};l.clear=function(){this.k.clear()};
l.Na=function(a,b,d,e,f,g,j){var m=fd(this,"oval");hd(m,a-d,b-e,d*2,e*2);a=new Ac(m,this,a,b,d,e,f,g);this.o(a,j);return a};l.$a=function(a,b,d,e,f,g,j){var m=fd(this,"rect");hd(m,a,b,d,e);a=new Bc(m,this,f,g);this.o(a,j);return a};l.drawImage=function(a,b,d,e,f,g){var j=fd(this,"image");hd(j,a,b,d,e);Ec?j.src=f:j.setAttribute("src",f);a=new Fc(j,this);this.o(a,g);return a};
l.f=function(a,b,d,e){var f=fd(this,"shape"),g=this.q?new bc(this.q,this.na):this.r();hd(f,0,0,g.width,g.height);a=Dc(a);Ec?f.path=a:f.setAttribute("path",a);b=new Cc(f,this,b,d);this.o(b,e);return b};
function Dc(a){var b=[];Hc(a,function(a,e){switch(a){case 0:b.push("m");Array.prototype.push.apply(b,Qa(e,A));break;case 1:b.push("l");Array.prototype.push.apply(b,Qa(e,A));break;case 2:b.push("c");Array.prototype.push.apply(b,Qa(e,A));break;case 4:b.push("x");break;case 3:var f=e[2]+e[3];b.push("ae",A(e[4]-e[0]*Math.cos(lc(f))),A(e[5]-e[1]*Math.sin(lc(f))),A(e[0]),A(e[1]),Math.round(e[2]*-65536),Math.round(e[3]*-65536))}});return b.join(" ")}l.T=function(){ed.l.T.call(this);this.ab();gd(this)};
l.g=function(){this.k=i;ed.l.g.call(this)};function jd(a,b,d,e,f){Yc.call(this,a,b,d,e,f)}s(jd,Yc);l=jd.prototype;l.eb=function(){Lc(this)};l.fb=function(){Lc(this)};function kd(a,b){var d=a.getContext();d.save();var e=b.Ab?b.Ab.Ma():new mc,f=e.X,g=e.Y;(f||g)&&d.translate(f,g);(e=e.D)&&d.rotate(Math.asin(e))}l.B=function(){var a=this.J.B("div",{style:"position:relative;overflow:hidden"});this.h=a;this.za=this.J.B("canvas");a.appendChild(this.za);this.Lb=this.k=new Kc(this);this.Qb=0;ld(this)};
l.getContext=function(){this.a()||this.B();if(!this.ma)this.ma=this.za.getContext("2d"),this.ma.save();return this.ma};l.r=function(){var a=this.width,b=this.height,d=q(a)&&a.indexOf("%")!=-1,e=q(b)&&b.indexOf("%")!=-1;if(!this.n&&(d||e))return i;var f,g;if(d)f=this.a().parentNode,g=Tc(f),a=parseFloat(a)*g.width/100;e&&(f=f||this.a().parentNode,g=g||Tc(f),b=parseFloat(b)*g.height/100);return new bc(a,b)};
function ld(a){Rc(a.a(),a.width,a.height);var b=a.r();if(b)Rc(a.za,b.width,b.height),a.za.width=b.width,a.za.height=b.height,a.ma=i}l.reset=function(){var a=this.getContext();a.restore();var b=this.r();b.width&&b.height&&a.clearRect(0,0,b.width,b.height);a.save()};l.clear=function(){this.reset();this.k.clear();for(var a=this.a();a.childNodes.length>1;)a.removeChild(a.lastChild)};
function Lc(a){if(a.ec)a.dc=!0;else if(a.n){a.reset();if(a.q){var b=a.r();a.getContext().scale(b.width/a.q,b.height/a.na)}(a.S||a.Z)&&a.getContext().translate(-a.S,-a.Z);kd(a,a.k);a.k.C(a.ma);a.getContext().restore()}}
function Mc(a,b){var d=a.getContext();kd(a,b);if(!b.Gb||!b.Hb)b.C(d);else{var e=b.fill;if(e)if(e instanceof dd){if(e.Ga!=0)d.globalAlpha=e.Ga,d.fillStyle=e.A,b.C(d),d.fill(),d.globalAlpha=1}else{var f=d.createLinearGradient(e.$b(),e.bc(),e.ac(),e.cc());f.addColorStop(0,e.Yb());f.addColorStop(1,e.Zb());d.fillStyle=f;b.C(d);d.fill()}if(e=b.ib)b.C(d),d.strokeStyle=e.A,e=e.kb,q(e)&&e.indexOf("px")!=-1&&(e=parseFloat(e)/Zc(a)),d.lineWidth=e,d.stroke()}a.getContext().restore()}
l.o=function(a,b){b=b||this.k;b.appendChild(a);this.n&&!this.Qb&&!(b!=this.k&&b!=this.Lb)&&Mc(this,a)};l.Na=function(a,b,d,e,f,g,j){a=new Nc(i,this,a,b,d,e,f,g);this.o(a,j);return a};l.$a=function(a,b,d,e,f,g,j){a=new Pc(i,this,a,b,d,e,f,g);this.o(a,j);return a};l.drawImage=function(a,b,d,e,f,g){a=new Qc(i,this,a,b,d,e,f);this.o(a,g);return a};l.f=function(a,b,d,e){a=new Oc(i,this,a,b,d);this.o(a,e);return a};l.g=function(){this.ma=i;jd.l.g.call(this)};
l.T=function(){var a=this.r();jd.l.T.call(this);a||(ld(this),this.dispatchEvent("resize"));Lc(this)};function md(a,b,d,e,f){Yc.call(this,a,b,d,e,f);this.ob={};this.jb=Za&&!kb(526);this.ba=new Tb(this)}var nd;s(md,Yc);function od(a,b,d){a=a.J.$.createElementNS("http://www.w3.org/2000/svg",b);if(d)for(var e in d)a.setAttribute(e,d[e]);return a}l=md.prototype;l.o=function(a,b){(b||this.k).a().appendChild(a.a())};l.eb=function(a,b){var d=a.a();b instanceof dd?(d.setAttribute("fill",b.A),d.setAttribute("fill-opacity",b.Ga)):d.setAttribute("fill","none")};
l.fb=function(a,b){var d=a.a();if(b){d.setAttribute("stroke",b.A);var e=b.kb;q(e)&&e.indexOf("px")!=-1?d.setAttribute("stroke-width",parseFloat(e)/Zc(this)):d.setAttribute("stroke-width",e)}else d.setAttribute("stroke","none")};
l.B=function(){var a=od(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=od(this,"g");this.Za=od(this,"defs");this.k=new sc(b,this);a.appendChild(this.Za);a.appendChild(b);this.h=a;if(this.q||this.S||this.Z)this.a().setAttribute("preserveAspectRatio","none"),this.jb?this.Va():this.a().setAttribute("viewBox",this.S+" "+this.Z+" "+(this.q?this.q+" "+this.na:""))};
l.Va=function(){if(this.n&&(this.q||this.S||!this.Z)){var a=this.r();if(a.width==0)this.a().style.visibility="hidden";else{this.a().style.visibility="";var b=-this.S,d=-this.Z,e=a.width/this.q,a=a.height/this.na;this.k.a().setAttribute("transform","scale("+e+" "+a+") translate("+b+" "+d+")")}}};
l.r=function(){if(!Ya)return this.n?Tc(this.a()):md.l.r.call(this);var a=this.width,b=this.height,d=q(a)&&a.indexOf("%")!=-1,e=q(b)&&b.indexOf("%")!=-1;if(!this.n&&(d||e))return i;var f,g;if(d)f=this.a().parentNode,g=Tc(f),a=parseFloat(a)*g.width/100;e&&(f=f||this.a().parentNode,g=g||Tc(f),b=parseFloat(b)*g.height/100);return new bc(a,b)};l.clear=function(){this.k.clear();hc(this.Za);this.ob={}};
l.Na=function(a,b,d,e,f,g,j){a=od(this,"ellipse",{cx:a,cy:b,rx:d,ry:e});f=new tc(a,this,f,g);this.o(f,j);return f};l.$a=function(a,b,d,e,f,g,j){a=od(this,"rect",{x:a,y:b,width:d,height:e});f=new uc(a,this,f,g);this.o(f,j);return f};l.drawImage=function(a,b,d,e,f,g){a=od(this,"image",{x:a,y:b,width:d,height:e,"image-rendering":"optimizeQuality",preserveAspectRatio:"none"});a.setAttributeNS("http://www.w3.org/1999/xlink","href",f);f=new xc(a,this);this.o(f,g);return f};
l.f=function(a,b,d,e){a=od(this,"path",{d:wc(a)});b=new vc(a,this,b,d);this.o(b,e);return b};function wc(a){var b=[];Hc(a,function(a,e){switch(a){case 0:b.push("M");Array.prototype.push.apply(b,e);break;case 1:b.push("L");Array.prototype.push.apply(b,e);break;case 2:b.push("C");Array.prototype.push.apply(b,e);break;case 3:var f=e[3];b.push("A",e[0],e[1],0,Math.abs(f)>180?1:0,f>0?1:0,e[4],e[5]);break;case 4:b.push("Z")}});return b.join(" ")}
l.T=function(){var a=this.r();md.l.T.call(this);a||this.dispatchEvent("resize");if(this.jb){var a=this.width,b=this.height;typeof a=="string"&&a.indexOf("%")!=-1&&typeof b=="string"&&b.indexOf("%")!=-1&&Wb(this.ba,pd(),cd,this.Va);this.Va()}};l.Da=function(){md.l.Da.call(this);this.jb&&Xb(this.ba,pd(),cd,this.Va)};l.g=function(){delete this.ob;delete this.Za;delete this.k;md.l.g.call(this)};function pd(){nd||(nd=new ad(400),nd.start());return nd};function qd(a,b,d,e,f){a=Xa&&!kb("9")?new ed(a,b,d,e,f):Za&&(!kb("420")||$a)?new jd(a,b,d,e,f):new md(a,b,d,e,f);a.B();return a};function B(a){return a!=i&&a!==!1}function rd(a,b){var d=a[p.call(i,b)];return B(d)?d:(d=a._,B(d)?d:!1)}function sd(a){return Array.prototype.slice.call(a)}function td(a){return Array.prototype.slice.call(arguments)}
var D=function ud(b){return B(B(b)?b.ga:b)?b.ga(b):function(){var d=ud[p.call(i,b)];return B(d)?d:ud._}().call(i,b)},wd=function vd(b,d){return B(B(b)?b.N:b)?b.N(b,d):function(){var d=vd[p.call(i,b)];return B(d)?d:vd._}().call(i,b,d)},E=function(){function a(a,b,g){return B(B(a)?a.La:a)?a.La(a,b,g):function(){var b=d[p.call(i,a)];return B(b)?b:d._}().call(i,a,b,g)}function b(a,b){return B(B(a)?a.La:a)?a.La(a,b):function(){var b=d[p.call(i,a)];return B(b)?b:d._}().call(i,a,b)}var d=i;return d=function(d,
f,g){switch(arguments.length){case 2:return b.call(this,d,f);case 3:return a.call(this,d,f,g)}c("Invalid arity: "+arguments.length)}}(),xd={},zd=function yd(b){return B(B(b)?b.ia:b)?b.ia(b):function(){var d=yd[p.call(i,b)];return B(d)?d:yd._}().call(i,b)},Bd=function Ad(b){return B(B(b)?b.ja:b)?b.ja(b):function(){var d=Ad[p.call(i,b)];return B(d)?d:Ad._}().call(i,b)},F=function(){function a(a,b,g){return B(B(a)?a.ha:a)?a.ha(a,b,g):function(){var b=d[p.call(i,a)];return B(b)?b:d._}().call(i,a,b,g)}
function b(a,b){return B(B(a)?a.ha:a)?a.ha(a,b):function(){var b=d[p.call(i,a)];return B(b)?b:d._}().call(i,a,b)}var d=i;return d=function(d,f,g){switch(arguments.length){case 2:return b.call(this,d,f);case 3:return a.call(this,d,f,g)}c("Invalid arity: "+arguments.length)}}(),Dd=function Cd(b,d,e){return B(B(b)?b.Ka:b)?b.Ka(b,d,e):function(){var d=Cd[p.call(i,b)];return B(d)?d:Cd._}().call(i,b,d,e)},Ed={},Fd={},Hd=function Gd(b){return B(B(b)?b.Cb:b)?b.state:function(){var d=Gd[p.call(i,b)];return B(d)?
d:Gd._}().call(i,b)},Id={},Kd=function Jd(b){return B(B(b)?b.Q:b)?b.c:function(){var d=Jd[p.call(i,b)];return B(d)?d:Jd._}().call(i,b)},Md=function Ld(b,d){return B(B(b)?b.R:b)?b.R(b,d):function(){var d=Ld[p.call(i,b)];return B(d)?d:Ld._}().call(i,b,d)},Nd=function(){function a(a,b,g){return B(B(a)?a.Ba:a)?a.Ba(a,b,g):function(){var b=d[p.call(i,a)];return B(b)?b:d._}().call(i,a,b,g)}function b(a,b){return B(B(a)?a.Ba:a)?a.Ba(a,b):function(){var b=d[p.call(i,a)];return B(b)?b:d._}().call(i,a,b)}var d=
i;return d=function(d,f,g){switch(arguments.length){case 2:return b.call(this,d,f);case 3:return a.call(this,d,f,g)}c("Invalid arity: "+arguments.length)}}(),Pd=function Od(b,d){return B(B(b)?b.s:b)?b.s(b,d):function(){var d=Od[p.call(i,b)];return B(d)?d:Od._}().call(i,b,d)},Rd=function Qd(b){return B(B(b)?b.O:b)?b.O(b):function(){var d=Qd[p.call(i,b)];return B(d)?d:Qd._}().call(i,b)},Td=function Sd(b){return B(B(b)?b.H:b)?b.H(b):function(){var d=Sd[p.call(i,b)];return B(d)?d:Sd._}().call(i,b)},Ud=
{},Vd={},Xd=function Wd(b,d){return B(B(b)?b.z:b)?b.z(b,d):function(){var d=Wd[p.call(i,b)];return B(d)?d:Wd._}().call(i,b,d)};function Yd(a,b){return a===b}function G(a,b){return Pd.call(i,a,b)}function Zd(a){return Yd.call(i,a,i)}Pd["null"]=function(a,b){return Zd.call(i,b)};wd["null"]=function(a,b){return H.call(i,b)};xd["null"]=!0;zd["null"]=ba(i);Bd["null"]=function(){return H.call(i)};Md["null"]=ba(i);Ed["null"]=!0;
E["null"]=function(){return function(a,b,d){switch(arguments.length){case 2:return i;case 3:return d}c("Invalid arity: "+arguments.length)}}();Id["null"]=!0;Kd["null"]=ba(i);Nd["null"]=function(){return function(a,b,d){switch(arguments.length){case 2:return b.call(i);case 3:return d}c("Invalid arity: "+arguments.length)}}();Rd["null"]=ba(0);D["null"]=ba(0);Dd["null"]=function(a,b,d){return $d.call(i,b,d)};
F["null"]=function(){return function(a,b,d){switch(arguments.length){case 2:return i;case 3:return d}c("Invalid arity: "+arguments.length)}}();Date.prototype.s=function(a,b){return Yd.call(i,a.toString,b.toString)};Rd.number=aa();Pd.number=function(a,b){return Yd.call(i,a,b)};function I(a){return a+1}function ae(a,b){return a<b}
var be=function(){return function(a,b,d,e){switch(arguments.length){case 2:var f;a:if(B(G.call(i,0,D.call(i,a))))f=b.call(i);else for(var g=E.call(i,a,0),j=1;;)if(B(ae.call(i,j,D.call(i,a))))g=b.call(i,g,E.call(i,a,j)),j=I.call(i,j);else{f=g;break a}return f;case 3:a:{f=d;for(j=0;;)if(B(ae.call(i,j,D.call(i,a))))f=b.call(i,f,E.call(i,a,j)),j=I.call(i,j);else{g=f;break a}}return g;case 4:a:{f=d;for(g=e;;)if(B(ae.call(i,g,D.call(i,a))))f=b.call(i,f,E.call(i,a,g)),g=I.call(i,g);else{j=f;break a}}return j}c("Invalid arity: "+
arguments.length)}}();function ce(a,b){this.fa=a;this.qa=b}l=ce.prototype;l.Ba=function(){return function(a,b,d){switch(arguments.length){case 2:return be.call(i,this.fa,b,this.fa[this.qa],I.call(i,this.qa));case 3:return be.call(i,this.fa,b,d,this.qa)}c("Invalid arity: "+arguments.length)}}();l.s=function(a,b){return de.call(i,a,b)};l.ka=!0;l.Ca=!0;l.ia=function(){return this.fa[this.qa]};l.ja=function(){return B(ae.call(i,I.call(i,this.qa),D.call(i,this.fa)))?new ce(this.fa,I.call(i,this.qa)):H.call(i)};
l.H=aa();function ee(a,b){return B(G.call(i,0,D.call(i,a)))?i:new ce(a,b)}function J(a,b){return ee.call(i,a,b)}Nd.array=function(){return function(a,b,d){switch(arguments.length){case 2:return be.call(i,a,b);case 3:return be.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();F.array=function(){return function(a,b,d){switch(arguments.length){case 2:return a[b];case 3:return E.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();
E.array=function(){return function(a,b,d){switch(arguments.length){case 2:return B(ae.call(i,b,a.length))?a[b]:i;case 3:return B(ae.call(i,b,a.length))?a[b]:d}c("Invalid arity: "+arguments.length)}}();D.array=function(a){return a.length};Td.array=function(a){return J.call(i,a,0)};function K(a){return B(a)?Td.call(i,a):i}function L(a){a=K.call(i,a);return B(a)?zd.call(i,a):i}function M(a){return Bd.call(i,K.call(i,a))}function N(a){return B(a)?K.call(i,M.call(i,a)):i}
function fe(a){return L.call(i,N.call(i,a))}function ge(a){return N.call(i,N.call(i,a))}D._=function(a){for(var a=K.call(i,a),b=0;;)if(B(a))a=N.call(i,a),b=I.call(i,b);else return b};Pd._=function(a,b){return Yd.call(i,a,b)};function he(a){return B(a)?!1:!0}
var ie=function(){function a(a,e,f){for(var g=J(Array.prototype.slice.call(arguments,2),0);;)if(B(g))var j=b.call(i,a,e),m=L.call(i,g),g=N.call(i,g),a=j,e=m;else return b.call(i,a,e)}var b=i,b=function(b,e,f){switch(arguments.length){case 2:return wd.call(i,b,e);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.i=2;b.b=function(b){var e=L(b),f=L(N(b)),b=M(N(b));return a.call(i,e,f,b)};return b}();function je(a){return D.call(i,a)}
var ke=function(){return function(a,b,d){switch(arguments.length){case 2:return E.call(i,a,b);case 3:return E.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}(),le=function(){return function(a,b,d){switch(arguments.length){case 2:return F.call(i,a,b);case 3:return F.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}(),me=function(){function a(a,e,f,g){for(var j=J(Array.prototype.slice.call(arguments,3),0);;){var m=b.call(i,a,e,f);if(B(j))var o=L.call(i,j),r=fe.call(i,j),j=ge.call(i,j),a=m,
e=o,f=r;else return m}}var b=i,b=function(b,e,f,g){switch(arguments.length){case 3:return Dd.call(i,b,e,f);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.i=3;b.b=function(b){var e=L(b),f=L(N(b)),g=L(N(N(b))),b=M(N(N(b)));return a.call(i,e,f,g,b)};return b}();function ne(a,b){return Md.call(i,a,b)}function oe(a){return Kd.call(i,a)}function pe(a){return Rd.call(i,a)}function qe(a){return B(B(a)?a.ka:a)?!0:rd.call(i,Ud,a)}
function re(a){return B(Zd.call(i,a))?!1:B(B(a)?a.mb:a)?!0:rd.call(i,Ed,a)}function se(a){return B(B(a)?a.Db:a)?!0:rd.call(i,Fd,a)}function te(){return{}}function ue(a){var b=td.call(i);Eb.call(i,a,function(a,e){return b.push(e)});return b}var ve=te.call(i);function we(a){return h===a}function xe(a){return B(Zd.call(i,a))?!1:B(B(a)?a.Ca:a)?!0:rd.call(i,xd,a)}function ye(a){return B(a)?!0:!1}
function ze(a){var b=q.call(i,a);return B(b)?he.call(i,function(){var b=G.call(i,a.charAt(0),"\ufdd0");return B(b)?b:G.call(i,a.charAt(0),"\ufdd1")}()):b}function Ae(a){var b=q.call(i,a);return B(b)?G.call(i,a.charAt(0),"\ufdd0"):b}function Be(a){var b=q.call(i,a);return B(b)?G.call(i,a.charAt(0),"\ufdd1"):b}function Ce(a,b){return B(Yd.call(i,F.call(i,a,b,ve),ve))?!1:!0}
var De=function(){return function(a,b,d){switch(arguments.length){case 2:return Nd.call(i,b,a);case 3:return Nd.call(i,d,a,b)}c("Invalid arity: "+arguments.length)}}(),Ee=function(){return function(a,b,d){switch(arguments.length){case 2:var e=K.call(i,b);return B(e)?De.call(i,a,L.call(i,e),N.call(i,e)):a.call(i);case 3:a:for(var f=b,g=K.call(i,d);;)if(B(g))f=a.call(i,f,L.call(i,g)),g=N.call(i,g);else{e=f;break a}return e}c("Invalid arity: "+arguments.length)}}();
Nd._=function(){return function(a,b,d){switch(arguments.length){case 2:return Ee.call(i,b,a);case 3:return Ee.call(i,b,d,a)}c("Invalid arity: "+arguments.length)}}();
var O=function(){function a(a,e,f){var g=J(Array.prototype.slice.call(arguments,2),0);return De.call(i,b,b.call(i,a,e),g)}var b=i,b=function(b,e,f){switch(arguments.length){case 0:return 0;case 1:return b;case 2:return b+e;default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.i=2;b.b=function(b){var e=L(b),f=L(N(b)),b=M(N(b));return a.call(i,e,f,b)};return b}(),Fe=function(){function a(a,e,f){var g=J(Array.prototype.slice.call(arguments,2),0);return De.call(i,b,b.call(i,
a,e),g)}var b=i,b=function(b,e,f){switch(arguments.length){case 1:return-b;case 2:return b-e;default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.i=2;b.b=function(b){var e=L(b),f=L(N(b)),b=M(N(b));return a.call(i,e,f,b)};return b}(),Ge=function(){function a(a,e,f){var g=J(Array.prototype.slice.call(arguments,2),0);return De.call(i,b,b.call(i,a,e),g)}var b=i,b=function(b,e,f){switch(arguments.length){case 0:return 1;case 1:return b;case 2:return b*e;default:return a.apply(this,
arguments)}c("Invalid arity: "+arguments.length)};b.i=2;b.b=function(b){var e=L(b),f=L(N(b)),b=M(N(b));return a.call(i,e,f,b)};return b}(),He=function(){function a(a,e,f){for(var g=J(Array.prototype.slice.call(arguments,2),0);;)if(B(b.call(i,a,e)))if(B(N.call(i,g)))var j=e,m=L.call(i,g),g=N.call(i,g),a=j,e=m;else return b.call(i,e,L.call(i,g));else return!1}var b=i,b=function(b,e,f){switch(arguments.length){case 1:return!0;case 2:return b<e;default:return a.apply(this,arguments)}c("Invalid arity: "+
arguments.length)};b.i=2;b.b=function(b){var e=L(b),f=L(N(b)),b=M(N(b));return a.call(i,e,f,b)};return b}(),Ie=function(){function a(a,e,f){for(var g=J(Array.prototype.slice.call(arguments,2),0);;)if(B(b.call(i,a,e)))if(B(N.call(i,g)))var j=e,m=L.call(i,g),g=N.call(i,g),a=j,e=m;else return b.call(i,e,L.call(i,g));else return!1}var b=i,b=function(b,e,f){switch(arguments.length){case 1:return!0;case 2:return b<=e;default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.i=2;b.b=
function(b){var e=L(b),f=L(N(b)),b=M(N(b));return a.call(i,e,f,b)};return b}(),Je=function(){function a(a,e,f){for(var g=J(Array.prototype.slice.call(arguments,2),0);;)if(B(b.call(i,a,e)))if(B(N.call(i,g)))var j=e,m=L.call(i,g),g=N.call(i,g),a=j,e=m;else return b.call(i,e,L.call(i,g));else return!1}var b=i,b=function(b,e,f){switch(arguments.length){case 1:return!0;case 2:return b>e;default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.i=2;b.b=function(b){var e=L(b),f=L(N(b)),
b=M(N(b));return a.call(i,e,f,b)};return b}();function Ke(a){return Fe.call(i,a,1)}function Le(a,b){return a^b}function Me(a,b){return a<<b}function Ne(a,b){return a>>b}function Oe(a){return He.call(i,0,a)}function Pe(a,b){for(var d=b,e=K.call(i,a);;)if(B(function(){var a=e;return B(a)?Oe.call(i,d):a}()))var f=Ke.call(i,d),g=N.call(i,e),d=f,e=g;else return e}
E._=function(){return function(a,b,d){switch(arguments.length){case 2:var e;var f=Pe.call(i,a,b);B(f)?e=L.call(i,f):c("Index out of bounds");return e;case 3:return e=Pe.call(i,a,b),B(e)?L.call(i,e):d}c("Invalid arity: "+arguments.length)}}();
var Qe=function(){function a(a,e){var f=J(Array.prototype.slice.call(arguments,1),0);return function(a,d){for(;;)if(B(d))var e=a.append(b.call(i,L.call(i,d))),f=N.call(i,d),a=e,d=f;else return b.call(i,a)}.call(i,new La(b.call(i,a)),f)}var b=i,b=function(b,e){switch(arguments.length){case 0:return"";case 1:return B(Zd.call(i,b))?"":b.toString();default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.i=1;b.b=function(b){var e=L(b),b=M(b);return a.call(i,e,b)};return b}(),Re=
function(){return function(a,b,d){switch(arguments.length){case 2:return a.substring(b);case 3:return a.substring(b,d)}c("Invalid arity: "+arguments.length)}}();function de(a,b){return ye.call(i,B(qe.call(i,b))?function(){for(var d=K.call(i,a),e=K.call(i,b);;)if(B(Zd.call(i,d)))return Zd.call(i,e);else if(B(Zd.call(i,e)))return!1;else if(B(G.call(i,L.call(i,d),L.call(i,e))))d=N.call(i,d),e=N.call(i,e);else return B("\ufdd0'else")?!1:i}():i)}
function Se(a,b){return Le.call(i,a,O.call(i,b,2654435769,Me.call(i,a,6),Ne.call(i,a,2)))}function Te(a){return De.call(i,function(a,d){return Se.call(i,a,pe.call(i,d))},pe.call(i,L.call(i,a)),N.call(i,a))}function Ue(a,b,d,e){this.c=a;this.Ea=b;this.va=d;this.count=e}l=Ue.prototype;l.s=function(a,b){return de.call(i,a,b)};l.N=function(a,b){return new Ue(this.c,b,a,I.call(i,this.count))};l.Ca=!0;l.ia=k("Ea");l.ja=k("va");l.H=aa();l.R=function(a,b){return new Ue(b,this.Ea,this.va,this.count)};
l.P=!0;l.Q=k("c");l.O=function(a){return Te.call(i,a)};l.ga=k("count");l.ka=!0;function Ve(a){this.c=a}l=Ve.prototype;l.s=function(a,b){return de.call(i,a,b)};l.N=function(a,b){return new Ue(this.c,b,i,1)};l.Ca=!0;l.ia=ba(i);l.ja=ba(i);l.H=ba(i);l.R=function(a,b){return new Ve(b)};l.P=!0;l.Q=k("c");l.O=function(a){return Te.call(i,a)};l.ga=ba(0);l.ka=!0;var We=new Ve(i);function Xe(a){return De.call(i,ie,We,a)}
function H(a){var b=J(Array.prototype.slice.call(arguments,0),0);return De.call(i,ie,We,Xe.call(i,b))}function Ye(a,b,d){this.c=a;this.Ea=b;this.va=d}l=Ye.prototype;l.H=aa();l.O=function(a){return Te.call(i,a)};l.s=function(a,b){return de.call(i,a,b)};l.ka=!0;l.N=function(a,b){return new Ye(i,b,a)};l.Ca=!0;l.ia=k("Ea");l.ja=function(){return B(Zd.call(i,this.va))?We:this.va};l.P=!0;l.Q=k("c");l.R=function(a,b){return new Ye(b,this.Ea,this.va)};function P(a,b){return new Ye(i,a,b)}
Nd.string=function(){return function(a,b,d){switch(arguments.length){case 2:return be.call(i,a,b);case 3:return be.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();F.string=function(){return function(a,b,d){switch(arguments.length){case 2:return E.call(i,a,b);case 3:return E.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();
E.string=function(){return function(a,b,d){switch(arguments.length){case 2:return B(He.call(i,b,D.call(i,a)))?a.charAt(b):i;case 3:return B(He.call(i,b,D.call(i,a)))?a.charAt(b):d}c("Invalid arity: "+arguments.length)}}();D.string=function(a){return a.length};Td.string=function(a){return ee.call(i,a,0)};Rd.string=function(a){return Ca.call(i,a)};
String.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return le.call(i,b,this.toString());case 3:return le.call(i,b,this.toString(),d)}c("Invalid arity: "+arguments.length)}}();function Ze(a){var b=a.x;return B(a.cb)?b:(a.x=b.call(i),a.cb=!0,a.x)}function Q(a,b,d){this.c=a;this.cb=b;this.x=d}l=Q.prototype;l.H=function(a){return K.call(i,Ze.call(i,a))};l.O=function(a){return Te.call(i,a)};l.s=function(a,b){return de.call(i,a,b)};l.ka=!0;
l.N=function(a,b){return P.call(i,b,a)};l.Ca=!0;l.ia=function(a){return L.call(i,Ze.call(i,a))};l.ja=function(a){return M.call(i,Ze.call(i,a))};l.P=!0;l.Q=k("c");l.R=function(a,b){return new Q(b,this.cb,this.x)};function $e(a){for(var b=td.call(i);;)if(B(K.call(i,a)))b.push(L.call(i,a)),a=N.call(i,a);else return b}function af(a,b){for(var d=a,e=b,f=0;;)if(B(function(){var a=Oe.call(i,e);return B(a)?K.call(i,d):a}()))var g=N.call(i,d),j=Ke.call(i,e),f=I.call(i,f),d=g,e=j;else return f}
var cf=function bf(b){return B(Zd.call(i,b))?i:B(Zd.call(i,N.call(i,b)))?K.call(i,L.call(i,b)):B("\ufdd0'else")?P.call(i,L.call(i,b),bf.call(i,N.call(i,b))):i},df=function(){function a(a,b,d){var e=J(Array.prototype.slice.call(arguments,2),0);return function w(a,b){return new Q(i,!1,function(){var d=K.call(i,a);return B(d)?P.call(i,L.call(i,d),w.call(i,M.call(i,d),b)):B(b)?w.call(i,L.call(i,b),N.call(i,b)):i})}.call(i,f.call(i,a,b),e)}function b(a,b){return new Q(i,!1,function(){var d=K.call(i,a);
return B(d)?P.call(i,L.call(i,d),f.call(i,M.call(i,d),b)):b})}function d(a){return new Q(i,!1,function(){return a})}function e(){return new Q(i,!1,ba(i))}var f=i,f=function(f,j,m){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,f);case 2:return b.call(this,f,j);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};f.i=2;f.b=function(b){var d=L(b),e=L(N(b)),b=M(N(b));return a.call(i,d,e,b)};return f}(),ef=function(){function a(a,b,f,g,j){var m=
J(Array.prototype.slice.call(arguments,4),0);return P.call(i,a,P.call(i,b,P.call(i,f,P.call(i,g,cf.call(i,m)))))}var b=i,b=function(b,e,f,g,j){switch(arguments.length){case 1:return K.call(i,b);case 2:return P.call(i,b,e);case 3:return P.call(i,b,P.call(i,e,f));case 4:return P.call(i,b,P.call(i,e,P.call(i,f,g)));default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.i=4;b.b=function(b){var e=L(b),f=L(N(b)),g=L(N(N(b))),j=L(N(N(N(b)))),b=M(N(N(N(b))));return a.call(i,e,f,g,
j,b)};return b}(),ff=function(){function a(a,b,f,g,j,m){var o=J(Array.prototype.slice.call(arguments,5),0),o=P.call(i,b,P.call(i,f,P.call(i,g,P.call(i,j,cf.call(i,o))))),r=a.i;return B(a.b)?B(Ie.call(i,af.call(i,o,r),r))?a.apply(a,$e.call(i,o)):a.b(o):a.apply(a,$e.call(i,o))}var b=i,b=function(b,e,f,g,j,m){switch(arguments.length){case 2:var o=b,r=e,w=o.i;return B(o.b)?B(Ie.call(i,af.call(i,r,w),w))?o.apply(o,$e.call(i,r)):o.b(r):o.apply(o,$e.call(i,r));case 3:return o=b,r=ef.call(i,e,f),w=o.i,B(o.b)?
B(Ie.call(i,af.call(i,r,w),w))?o.apply(o,$e.call(i,r)):o.b(r):o.apply(o,$e.call(i,r));case 4:return o=b,r=ef.call(i,e,f,g),w=o.i,B(o.b)?B(Ie.call(i,af.call(i,r,w),w))?o.apply(o,$e.call(i,r)):o.b(r):o.apply(o,$e.call(i,r));case 5:return o=b,r=ef.call(i,e,f,g,j),w=o.i,B(o.b)?B(Ie.call(i,af.call(i,r,w),w))?o.apply(o,$e.call(i,r)):o.b(r):o.apply(o,$e.call(i,r));default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.i=5;b.b=function(b){var e=L(b),f=L(N(b)),g=L(N(N(b))),j=L(N(N(N(b)))),
m=L(N(N(N(N(b))))),b=M(N(N(N(N(b)))));return a.call(i,e,f,g,j,m,b)};return b}();function gf(a,b){for(;;)if(B(Zd.call(i,K.call(i,b))))return!0;else if(B(a.call(i,L.call(i,b))))var d=a,e=N.call(i,b),a=d,b=e;else return B("\ufdd0'else")?!1:i}function hf(a){return a}
var jf=function(){function a(a,b,d,e,r){var w=J(Array.prototype.slice.call(arguments,4),0);return f.call(i,function(b){return ff.call(i,a,b)},function U(a){return new Q(i,!1,function(){var b=f.call(i,K,a);return B(gf.call(i,hf,b))?P.call(i,f.call(i,L,b),U.call(i,f.call(i,M,b))):i})}.call(i,ie.call(i,w,e,d,b)))}function b(a,b,d,e){return new Q(i,!1,function(){var r=K.call(i,b),w=K.call(i,d),C=K.call(i,e);return B(B(r)?B(w)?C:w:r)?P.call(i,a.call(i,L.call(i,r),L.call(i,w),L.call(i,C)),f.call(i,a,M.call(i,
r),M.call(i,w),M.call(i,C))):i})}function d(a,b,d){return new Q(i,!1,function(){var e=K.call(i,b),r=K.call(i,d);return B(B(e)?r:e)?P.call(i,a.call(i,L.call(i,e),L.call(i,r)),f.call(i,a,M.call(i,e),M.call(i,r))):i})}function e(a,b){return new Q(i,!1,function(){var d=K.call(i,b);return B(d)?P.call(i,a.call(i,L.call(i,d)),f.call(i,a,M.call(i,d))):i})}var f=i,f=function(f,j,m,o,r){switch(arguments.length){case 2:return e.call(this,f,j);case 3:return d.call(this,f,j,m);case 4:return b.call(this,f,j,m,
o);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};f.i=4;f.b=function(b){var d=L(b),e=L(N(b)),f=L(N(N(b))),r=L(N(N(N(b)))),b=M(N(N(N(b))));return a.call(i,d,e,f,r,b)};return f}(),lf=function kf(b,d){return new Q(i,!1,function(){if(B(Oe.call(i,b))){var e=K.call(i,d);return B(e)?P.call(i,L.call(i,e),kf.call(i,Ke.call(i,b),M.call(i,e))):i}else return i})};
function mf(a,b){function d(a,b){for(;;){var d=K.call(i,b);if(B(function(){var b=Oe.call(i,a);return B(b)?d:b}()))var j=Ke.call(i,a),m=M.call(i,d),a=j,b=m;else return d}}return new Q(i,!1,function(){return d.call(i,a,b)})}
var nf=function(){function a(a){return new Q(i,!1,function(){return P.call(i,a,b.call(i,a))})}var b=i;return b=function(d,e){switch(arguments.length){case 1:return a.call(this,d);case 2:return lf.call(i,d,b.call(i,e))}c("Invalid arity: "+arguments.length)}}(),of=function(){function a(a,b,g){var j=J(Array.prototype.slice.call(arguments,2),0);return new Q(i,!1,function(){var g=jf.call(i,K,ie.call(i,j,b,a));return B(gf.call(i,hf,g))?df.call(i,jf.call(i,L,g),ff.call(i,d,jf.call(i,M,g))):i})}function b(a,
b){return new Q(i,!1,function(){var g=K.call(i,a),j=K.call(i,b);return B(B(g)?j:g)?P.call(i,L.call(i,g),P.call(i,L.call(i,j),d.call(i,M.call(i,g),M.call(i,j)))):i})}var d=i,d=function(d,f,g){switch(arguments.length){case 2:return b.call(this,d,f);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};d.i=2;d.b=function(b){var d=L(b),g=L(N(b)),b=M(N(b));return a.call(i,d,g,b)};return d}();function pf(a,b){return mf.call(i,1,of.call(i,nf.call(i,a),b))}
function qf(a){return function d(a,f){return new Q(i,!1,function(){var g=K.call(i,a);return B(g)?P.call(i,L.call(i,g),d.call(i,M.call(i,g),f)):B(K.call(i,f))?d.call(i,L.call(i,f),M.call(i,f)):i})}.call(i,i,a)}
var rf=function(){function a(a,b,f){var g=J(Array.prototype.slice.call(arguments,2),0);return qf.call(i,ff.call(i,jf,a,b,g))}var b=i,b=function(b,e,f){switch(arguments.length){case 2:return qf.call(i,jf.call(i,b,e));default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.i=2;b.b=function(b){var e=L(b),f=L(N(b)),b=M(N(b));return a.call(i,e,f,b)};return b}();function sf(a,b){return De.call(i,wd,a,b)}
var tf=function(){function a(a,b,g,j){return new Q(i,!1,function(){var m=K.call(i,j);if(B(m)){var o=lf.call(i,a,m);return B(G.call(i,a,je.call(i,o)))?P.call(i,o,d.call(i,a,b,g,mf.call(i,b,m))):H.call(i,lf.call(i,a,df.call(i,o,g)))}else return i})}function b(a,b,g){return new Q(i,!1,function(){var j=K.call(i,g);if(B(j)){var m=lf.call(i,a,j);return B(G.call(i,a,je.call(i,m)))?P.call(i,m,d.call(i,a,b,mf.call(i,b,j))):i}else return i})}var d=i;return d=function(e,f,g,j){switch(arguments.length){case 2:return d.call(i,
e,e,f);case 3:return b.call(this,e,f,g);case 4:return a.call(this,e,f,g,j)}c("Invalid arity: "+arguments.length)}}(),uf=function(){return function(a,b,d){switch(arguments.length){case 2:return De.call(i,le,a,b);case 3:var e;a:for(var f=ve,g=a,j=K.call(i,b);;)if(B(j))if(g=le.call(i,g,L.call(i,j),f),B(Yd.call(i,f,g))){e=d;break a}else j=N.call(i,j);else{e=g;break a}return e}c("Invalid arity: "+arguments.length)}}();function vf(a,b){this.c=a;this.p=b}l=vf.prototype;
l.s=function(a,b){return de.call(i,a,b)};l.N=function(a,b){var d=sd.call(i,this.p);d.push(b);return new vf(this.c,d)};l.H=function(){var a=this;return B(Je.call(i,a.p.length,0))?function d(e){return new Q(i,!1,function(){return B(He.call(i,e,a.p.length))?P.call(i,a.p[e],d.call(i,I.call(i,e))):i})}.call(i,0):i};l.Db=!0;l.R=function(a,b){return new vf(b,this.p)};
l.La=function(){function a(a,b,f){var g=this;return B(function(){var a=Ie.call(i,0,b);return B(a)?He.call(i,b,g.p.length):a}())?g.p[b]:f}function b(a,b){var f=this;return B(function(){var a=Ie.call(i,0,b);return B(a)?He.call(i,b,f.p.length):a}())?f.p[b]:i}return function(d,e,f){switch(arguments.length){case 2:return b.call(this,0,e);case 3:return a.call(this,0,e,f)}c("Invalid arity: "+arguments.length)}}();l.P=!0;l.Q=k("c");
l.Ba=function(){return function(a,b,d){switch(arguments.length){case 2:return be.call(i,this.p,b);case 3:return be.call(i,this.p,b,d)}c("Invalid arity: "+arguments.length)}}();l.O=function(a){return Te.call(i,a)};l.ga=function(){return this.p.length};l.ka=!0;l.Ka=function(a,b,d){a=sd.call(i,this.p);a[b]=d;return new vf(this.c,a)};l.ha=function(){return function(a,b,d){switch(arguments.length){case 2:return E.call(i,a,b,i);case 3:return E.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();
var wf=new vf(i,td.call(i));function R(a){return new vf(i,a)}vf.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return F.call(i,this,b);case 3:return F.call(i,this,b,d)}c("Invalid arity: "+arguments.length)}}();function xf(a){return De.call(i,ie,wf,a)}function yf(a){var b=J(Array.prototype.slice.call(arguments,0),0);return xf.call(i,b)}function zf(){}zf.prototype.s=ba(!1);var Af=new zf;
function Bf(a,b){return ye.call(i,B(re.call(i,b))?B(G.call(i,je.call(i,a),je.call(i,b)))?gf.call(i,hf,jf.call(i,function(a){return G.call(i,le.call(i,b,L.call(i,a),Af),fe.call(i,a))},a)):i:i)}function Cf(a,b,d){for(var e=d.length,f=0;;)if(B(He.call(i,f,e)))if(B(G.call(i,b,d[f])))return f;else f=O.call(i,f,a);else return i}
var Df=function(){function a(a,b,f,g){return B(function(){var f=q.call(i,a);return B(f)?b.hasOwnProperty(a):f}())?f:g}var b=i;return b=function(d,e,f,g){switch(arguments.length){case 2:return b.call(i,d,e,!0,!1);case 4:return a.call(this,d,e,f,g)}c("Invalid arity: "+arguments.length)}}();function Ef(a,b,d){this.c=a;this.keys=b;this.Ha=d}l=Ef.prototype;l.s=function(a,b){return Bf.call(i,a,b)};l.N=function(a,b){return B(se.call(i,b))?Dd.call(i,a,E.call(i,b,0),E.call(i,b,1)):De.call(i,wd,a,b)};
l.H=function(){var a=this;return B(Oe.call(i,a.keys.length))?jf.call(i,function(b){return yf.call(i,b,a.Ha[b])},a.keys):i};l.R=function(a,b){return new Ef(b,this.keys,this.Ha)};l.mb=!0;l.P=!0;l.Q=k("c");l.O=function(a){return Te.call(i,a)};l.ga=function(){return this.keys.length};
l.Ka=function(a,b,d){if(B(q.call(i,b))){var a=Fb.call(i,this.Ha),e=a.hasOwnProperty(b);a[b]=d;return B(e)?new Ef(this.c,this.keys,a):(d=sd.call(i,this.keys),d.push(b),new Ef(this.c,d,a))}else return ne.call(i,sf.call(i,$d.call(i,b,d),K.call(i,a)),this.c)};l.ha=function(){return function(a,b,d){switch(arguments.length){case 2:return F.call(i,a,b,i);case 3:return Df.call(i,b,this.Ha,this.Ha[b],d)}c("Invalid arity: "+arguments.length)}}();td.call(i);function Ff(a,b){return new Ef(i,a,b)}
Ef.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return F.call(i,this,b);case 3:return F.call(i,this,b,d)}c("Invalid arity: "+arguments.length)}}();function Gf(a,b,d){this.c=a;this.count=b;this.ca=d}l=Gf.prototype;l.s=function(a,b){return Bf.call(i,a,b)};l.N=function(a,b){return B(se.call(i,b))?Dd.call(i,a,E.call(i,b,0),E.call(i,b,1)):De.call(i,wd,a,b)};
l.H=function(){var a=this;if(B(Oe.call(i,a.count))){var b=ue.call(i,a.ca);return rf.call(i,function(b){return jf.call(i,xf,tf.call(i,2,a.ca[b]))},b)}else return i};l.R=function(a,b){return new Gf(b,this.count,this.ca)};l.mb=!0;l.P=!0;l.Q=k("c");l.O=function(a){return Te.call(i,a)};l.ga=k("count");
l.Ka=function(a,b,d){var a=pe.call(i,b),e=this.ca[a];if(B(e)){var e=sd.call(i,e),f=Fb.call(i,this.ca);f[a]=e;a=Cf.call(i,2,b,e);return B(a)?(e[I.call(i,a)]=d,new Gf(this.c,this.count,f)):(e.push(b,d),new Gf(this.c,I.call(i,this.count),f))}else return e=Fb.call(i,this.ca),e[a]=td.call(i,b,d),new Gf(this.c,I.call(i,this.count),e)};
l.ha=function(){return function(a,b,d){switch(arguments.length){case 2:return F.call(i,a,b,i);case 3:var e=this.ca[pe.call(i,b)],f=B(e)?Cf.call(i,2,b,e):i;return B(f)?e[I.call(i,f)]:d}c("Invalid arity: "+arguments.length)}}();var Hf=new Gf(i,0,te.call(i));Gf.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return F.call(i,this,b);case 3:return F.call(i,this,b,d)}c("Invalid arity: "+arguments.length)}}();
function $d(a){for(var b=J(Array.prototype.slice.call(arguments,0),0),b=K.call(i,b),d=Hf;;)if(B(b))var e=ge.call(i,b),d=me.call(i,d,L.call(i,b),fe.call(i,b)),b=e;else return d}$d.call(i);function If(a){if(B(ze.call(i,a)))return a;else if(B(function(){var b=Ae.call(i,a);return B(b)?b:Be.call(i,a)}())){var b=a.lastIndexOf("/");return B(He.call(i,b,0))?Re.call(i,a,2):Re.call(i,a,I.call(i,b))}else return i}
function Jf(a){if(B(function(){var b=Ae.call(i,a);return B(b)?b:Be.call(i,a)}())){var b=a.lastIndexOf("/");return B(Je.call(i,b,-1))?Re.call(i,a,2,b):i}else return"\ufdd0'else"}
var Kf=function(){function a(a,d){for(;;)if(B(function(){var e=K.call(i,d);return B(e)?Oe.call(i,a):e}()))var e=Ke.call(i,a),f=N.call(i,d),a=e,d=f;else return i}return function(b,d){switch(arguments.length){case 1:var e;a:for(var f=b;;)if(B(K.call(i,f)))f=N.call(i,f);else{e=i;break a}return e;case 2:return a.call(this,b,d)}c("Invalid arity: "+arguments.length)}}(),Lf=function(){return function(a,b){switch(arguments.length){case 1:return Kf.call(i,a),a;case 2:return Kf.call(i,a,b),b}c("Invalid arity: "+
arguments.length)}}();function Mf(a,b,d,e,f,g){return df.call(i,R([b]),qf.call(i,pf.call(i,R([d]),jf.call(i,function(b){return a.call(i,b,f)},g))),R([e]))}
var Of=function Nf(b,d){return B(Zd.call(i,b))?H.call(i,"nil"):B(we.call(i,b))?H.call(i,"#<undefined>"):B("\ufdd0'else")?df.call(i,B(function(){var e=le.call(i,d,"\ufdd0'meta");return B(e)?(e=B(B(b)?b.P:b)?!0:rd.call(i,Id,b),B(e)?oe.call(i,b):e):e}())?df.call(i,R(["^"]),Nf.call(i,oe.call(i,b),d),R([" "])):i,B(B(B(b)?b.G:b)?!0:rd.call(i,Vd,b))?Xd.call(i,b,d):H.call(i,"#<",Qe.call(i,b),">")):i};Gf.prototype.G=!0;
Gf.prototype.z=function(a,b){return Mf.call(i,function(a){return Mf.call(i,Of,""," ","",b,a)},"{",", ","}",b,a)};Vd.number=!0;Xd.number=function(a){return H.call(i,Qe.call(i,a))};ce.prototype.G=!0;ce.prototype.z=function(a,b){return Mf.call(i,Of,"("," ",")",b,a)};Q.prototype.G=!0;Q.prototype.z=function(a,b){return Mf.call(i,Of,"("," ",")",b,a)};Vd["boolean"]=!0;Xd["boolean"]=function(a){return H.call(i,Qe.call(i,a))};Vd.string=!0;
Xd.string=function(a,b){return B(Ae.call(i,a))?H.call(i,Qe.call(i,":",function(){var b=Jf.call(i,a);return B(b)?Qe.call(i,b,"/"):i}(),If.call(i,a))):B(Be.call(i,a))?H.call(i,Qe.call(i,function(){var b=Jf.call(i,a);return B(b)?Qe.call(i,b,"/"):i}(),If.call(i,a))):B("\ufdd0'else")?H.call(i,B("\ufdd0'readably".call(i,b))?za.call(i,a):a):i};vf.prototype.G=!0;vf.prototype.z=function(a,b){return Mf.call(i,Of,"["," ","]",b,a)};Ue.prototype.G=!0;
Ue.prototype.z=function(a,b){return Mf.call(i,Of,"("," ",")",b,a)};Vd.array=!0;Xd.array=function(a,b){return Mf.call(i,Of,"#<Array [",", ","]>",b,a)};Ve.prototype.G=!0;Ve.prototype.z=function(){return H.call(i,"()")};Ye.prototype.G=!0;Ye.prototype.z=function(a,b){return Mf.call(i,Of,"("," ",")",b,a)};Ef.prototype.G=!0;Ef.prototype.z=function(a,b){return Mf.call(i,function(a){return Mf.call(i,Of,""," ","",b,a)},"{",", ","}",b,a)};function Pf(a,b,d){this.state=a;this.c=b;this.Ub=d}l=Pf.prototype;
l.G=!0;l.z=function(a,b){return df.call(i,R(["#<Atom: "]),Xd.call(i,this.state,b),">")};l.P=!0;l.Q=k("c");l.Cb=k("state");l.s=function(a,b){return Yd.call(i,a,b)};
var Qf=function(){function a(a,b){var f=J(Array.prototype.slice.call(arguments,1),0),g=B(xe.call(i,f))?ff.call(i,$d,f):f,f=le.call(i,g,"\ufdd0'validator"),g=le.call(i,g,"\ufdd0'meta");return new Pf(a,g,f)}var b=i,b=function(b,e){switch(arguments.length){case 1:return new Pf(b,i,i);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.i=1;b.b=function(b){var e=L(b),b=M(b);return a.call(i,e,b)};return b}();
function Rf(a,b){var d=a.Ub;B(d)&&!B(d.call(i,b))&&c("Validator rejected reference state");return a.state=b}
var Sf=function(){function a(a,b,f,g,j,m){var o=J(Array.prototype.slice.call(arguments,5),0);return Rf.call(i,a,ff.call(i,b,a.state,f,g,j,o))}var b=i,b=function(b,e,f,g,j,m){switch(arguments.length){case 2:return Rf.call(i,b,e.call(i,b.state));case 3:return Rf.call(i,b,e.call(i,b.state,f));case 4:return Rf.call(i,b,e.call(i,b.state,f,g));case 5:return Rf.call(i,b,e.call(i,b.state,f,g,j));default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.i=5;b.b=function(b){var e=L(b),
f=L(N(b)),g=L(N(N(b))),j=L(N(N(N(b)))),m=L(N(N(N(N(b))))),b=M(N(N(N(N(b)))));return a.call(i,e,f,g,j,m,b)};return b}();function Tf(a){return Hd.call(i,a)};var Uf=Ff(["\ufdd0'pos","\ufdd0'face"],{"\ufdd0'pos":R([111,211]),"\ufdd0'face":"\ufdd0'west"}),Vf=R(["                            ","                            ","                            ","                            "," pppppppppppp  pppppppppppp "," p    p     p  p     p    p "," e    p     p  p     p    e "," p    p     p  p     p    p "," pppppppppppppppppppppppppp "," p    p  p        p  p    p "," p    p  p        p  p    p "," pppppp  pppp  pppp  pppppp ","      p     o  o     p      ",
"      p     o  o     p      ","      p  oooooooooo  p      ","      p  o        o  p      ","      p  o gggggg o  p      "," ooooopooo gggggg ooopooooo ","      p  o gggggg o  p      ","      p  o        o  p      ","      p  oooooooooo  p      ","      p  o        o  p      ","      p  o        o  p      "," pppppppppppp  pppppppppppp "," p    p     p  p     p    p "," p    p     p  p     p    p "," epp  pppppppooppppppp  ppe ","   p  p  p        p  p  p   ","   p  p  p        p  p  p   "," pppppp  pppp  pppp  pppppp ",
" p          p  p          p "," p          p  p          p "," pppppppppppppppppppppppppp ","                            ","                            ","                            "]),Wf=function(){var a=i;return a=function(b,d){switch(arguments.length){case 1:return a.call(i,b,We);case 2:var e;a:for(var f=b,g=d;;)if(B(G.call(i,0,f))){e=g;break a}else var j=Ke.call(i,f),g=ie.call(i,g,Fe.call(i,f,1)),f=j;return e}c("Invalid arity: "+arguments.length)}}();
function Xf(){var a=Qf.call(i,Ff([],{}));Lf.call(i,function(){return function d(e){return new Q(i,!1,function(){for(var f=e;;)if(B(K.call(i,f))){var g=L.call(i,f),j=K.call(i,function o(d){return new Q(i,!1,function(){for(;;)if(B(K.call(i,d))){var e=L.call(i,d);return P.call(i,function(){var d=uf.call(i,Vf,R([g,e]));return Sf.call(i,a,me,R([e,g]),B(G.call(i,d," "))?Ff([],{}):B(G.call(i,d,"p"))?Ff(["\ufdd0'open","\ufdd0'pellet"],{"\ufdd0'open":i,"\ufdd0'pellet":i}):B(G.call(i,d,"o"))?Ff(["\ufdd0'open"],
{"\ufdd0'open":i}):B(G.call(i,d,"e"))?Ff(["\ufdd0'open","\ufdd0'energy"],{"\ufdd0'open":i,"\ufdd0'energy":i}):B("\ufdd0'else")?i:i)}(),o.call(i,M.call(i,d)))}else return i})}.call(i,Wf.call(i,je.call(i,Vf.call(i,0)))));if(B(j))return df.call(i,j,d.call(i,M.call(i,f)));else f=M.call(i,f)}else return i})}.call(i,Wf.call(i,je.call(i,Vf)))}());return Tf.call(i,a)}var Yf=new dd("#FF0");function S(a,b){return R([a,b])}function Zf(a){return jf.call(i,function(a){return Ge.call(i,8,a)},a)}
function $f(a,b){return jf.call(i,function(a,b){return O.call(i,a,b)},a,b)}function ag(a){return $f.call(i,R([3,3]),Zf.call(i,a))}function bg(a){return $f.call(i,R([0,0]),Zf.call(i,a))}function T(a){return $f.call(i,R([3,7]),Zf.call(i,a))}function cg(a){return $f.call(i,R([0,7]),Zf.call(i,a))}function V(a){return $f.call(i,R([3,0]),Zf.call(i,a))}function dg(a){return $f.call(i,R([7,7]),Zf.call(i,a))}function eg(a){return $f.call(i,R([7,0]),Zf.call(i,a))}
function W(a){return $f.call(i,R([7,3]),Zf.call(i,a))}function X(a){return $f.call(i,R([0,3]),Zf.call(i,a))}function fg(a){return a.$a(0,0,a.width,a.height,i,new dd("#000"))}function gg(a,b){return a.moveTo(L.call(i,b),fe.call(i,b))}function Y(a,b){return a.lineTo(L.call(i,b),fe.call(i,b))}function Z(a,b){var d=a.m;return a.arcTo(Fe.call(i,L.call(i,b),L.call(i,d)),Fe.call(i,fe.call(i,b),fe.call(i,d)),-90,90)}
function $(a,b){var d=a.m;return a.arcTo(Fe.call(i,L.call(i,b),L.call(i,d)),Fe.call(i,fe.call(i,b),fe.call(i,d)),180,-90)}function hg(a,b,d,e){return Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,gg.call(i,new y,W.call(i,S.call(i,a,b))),X.call(i,S.call(i,d,b))),T.call(i,S.call(i,d,b))),V.call(i,S.call(i,d,e))),X.call(i,S.call(i,d,e))),W.call(i,S.call(i,a,e))),V.call(i,S.call(i,a,e))),T.call(i,S.call(i,a,b))),W.call(i,S.call(i,a,b)))}
function ig(a,b){return Z.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Z.call(i,Y.call(i,gg.call(i,new y,W.call(i,S.call(i,a,b))),X.call(i,S.call(i,O.call(i,7,a),b))),T.call(i,S.call(i,O.call(i,7,a),b))),X.call(i,S.call(i,O.call(i,7,a),O.call(i,1,b)))),W.call(i,S.call(i,O.call(i,4,a),O.call(i,1,b)))),T.call(i,S.call(i,O.call(i,4,a),O.call(i,1,b)))),V.call(i,S.call(i,O.call(i,4,a),O.call(i,4,b)))),X.call(i,S.call(i,O.call(i,4,a),O.call(i,4,b)))),
V.call(i,S.call(i,13,O.call(i,4,b)))),T.call(i,S.call(i,O.call(i,3,a),O.call(i,1,b)))),X.call(i,S.call(i,O.call(i,3,a),O.call(i,1,b)))),W.call(i,S.call(i,a,O.call(i,1,b)))),V.call(i,S.call(i,a,O.call(i,1,b)))),W.call(i,S.call(i,a,b)))}
function jg(a){var b=new y;Y.call(i,Y.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Y.call(i,Y.call(i,gg.call(i,b,bg.call(i,S.call(i,0,16))),bg.call(i,S.call(i,5,16))),cg.call(i,S.call(i,5,12))),T.call(i,S.call(i,0,12))),X.call(i,S.call(i,0,12))),X.call(i,S.call(i,0,3))),V.call(i,S.call(i,0,3))),V.call(i,S.call(i,27,3))),W.call(i,S.call(i,27,3))),W.call(i,S.call(i,27,12))),T.call(i,S.call(i,27,12))),dg.call(i,S.call(i,22,12))),eg.call(i,S.call(i,22,16))),
eg.call(i,S.call(i,27,16)));a.f(b,new z("#00F"));b=new y;Y.call(i,$.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,$.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,$.call(i,Y.call(i,gg.call(i,b,X.call(i,S.call(i,0,16))),X.call(i,S.call(i,5,16))),V.call(i,S.call(i,5,16))),T.call(i,S.call(i,5,12))),X.call(i,S.call(i,5,12))),W.call(i,S.call(i,0,12))),V.call(i,S.call(i,0,12))),T.call(i,S.call(i,0,3))),W.call(i,
S.call(i,0,3))),X.call(i,S.call(i,13,3))),T.call(i,S.call(i,13,3))),V.call(i,S.call(i,13,7))),W.call(i,S.call(i,13,7))),V.call(i,S.call(i,14,7))),T.call(i,S.call(i,14,3))),W.call(i,S.call(i,14,3))),X.call(i,S.call(i,27,3))),T.call(i,S.call(i,27,3))),V.call(i,S.call(i,27,12))),X.call(i,S.call(i,27,12))),W.call(i,S.call(i,22,12))),T.call(i,S.call(i,22,12))),V.call(i,S.call(i,22,16))),W.call(i,S.call(i,22,16))),W.call(i,S.call(i,27,16)));a.f(b,new z("#00F"));a.f(hg.call(i,2,5,5,7),new z("#00F"));a.f(hg.call(i,
7,5,11,7),new z("#00F"));a.f(hg.call(i,16,5,20,7),new z("#00F"));a.f(hg.call(i,22,5,25,7),new z("#00F"));a.f(hg.call(i,2,9,5,10),new z("#00F"));a.f(hg.call(i,22,9,25,10),new z("#00F"));a.f(hg.call(i,7,18,8,22),new z("#00F"));a.f(hg.call(i,19,18,20,22),new z("#00F"));a.f(hg.call(i,7,24,11,25),new z("#00F"));a.f(hg.call(i,16,24,20,25),new z("#00F"));b=new y;Y.call(i,Y.call(i,Y.call(i,Y.call(i,gg.call(i,b,ag.call(i,S.call(i,10,15))),ag.call(i,S.call(i,17,15))),ag.call(i,S.call(i,17,19))),ag.call(i,S.call(i,
10,19))),ag.call(i,S.call(i,10,15)));a.f(b,new z("#00F"));b=new y;Y.call(i,Y.call(i,Y.call(i,Y.call(i,gg.call(i,b,dg.call(i,S.call(i,10,15))),cg.call(i,S.call(i,17,15))),bg.call(i,S.call(i,17,19))),eg.call(i,S.call(i,10,19))),dg.call(i,S.call(i,10,15)));a.f(b,new z("#00F"));a.f(ig.call(i,10,9),new z("#00F"));a.f(ig.call(i,10,21),new z("#00F"));a.f(ig.call(i,10,27),new z("#00F"));b=new y;Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,
Z.call(i,Y.call(i,Z.call(i,gg.call(i,b,T.call(i,S.call(i,7,9))),W.call(i,S.call(i,7,9))),X.call(i,S.call(i,8,9))),T.call(i,S.call(i,8,9))),V.call(i,S.call(i,8,12))),W.call(i,S.call(i,8,12))),X.call(i,S.call(i,11,12))),T.call(i,S.call(i,11,12))),V.call(i,S.call(i,11,13))),X.call(i,S.call(i,11,13))),W.call(i,S.call(i,8,13))),T.call(i,S.call(i,8,13))),V.call(i,S.call(i,8,16))),X.call(i,S.call(i,8,16))),W.call(i,S.call(i,7,16))),V.call(i,S.call(i,7,16))),T.call(i,S.call(i,7,9)));a.f(b,new z("#00F"));
b=new y;Y.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,gg.call(i,b,T.call(i,S.call(i,19,9))),W.call(i,S.call(i,19,9))),X.call(i,S.call(i,20,9))),T.call(i,S.call(i,20,9))),V.call(i,S.call(i,20,16))),X.call(i,S.call(i,20,16))),W.call(i,S.call(i,19,16))),V.call(i,S.call(i,19,16))),T.call(i,S.call(i,19,13))),X.call(i,S.call(i,19,13))),W.call(i,S.call(i,16,13))),V.call(i,S.call(i,16,13))),T.call(i,S.call(i,
16,12))),W.call(i,S.call(i,16,12))),X.call(i,S.call(i,19,12))),V.call(i,S.call(i,19,12))),T.call(i,S.call(i,19,9)));a.f(b,new z("#00F"));b=new y;Y.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,gg.call(i,b,T.call(i,S.call(i,2,24))),W.call(i,S.call(i,2,24))),X.call(i,S.call(i,5,24))),T.call(i,S.call(i,5,24))),V.call(i,S.call(i,5,28))),X.call(i,S.call(i,5,28))),W.call(i,S.call(i,4,28))),V.call(i,S.call(i,4,28))),T.call(i,S.call(i,4,25))),X.call(i,
S.call(i,4,25))),W.call(i,S.call(i,2,25))),V.call(i,S.call(i,2,25))),T.call(i,S.call(i,2,24)));a.f(b,new z("#00F"));b=new y;Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,gg.call(i,b,T.call(i,S.call(i,22,24))),W.call(i,S.call(i,22,24))),X.call(i,S.call(i,25,24))),T.call(i,S.call(i,25,24))),V.call(i,S.call(i,25,25))),X.call(i,S.call(i,25,25))),W.call(i,S.call(i,23,25))),T.call(i,S.call(i,23,25))),V.call(i,S.call(i,23,28))),X.call(i,S.call(i,
23,28))),W.call(i,S.call(i,22,28))),V.call(i,S.call(i,22,28))),T.call(i,S.call(i,22,24)));return a.f(b,new z("#00F"))}function kg(a,b){var d=new z("#FFB9AF"),e=new dd("#FFB9AF"),f=ag.call(i,b),g=ke.call(i,f,0,i),f=ke.call(i,f,1,i);return a.Na(g,f,1,1,d,e,h)}function lg(a,b){return Lf.call(i,jf.call(i,function(b){var e=L.call(i,b),f=ke.call(i,e,0,i),e=ke.call(i,e,1,i),b=fe.call(i,b);return B(Ce.call(i,b,"\ufdd0'pellet"))?kg.call(i,a,S.call(i,f,e)):i},b))}
function mg(a,b){var d=L.call(i,b.call(i,"\ufdd0'pos")),e=fe.call(i,b.call(i,"\ufdd0'pos"));return a.Na(d,e,7,7,i,Yf,h)}(function(){var a=qd.call(i,224,288),b=Xf.call(i);fg.call(i,a);jg.call(i,a);lg.call(i,a,b);mg.call(i,a,Uf);b=cc.call(i,"playfield");a.n&&c(Error("Component already rendered"));a.h||a.B();b?b.insertBefore(a.h,i):a.J.$.body.appendChild(a.h);(!a.sa||a.sa.n)&&a.T()}).call(i);