function b(a){throw a;}var h=void 0,i=null;function aa(){return function(a){return a}}function k(a){return function(){return this[a]}}function ba(a){return function(){return a}}var l,n=this;function ca(){}
function p(a){var c=typeof a;if(c=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return c;var d=Object.prototype.toString.call(a);if(d=="[object Window]")return"object";if(d=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(d=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(c=="function"&&typeof a.call=="undefined")return"object";return c}function da(a){return p(a)=="array"}function ea(a){var c=p(a);return c=="array"||c=="object"&&typeof a.length=="number"}function q(a){return typeof a=="string"}function fa(a){return typeof a=="number"}function ga(a){return p(a)=="function"}function ha(a){a=p(a);return a=="object"||a=="array"||a=="function"}function ia(a){return a[ja]||(a[ja]=++ka)}var ja="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),ka=0;
function la(a,c,d){return a.call.apply(a.bind,arguments)}function ma(a,c,d){var e=c||n;if(arguments.length>2){var f=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,f);return a.apply(e,c)}}else return function(){return a.apply(e,arguments)}}function na(a,c,d){na=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?la:ma;return na.apply(i,arguments)}var oa=Date.now||function(){return+new Date};
function s(a,c){function d(){}d.prototype=c.prototype;a.k=c.prototype;a.prototype=new d;a.prototype.constructor=a};function pa(a){var c=a.length-1;return c>=0&&a.indexOf("%",c)==c}function qa(a){if(!ra.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(sa,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(ta,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(ua,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(va,"&quot;"));return a}var sa=/&/g,ta=/</g,ua=/>/g,va=/\"/g,ra=/[&<>\"]/,wa={"\000":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\x0B",'"':'\\"',"\\":"\\\\"},xa={"'":"\\'"};
function za(a){var o;a=String(a);if(a.quote)return a.quote();else{for(var c=['"'],d=0;d<a.length;d++){var e=a.charAt(d),f=e.charCodeAt(0),g=c,j=d+1,m;if(!(m=wa[e])){if(!(f>31&&f<127))if(e in xa)e=xa[e];else if(e in wa)o=xa[e]=wa[e],e=o;else{f=e;m=e.charCodeAt(0);if(m>31&&m<127)f=e;else{if(m<256){if(f="\\x",m<16||m>256)f+="0"}else f="\\u",m<4096&&(f+="0");f+=m.toString(16).toUpperCase()}e=xa[e]=f}m=e}g[j]=m}c.push('"');return c.join("")}}
function Aa(a,c){for(var d=0,e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=String(c).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),g=Math.max(e.length,f.length),j=0;d==0&&j<g;j++){var m=e[j]||"",o=f[j]||"",r=RegExp("(\\d*)(\\D*)","g"),A=RegExp("(\\d*)(\\D*)","g");do{var G=r.exec(m)||["","",""],W=A.exec(o)||["","",""];if(G[0].length==0&&W[0].length==0)break;d=Ba(G[1].length==0?0:parseInt(G[1],10),W[1].length==0?0:parseInt(W[1],10))||Ba(G[2].length==0,W[2].length==0)||Ba(G[2],W[2])}while(d==
0)}return d}function Ba(a,c){if(a<c)return-1;else if(a>c)return 1;return 0}function Ca(a){for(var c=0,d=0;d<a.length;++d)c=31*c+a.charCodeAt(d),c%=4294967296;return c}var Da=Math.random()*2147483648|0;var Ea,Fa,Ga,Ha,Ia,Ja,Ka=(Ja="ScriptEngine"in n&&n.ScriptEngine()=="JScript")?n.ScriptEngineMajorVersion()+"."+n.ScriptEngineMinorVersion()+"."+n.ScriptEngineBuildVersion():"0";function La(a,c){this.v=Ja?[]:"";a!=i&&this.append.apply(this,arguments)}Ja?(La.prototype.cb=0,La.prototype.append=function(a,c,d){c==i?this.v[this.cb++]=a:(this.v.push.apply(this.v,arguments),this.cb=this.v.length);return this}):La.prototype.append=function(a,c,d){this.v+=a;if(c!=i)for(var e=1;e<arguments.length;e++)this.v+=arguments[e];return this};La.prototype.clear=function(){Ja?this.cb=this.v.length=0:this.v=""};
La.prototype.toString=function(){if(Ja){var a=this.v.join("");this.clear();a&&this.append(a);return a}else return this.v};var Ma;function Na(){}Na.prototype.Cb=!1;Na.prototype.ca=function(){if(!this.Cb)this.Cb=!0,this.h()};Na.prototype.h=function(){};var Oa=Array.prototype,Pa=Oa.indexOf?function(a,c,d){return Oa.indexOf.call(a,c,d)}:function(a,c,d){d=d==i?0:d<0?Math.max(0,a.length+d):d;if(q(a))return!q(c)||c.length!=1?-1:a.indexOf(c,d);for(;d<a.length;d++)if(d in a&&a[d]===c)return d;return-1},Qa=Oa.forEach?function(a,c,d){Oa.forEach.call(a,c,d)}:function(a,c,d){for(var e=a.length,f=q(a)?a.split(""):a,g=0;g<e;g++)g in f&&c.call(d,f[g],g,a)},Ra=Oa.map?function(a,c,d){return Oa.map.call(a,c,d)}:function(a,c,d){for(var e=a.length,f=Array(e),g=q(a)?
a.split(""):a,j=0;j<e;j++)j in g&&(f[j]=c.call(d,g[j],j,a));return f};function Sa(a){return Oa.concat.apply(Oa,arguments)}function Ta(a){if(da(a))return Sa(a);else{for(var c=[],d=0,e=a.length;d<e;d++)c[d]=a[d];return c}}function Ua(a,c,d){return arguments.length<=2?Oa.slice.call(a,c):Oa.slice.call(a,c,d)};function Va(){return n.navigator?n.navigator.userAgent:i}Ia=Ha=Ga=Fa=Ea=!1;var Wa;if(Wa=Va()){var Xa=n.navigator;Ea=Wa.indexOf("Opera")==0;Fa=!Ea&&Wa.indexOf("MSIE")!=-1;Ha=(Ga=!Ea&&Wa.indexOf("WebKit")!=-1)&&Wa.indexOf("Mobile")!=-1;Ia=!Ea&&!Ga&&Xa.product=="Gecko"}var Ya=Ea,t=Fa,Za=Ia,$a=Ga,ab=Ha,bb=n.navigator,cb=(bb&&bb.platform||"").indexOf("Mac")!=-1,db;
a:{var eb="",fb;if(Ya&&n.opera)var gb=n.opera.version,eb=typeof gb=="function"?gb():gb;else if(Za?fb=/rv\:([^\);]+)(\)|;)/:t?fb=/MSIE\s+([^\);]+)(\)|;)/:$a&&(fb=/WebKit\/(\S+)/),fb)var hb=fb.exec(Va()),eb=hb?hb[1]:"";if(t){var ib,jb=n.document;ib=jb?jb.documentMode:h;if(ib>parseFloat(eb)){db=String(ib);break a}}db=eb}var kb={};function lb(a){return kb[a]||(kb[a]=Aa(db,a)>=0)};!t||lb("9");t&&lb("8");function mb(a,c){this.type=a;this.currentTarget=this.target=c}s(mb,Na);mb.prototype.h=function(){delete this.type;delete this.target;delete this.currentTarget};mb.prototype.va=!1;mb.prototype.Ya=!0;var nb=new Function("a","return a");function ob(a,c){a&&this.Ja(a,c)}s(ob,mb);l=ob.prototype;l.target=i;l.relatedTarget=i;l.offsetX=0;l.offsetY=0;l.clientX=0;l.clientY=0;l.screenX=0;l.screenY=0;l.button=0;l.keyCode=0;l.charCode=0;l.ctrlKey=!1;l.altKey=!1;l.shiftKey=!1;l.metaKey=!1;l.bc=!1;l.hb=i;
l.Ja=function(a,c){var d=this.type=a.type;mb.call(this,d);this.target=a.target||a.srcElement;this.currentTarget=c;var e=a.relatedTarget;if(e){if(Za)try{nb(e.nodeName)}catch(f){e=i}}else if(d=="mouseover")e=a.fromElement;else if(d=="mouseout")e=a.toElement;this.relatedTarget=e;this.offsetX=a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(d=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.bc=cb?a.metaKey:a.ctrlKey;this.state=a.state;this.hb=a;delete this.Ya;delete this.va};l.h=function(){ob.k.h.call(this);this.relatedTarget=this.currentTarget=this.target=this.hb=i};function pb(){}var qb=0;l=pb.prototype;l.key=0;l.wa=!1;l.vb=!1;l.Ja=function(a,c,d,e,f,g){ga(a)?this.Fb=!0:a&&a.handleEvent&&ga(a.handleEvent)?this.Fb=!1:b(Error("Invalid listener argument"));this.ta=a;this.Jb=c;this.src=d;this.type=e;this.capture=!!f;this.Sa=g;this.vb=!1;this.key=++qb;this.wa=!1};l.handleEvent=function(a){return this.Fb?this.ta.call(this.Sa||this.src,a):this.ta.handleEvent.call(this.ta,a)};function rb(a,c){this.Gb=c;this.ea=[];a>this.Gb&&b(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var d=0;d<a;d++)this.ea.push(this.J?this.J():{})}s(rb,Na);rb.prototype.J=i;rb.prototype.Bb=i;rb.prototype.getObject=function(){return this.ea.length?this.ea.pop():this.J?this.J():{}};function sb(a,c){a.ea.length<a.Gb?a.ea.push(c):tb(a,c)}function tb(a,c){if(a.Bb)a.Bb(c);else if(ha(c))if(ga(c.ca))c.ca();else for(var d in c)delete c[d]}
rb.prototype.h=function(){rb.k.h.call(this);for(var a=this.ea;a.length;)tb(this,a.pop());delete this.ea};var ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb;
(function(){function a(){return{g:0,u:0}}function c(){return[]}function d(){function a(c){return j.call(a.src,a.key,c)}return a}function e(){return new pb}function f(){return new ob}var g=Ja&&!(Aa(Ka,"5.7")>=0),j;zb=function(a){j=a};if(g){ub=function(){return m.getObject()};vb=function(a){sb(m,a)};wb=function(){return o.getObject()};xb=function(a){sb(o,a)};yb=function(){return r.getObject()};Ab=function(){sb(r,d())};Bb=function(){return A.getObject()};Cb=function(a){sb(A,a)};Db=function(){return G.getObject()};
Eb=function(a){sb(G,a)};var m=new rb(0,600);m.J=a;var o=new rb(0,600);o.J=c;var r=new rb(0,600);r.J=d;var A=new rb(0,600);A.J=e;var G=new rb(0,600);G.J=f}else ub=a,vb=ca,wb=c,xb=ca,yb=d,Ab=ca,Bb=e,Cb=ca,Db=f,Eb=ca})();function Fb(a,c,d){for(var e in a)c.call(d,a[e],e,a)}function Gb(a){var c={},d;for(d in a)c[d]=a[d];return c}var Hb=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];function Ib(a,c){for(var d,e,f=1;f<arguments.length;f++){e=arguments[f];for(d in e)a[d]=e[d];for(var g=0;g<Hb.length;g++)d=Hb[g],Object.prototype.hasOwnProperty.call(e,d)&&(a[d]=e[d])}};var Jb={},u={},Kb={},Lb={};
function Mb(a,c,d,e,f){if(c)if(da(c)){for(var g=0;g<c.length;g++)Mb(a,c[g],d,e,f);return i}else{var e=!!e,j=u;c in j||(j[c]=ub());j=j[c];e in j||(j[e]=ub(),j.g++);var j=j[e],m=ia(a),o;j.u++;if(j[m]){o=j[m];for(g=0;g<o.length;g++)if(j=o[g],j.ta==d&&j.Sa==f){if(j.wa)break;return o[g].key}}else o=j[m]=wb(),j.g++;g=yb();g.src=a;j=Bb();j.Ja(d,g,a,c,e,f);d=j.key;g.key=d;o.push(j);Jb[d]=j;Kb[m]||(Kb[m]=wb());Kb[m].push(j);a.addEventListener?(a==n||!a.eb)&&a.addEventListener(c,g,e):a.attachEvent(c in Lb?
Lb[c]:Lb[c]="on"+c,g);return d}else b(Error("Invalid event type"))}function Nb(a,c,d,e,f){if(da(c))for(var g=0;g<c.length;g++)Nb(a,c[g],d,e,f);else if(e=!!e,a=Ob(a,c,e))for(g=0;g<a.length;g++)if(a[g].ta==d&&a[g].capture==e&&a[g].Sa==f){Pb(a[g].key);break}}
function Pb(a){if(Jb[a]){var c=Jb[a];if(!c.wa){var d=c.src,e=c.type,f=c.Jb,g=c.capture;d.removeEventListener?(d==n||!d.eb)&&d.removeEventListener(e,f,g):d.detachEvent&&d.detachEvent(e in Lb?Lb[e]:Lb[e]="on"+e,f);d=ia(d);f=u[e][g][d];if(Kb[d]){var j=Kb[d],m=Pa(j,c);m>=0&&Oa.splice.call(j,m,1);j.length==0&&delete Kb[d]}c.wa=!0;f.Hb=!0;Qb(e,g,d,f);delete Jb[a]}}}
function Qb(a,c,d,e){if(!e.Wa&&e.Hb){for(var f=0,g=0;f<e.length;f++)if(e[f].wa){var j=e[f].Jb;j.src=i;Ab(j);Cb(e[f])}else f!=g&&(e[g]=e[f]),g++;e.length=g;e.Hb=!1;g==0&&(xb(e),delete u[a][c][d],u[a][c].g--,u[a][c].g==0&&(vb(u[a][c]),delete u[a][c],u[a].g--),u[a].g==0&&(vb(u[a]),delete u[a]))}}
function Rb(a){var c,d=0,e=c==i;c=!!c;if(a==i)Fb(Kb,function(a){for(var f=a.length-1;f>=0;f--){var g=a[f];if(e||c==g.capture)Pb(g.key),d++}});else if(a=ia(a),Kb[a])for(var a=Kb[a],f=a.length-1;f>=0;f--){var g=a[f];if(e||c==g.capture)Pb(g.key),d++}}function Ob(a,c,d){var e=u;return c in e&&(e=e[c],d in e&&(e=e[d],a=ia(a),e[a]))?e[a]:i}
function Sb(a,c,d,e,f){var g=1,c=ia(c);if(a[c]){a.u--;a=a[c];a.Wa?a.Wa++:a.Wa=1;try{for(var j=a.length,m=0;m<j;m++){var o=a[m];o&&!o.wa&&(g&=Tb(o,f)!==!1)}}finally{a.Wa--,Qb(d,e,c,a)}}return Boolean(g)}function Tb(a,c){var d=a.handleEvent(c);a.vb&&Pb(a.key);return d}
zb(function(a,c){if(!Jb[a])return!0;var d=Jb[a],e=d.type,f=u;if(!(e in f))return!0;var f=f[e],g,j;Ma===h&&(Ma=t&&!n.addEventListener);if(Ma){var m;if(!(m=c))a:{m="window.event".split(".");for(var o=n;g=m.shift();)if(o[g]!=i)o=o[g];else{m=i;break a}m=o}g=m;m=!0 in f;o=!1 in f;if(m){if(g.keyCode<0||g.returnValue!=h)return!0;a:{var r=!1;if(g.keyCode==0)try{g.keyCode=-1;break a}catch(A){r=!0}if(r||g.returnValue==h)g.returnValue=!0}}r=Db();r.Ja(g,this);g=!0;try{if(m){for(var G=wb(),W=r.currentTarget;W;W=
W.parentNode)G.push(W);j=f[!0];j.u=j.g;for(var ya=G.length-1;!r.va&&ya>=0&&j.u;ya--)r.currentTarget=G[ya],g&=Sb(j,G[ya],e,!0,r);if(o){j=f[!1];j.u=j.g;for(ya=0;!r.va&&ya<G.length&&j.u;ya++)r.currentTarget=G[ya],g&=Sb(j,G[ya],e,!1,r)}}else g=Tb(d,r)}finally{if(G)G.length=0,xb(G);r.ca();Eb(r)}return g}e=new ob(c,this);try{g=Tb(d,e)}finally{e.ca()}return g});function Ub(a){this.fa=a}s(Ub,Na);var Vb=new rb(0,100),Wb=[];function Xb(a,c,d,e){da(d)||(Wb[0]=d,d=Wb);for(var f=0;f<d.length;f++){var g=a,j=Mb(c,d[f],e||a,!1,a.fa||a);g.t?g.t[j]=!0:g.X?(g.t=Vb.getObject(),g.t[g.X]=!0,g.X=i,g.t[j]=!0):g.X=j}}
function Yb(a,c,d,e,f,g){if(a.X||a.t)if(da(d))for(var j=0;j<d.length;j++)Yb(a,c,d[j],e,f,g);else{a:{e=e||a;g=g||a.fa||a;f=!!f;if(c=Ob(c,d,f))for(d=0;d<c.length;d++)if(c[d].ta==e&&c[d].capture==f&&c[d].Sa==g){c=c[d];break a}c=i}if(c)if(c=c.key,Pb(c),a.t)a=a.t,c in a&&delete a[c];else if(a.X==c)a.X=i}}function Zb(a){if(a.t){for(var c in a.t)Pb(c),delete a.t[c];sb(Vb,a.t);a.t=i}else a.X&&Pb(a.X)}Ub.prototype.h=function(){Ub.k.h.call(this);Zb(this)};Ub.prototype.handleEvent=function(){b(Error("EventHandler.handleEvent not implemented"))};var $b,ac=!t||lb("9");!Za&&!t||t&&lb("9")||Za&&lb("1.9.1");t&&lb("9");function bc(a,c){var d;d=(d=a.className)&&typeof d.split=="function"?d.split(/\s+/):[];var e=Ua(arguments,1),f;f=d;for(var g=0,j=0;j<e.length;j++)Pa(f,e[j])>=0||(f.push(e[j]),g++);f=g==e.length;a.className=d.join(" ");return f};function cc(a,c){this.width=a;this.height=c}l=cc.prototype;l.Qa=function(){return new cc(this.width,this.height)};l.toString=function(){return"("+this.width+" x "+this.height+")"};l.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};l.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};l.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
l.scale=function(a){this.width*=a;this.height*=a;return this};function dc(a){return q(a)?document.getElementById(a):a}function ec(a,c){Fb(c,function(c,e){e=="style"?a.style.cssText=c:e=="class"?a.className=c:e=="for"?a.htmlFor=c:e in fc?a.setAttribute(fc[e],c):a[e]=c})}var fc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function gc(a,c,d,e){function f(d){d&&c.appendChild(q(d)?a.createTextNode(d):d)}for(;e<d.length;e++){var g=d[e];ea(g)&&!(ha(g)&&g.nodeType>0)?Qa(hc(g)?Ta(g):g,f):f(g)}}function ic(a){for(var c;c=a.firstChild;)a.removeChild(c)}function jc(a){a&&a.parentNode&&a.parentNode.removeChild(a)}function hc(a){if(a&&typeof a.length=="number")if(ha(a))return typeof a.item=="function"||typeof a.item=="string";else if(ga(a))return typeof a.item=="function";return!1}
function kc(a){this.da=a||n.document||document}l=kc.prototype;l.a=function(a){return q(a)?this.da.getElementById(a):a};l.B=function(a,c,d){var e=this.da,f=arguments,g=f[0],j=f[1];if(!ac&&j&&(j.name||j.type)){g=["<",g];j.name&&g.push(' name="',qa(j.name),'"');if(j.type){g.push(' type="',qa(j.type),'"');var m={};Ib(m,j);j=m;delete j.type}g.push(">");g=g.join("")}g=e.createElement(g);if(j)q(j)?g.className=j:da(j)?bc.apply(i,[g].concat(j)):ec(g,j);f.length>2&&gc(e,g,f,2);return g};l.createElement=function(a){return this.da.createElement(a)};
l.createTextNode=function(a){return this.da.createTextNode(a)};l.appendChild=function(a,c){a.appendChild(c)};l.append=function(a,c){gc(a.nodeType==9?a:a.ownerDocument||a.document,a,arguments,1)};function lc(){}s(lc,Na);l=lc.prototype;l.eb=!0;l.Xa=i;l.pb=function(a){this.Xa=a};l.addEventListener=function(a,c,d,e){Mb(this,a,c,d,e)};l.removeEventListener=function(a,c,d,e){Nb(this,a,c,d,e)};
l.dispatchEvent=function(a){var c=a.type||a,d=u;if(c in d){if(q(a))a=new mb(a,this);else if(a instanceof mb)a.target=a.target||this;else{var e=a,a=new mb(c,this);Ib(a,e)}var e=1,f,d=d[c],c=!0 in d,g;if(c){f=[];for(g=this;g;g=g.Xa)f.push(g);g=d[!0];g.u=g.g;for(var j=f.length-1;!a.va&&j>=0&&g.u;j--)a.currentTarget=f[j],e&=Sb(g,f[j],a.type,!0,a)&&a.Ya!=!1}if(!1 in d)if(g=d[!1],g.u=g.g,c)for(j=0;!a.va&&j<f.length&&g.u;j++)a.currentTarget=f[j],e&=Sb(g,f[j],a.type,!1,a)&&a.Ya!=!1;else for(f=this;!a.va&&
f&&g.u;f=f.Xa)a.currentTarget=f,e&=Sb(g,f,a.type,!1,a)&&a.Ya!=!1;a=Boolean(e)}else a=!0;return a};l.h=function(){lc.k.h.call(this);Rb(this);this.Xa=i};function mc(a){return a*Math.PI/180};function nc(a,c,d,e,f,g){arguments.length==6?this.setTransform(a,c,d,e,f,g):arguments.length!=0?b(Error("Insufficient matrix parameters")):(this.L=this.N=1,this.F=this.M=this.Z=this.$=0)}l=nc.prototype;l.Qa=function(){return new nc(this.L,this.F,this.M,this.N,this.Z,this.$)};l.setTransform=function(a,c,d,e,f,g){(!fa(a)||!fa(c)||!fa(d)||!fa(e)||!fa(f)||!fa(g))&&b(Error("Invalid transform parameters"));this.L=a;this.F=c;this.M=d;this.N=e;this.Z=f;this.$=g;return this};
l.scale=function(a,c){this.L*=a;this.F*=a;this.M*=c;this.N*=c;return this};l.translate=function(a,c){this.Z+=a*this.L+c*this.M;this.$+=a*this.F+c*this.N;return this};l.rotate=function(a,c,d){a=oc(a,c,d);c=this.L;d=this.M;this.L=a.L*c+a.F*d;this.M=a.M*c+a.N*d;this.Z+=a.Z*c+a.$*d;c=this.F;d=this.N;this.F=a.L*c+a.F*d;this.N=a.M*c+a.N*d;this.$+=a.Z*c+a.$*d;return this};l.toString=function(){return"matrix("+[this.L,this.F,this.M,this.N,this.Z,this.$].join(",")+")"};
function oc(a,c,d){var e=new nc,f=Math.cos(a),a=Math.sin(a);return e.setTransform(f,a,-a,f,c-c*f+d*a,d-c*a-d*f)};function v(a,c){this.c=a;this.D=c;this.eb=!1}s(v,lc);l=v.prototype;l.D=i;l.c=i;l.rb=i;l.a=k("c");l.addEventListener=function(a,c,d,e){Mb(this.c,a,c,d,e)};l.removeEventListener=function(a,c,d,e){Nb(this.c,a,c,d,e)};l.h=function(){v.k.h.call(this);Rb(this.c)};function w(a,c,d,e){v.call(this,a,c);this.qb=d;this.D.nb(this,d);this.fill=e;this.D.Za(this,e)}s(w,v);w.prototype.fill=i;w.prototype.qb=i;w.prototype.Sb=k("fill");w.prototype.Tb=k("qb");function pc(a,c,d,e){w.call(this,a,c,d,e)}s(pc,w);function qc(a,c){v.call(this,a,c)}s(qc,v);function rc(a,c){v.call(this,a,c)}s(rc,v);function sc(a,c,d,e){w.call(this,a,c,d,e)}s(sc,w);function tc(a,c,d,e){w.call(this,a,c,d,e)}s(tc,w);function uc(a,c){v.call(this,a,c)}s(uc,qc);uc.prototype.clear=function(){ic(this.a())};function vc(a,c,d,e){w.call(this,a,c,d,e)}s(vc,pc);vc.prototype.mb=function(a,c){wc(this.a(),{cx:a,cy:c})};function xc(a,c,d,e){w.call(this,a,c,d,e)}s(xc,tc);function yc(a,c,d,e){w.call(this,a,c,d,e)}s(yc,sc);yc.prototype.$a=function(a){wc(this.a(),{d:zc(a)})};function Ac(a,c){v.call(this,a,c)}s(Ac,rc);function Bc(){return this.c=this.D.K.a(this.V)||this.c}function Cc(a,c){this.V=a.id;v.call(this,a,c)}s(Cc,qc);Cc.prototype.a=Bc;Cc.prototype.clear=function(){ic(this.a())};function Dc(a,c,d,e,f,g,j,m){this.V=a.id;w.call(this,a,c,j,m);this.Qb=d;this.Rb=e;this.Kb=f;this.Mb=g}s(Dc,pc);Dc.prototype.a=Bc;Dc.prototype.mb=function(a,c){this.Qb=a;this.Rb=c;Ec(this.a(),a-this.Kb,c-this.Mb,this.Kb*2,this.Mb*2)};function Fc(a,c,d,e){this.V=a.id;w.call(this,a,c,d,e)}s(Fc,tc);Fc.prototype.a=Bc;
function Gc(a,c,d,e){this.V=a.id;w.call(this,a,c,d,e)}s(Gc,sc);Gc.prototype.a=Bc;Gc.prototype.$a=function(a){var c=this.a(),a=Hc(a);Ic?c.path=a:c.setAttribute("path",a)};function Jc(a,c){this.V=a.id;v.call(this,a,c)}s(Jc,rc);Jc.prototype.a=Bc;function x(){this.j=[];this.g=[];this.G=[]}x.prototype.oa=i;x.prototype.m=i;x.prototype.ya=!0;var Kc=[2,2,6,6,0];l=x.prototype;l.clear=function(){this.j.length=0;this.g.length=0;this.G.length=0;delete this.oa;delete this.m;delete this.ya;return this};l.moveTo=function(a,c){this.j[this.j.length-1]==0?this.G.length-=2:(this.j.push(0),this.g.push(1));this.G.push(a,c);this.m=this.oa=[a,c];return this};
l.lineTo=function(a){var c=this.j[this.j.length-1];c==i&&b(Error("Path cannot start with lineTo"));c!=1&&(this.j.push(1),this.g.push(0));for(c=0;c<arguments.length;c+=2){var d=arguments[c],e=arguments[c+1];this.G.push(d,e)}this.g[this.g.length-1]+=c/2;this.m=[d,e];return this};
l.xb=function(a){var c=this.j[this.j.length-1];c==i&&b(Error("Path cannot start with curve"));c!=2&&(this.j.push(2),this.g.push(0));for(c=0;c<arguments.length;c+=6){var d=arguments[c+4],e=arguments[c+5];this.G.push(arguments[c],arguments[c+1],arguments[c+2],arguments[c+3],d,e)}this.g[this.g.length-1]+=c/6;this.m=[d,e];return this};l.close=function(){var a=this.j[this.j.length-1];a==i&&b(Error("Path cannot start with close"));if(a!=4)this.j.push(4),this.g.push(1),this.m=this.oa;return this};
l.arcTo=function(a,c,d,e){var f=this.m[0]-a*Math.cos(mc(d))+a*Math.cos(mc(d+e)),g=this.m[1]-c*Math.sin(mc(d))+c*Math.sin(mc(d+e));this.j.push(3);this.g.push(1);this.G.push(a,c,d,e,f,g);this.ya=!1;this.m=[f,g];return this};
l.ub=function(a,c,d,e){var f=this.m[0]-a*Math.cos(mc(d)),g=this.m[1]-c*Math.sin(mc(d)),j=mc(e),e=Math.ceil(Math.abs(j)/Math.PI*2);j/=e;for(var d=mc(d),m=0;m<e;m++){var o=Math.cos(d),r=Math.sin(d),A=4/3*Math.sin(j/2)/(1+Math.cos(j/2)),G=f+(o-A*r)*a,W=g+(r+A*o)*c;d+=j;o=Math.cos(d);r=Math.sin(d);this.xb(G,W,f+(o+A*r)*a,g+(r-A*o)*c,f+o*a,g+r*c)}return this};function Lc(a,c){for(var d=a.G,e=0,f=0,g=a.j.length;f<g;f++){var j=a.j[f],m=Kc[j]*a.g[f];c(j,d.slice(e,e+m));e+=m}}
l.Qa=function(){var a=new this.constructor;a.j=this.j.concat();a.g=this.g.concat();a.G=this.G.concat();a.oa=this.oa&&this.oa.concat();a.m=this.m&&this.m.concat();a.ya=this.ya;return a};var Mc={};Mc[0]=x.prototype.moveTo;Mc[1]=x.prototype.lineTo;Mc[4]=x.prototype.close;Mc[2]=x.prototype.xb;Mc[3]=x.prototype.ub;function Nc(a){if(a.ya)return a.Qa();var c=new x;Lc(a,function(a,e){Mc[a].apply(c,e)});return c};function Oc(a){v.call(this,i,a);this.w=[]}s(Oc,qc);Oc.prototype.clear=function(){if(this.w.length)this.w.length=0,Pc(this.D)};Oc.prototype.appendChild=function(a){this.w.push(a)};Oc.prototype.C=function(){for(var a=0,c=this.w.length;a<c;a++)Qc(this.D,this.w[a])};function Rc(a,c,d,e,f,g,j,m){w.call(this,a,c,j,m);this.yb=d;this.zb=e;this.Lb=f;this.Nb=g;this.aa=new x;Sc(this);this.Ib=new Tc(i,c,this.aa,j,m)}s(Rc,pc);
function Sc(a){a.aa.clear();a.aa.moveTo(a.yb+a.Lb*Math.cos(mc(0)),a.zb+a.Nb*Math.sin(mc(0)));a.aa.arcTo(a.Lb,a.Nb,0,360);a.aa.close()}Rc.prototype.mb=function(a,c){this.yb=a;this.zb=c;Sc(this);this.Ib.$a(this.aa)};Rc.prototype.C=function(a){this.Ib.C(a)};function Uc(a,c,d,e,f,g,j,m){w.call(this,a,c,j,m);this.za=d;this.Aa=e;this.Na=f;this.Ia=g}s(Uc,tc);Uc.prototype.ra=!1;
Uc.prototype.C=function(a){this.ra=!0;a.beginPath();a.moveTo(this.za,this.Aa);a.lineTo(this.za,this.Aa+this.Ia);a.lineTo(this.za+this.Na,this.Aa+this.Ia);a.lineTo(this.za+this.Na,this.Aa);a.closePath()};function Tc(a,c,d,e,f){w.call(this,a,c,e,f);this.$a(d)}s(Tc,sc);Tc.prototype.ra=!1;Tc.prototype.$a=function(a){this.aa=a.ya?a:Nc(a);this.ra&&Pc(this.D)};
Tc.prototype.C=function(a){this.ra=!0;a.beginPath();Lc(this.aa,function(c,d){switch(c){case 0:a.moveTo(d[0],d[1]);break;case 1:for(var e=0;e<d.length;e+=2)a.lineTo(d[e],d[e+1]);break;case 2:for(e=0;e<d.length;e+=6)a.bezierCurveTo(d[e],d[e+1],d[e+2],d[e+3],d[e+4],d[e+5]);break;case 3:b(Error("Canvas paths cannot contain arcs"));case 4:a.closePath()}})};function Vc(a,c,d,e,f,g,j){v.call(this,a,c);this.za=d;this.Aa=e;this.Na=f;this.Ia=g;this.ec=j}s(Vc,rc);Vc.prototype.ra=!1;
Vc.prototype.C=function(a){this.Eb?(this.Na&&this.Ia&&a.drawImage(this.Eb,this.za,this.Aa,this.Na,this.Ia),this.ra=!0):(a=new Image,a.onload=na(this.Ub,this,a),a.src=this.ec)};Vc.prototype.Ub=function(a){this.Eb=a;Pc(this.D)};function Wc(a,c,d){c instanceof cc?(d=c.height,c=c.width):d==h&&b(Error("missing height argument"));a.style.width=Xc(c);a.style.height=Xc(d)}function Xc(a){typeof a=="number"&&(a=Math.round(a)+"px");return a}
function Yc(a){var c;a:{c=a.nodeType==9?a:a.ownerDocument||a.document;if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,i))){c=c.display||c.getPropertyValue("display");break a}c=""}if((c||(a.currentStyle?a.currentStyle.display:i)||a.style.display)!="none")return new cc(a.offsetWidth,a.offsetHeight);c=a.style;var d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";var g=a.offsetWidth,a=a.offsetHeight;c.display=d;
c.position=f;c.visibility=e;return new cc(g,a)};function Zc(){}(function(a){a.Db=function(){return a.Yb||(a.Yb=new a)}})(Zc);Zc.prototype.ac=0;Zc.Db();function $c(a){this.K=a||$b||($b=new kc);this.dc=ad}s($c,lc);$c.prototype.Xb=Zc.Db();var ad=i;l=$c.prototype;l.V=i;l.n=!1;l.c=i;l.dc=i;l.$b=i;l.ua=i;l.w=i;l.Ca=i;l.hc=!1;l.a=k("c");l.pb=function(a){this.ua&&this.ua!=a&&b(Error("Method not supported"));$c.k.pb.call(this,a)};l.B=function(){this.c=this.K.createElement("div")};l.U=function(){this.n=!0;bd(this,function(a){!a.n&&a.a()&&a.U()})};l.Ga=function(){bd(this,function(a){a.n&&a.Ga()});this.Ra&&Zb(this.Ra);this.n=!1};
l.h=function(){$c.k.h.call(this);this.n&&this.Ga();this.Ra&&(this.Ra.ca(),delete this.Ra);bd(this,function(a){a.ca()});!this.hc&&this.c&&jc(this.c);this.ua=this.$b=this.c=this.Ca=this.w=i};function bd(a,c){a.w&&Qa(a.w,c,h)}
l.removeChild=function(a,c){if(a){var d=q(a)?a:a.V||(a.V=":"+(a.Xb.ac++).toString(36)),a=this.Ca&&d?(d in this.Ca?this.Ca[d]:h)||i:i;if(d&&a){var e=this.Ca;d in e&&delete e[d];d=this.w;e=Pa(d,a);e>=0&&Oa.splice.call(d,e,1);c&&(a.Ga(),a.c&&jc(a.c));d=a;d==i&&b(Error("Unable to set parent component"));d.ua=i;$c.k.pb.call(d,i)}}a||b(Error("Child is not in parent component"));return a};function cd(a,c,d,e,f){$c.call(this,f);this.width=a;this.height=c;this.q=d||i;this.qa=e||i}s(cd,$c);cd.prototype.l=i;cd.prototype.T=0;cd.prototype.ba=0;cd.prototype.r=function(){return this.n?Yc(this.a()):fa(this.width)&&fa(this.height)?new cc(this.width,this.height):i};function dd(a){var c=a.r();return c?c.width/(a.q?new cc(a.q,a.qa):a.r()).width:0};function ed(a,c,d,e,f){if(!t&&(!$a||!lb("525")))return!0;if(cb&&f)return fd(a);if(f&&!e)return!1;if(!d&&(c==17||c==18))return!1;if(t&&e&&c==a)return!1;switch(a){case 13:return!0;case 27:return!$a}return fd(a)}
function fd(a){if(a>=48&&a<=57)return!0;if(a>=96&&a<=106)return!0;if(a>=65&&a<=90)return!0;if($a&&a==0)return!0;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}};function gd(a,c){if(a)this.Va&&this.detach(),this.c=a,this.Ua=Mb(this.c,"keypress",this,c),this.jb=Mb(this.c,"keydown",this.Vb,c,this),this.Va=Mb(this.c,"keyup",this.Wb,c,this)}s(gd,lc);l=gd.prototype;l.c=i;l.Ua=i;l.jb=i;l.Va=i;l.Y=-1;l.W=-1;
var hd={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},id={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},jd={61:187,59:186},kd=t||$a&&lb("525");l=gd.prototype;
l.Vb=function(a){if($a&&(this.Y==17&&!a.ctrlKey||this.Y==18&&!a.altKey))this.W=this.Y=-1;kd&&!ed(a.keyCode,this.Y,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):this.W=Za&&a.keyCode in jd?jd[a.keyCode]:a.keyCode};l.Wb=function(){this.W=this.Y=-1};
l.handleEvent=function(a){var c=a.hb,d,e;t&&a.type=="keypress"?(d=this.W,e=d!=13&&d!=27?c.keyCode:0):$a&&a.type=="keypress"?(d=this.W,e=c.charCode>=0&&c.charCode<63232&&fd(d)?c.charCode:0):Ya?(d=this.W,e=fd(d)?c.keyCode:0):(d=c.keyCode||this.W,e=c.charCode||0,cb&&e==63&&!d&&(d=191));var f=d,g=c.keyIdentifier;d?d>=63232&&d in hd?f=hd[d]:d==25&&a.shiftKey&&(f=9):g&&g in id&&(f=id[g]);a=f==this.Y;this.Y=f;c=new ld(f,e,a,c);try{this.dispatchEvent(c)}finally{c.ca()}};l.a=k("c");
l.detach=function(){if(this.Ua)Pb(this.Ua),Pb(this.jb),Pb(this.Va),this.Va=this.jb=this.Ua=i;this.c=i;this.W=this.Y=-1};l.h=function(){gd.k.h.call(this);this.detach()};function ld(a,c,d,e){e&&this.Ja(e,h);this.type="key";this.keyCode=a;this.charCode=c;this.repeat=d}s(ld,ob);function md(){};function nd(a){this.tb=1;this.A=a};function od(a,c){this.Ta=a||1;this.Ma=c||pd;this.bb=na(this.fc,this);this.kb=oa()}s(od,lc);od.prototype.enabled=!1;var pd=n.window;l=od.prototype;l.ha=i;l.fc=function(){if(this.enabled){var a=oa()-this.kb;if(a>0&&a<this.Ta*0.8)this.ha=this.Ma.setTimeout(this.bb,this.Ta-a);else if(this.dispatchEvent(qd),this.enabled)this.ha=this.Ma.setTimeout(this.bb,this.Ta),this.kb=oa()}};l.start=function(){this.enabled=!0;if(!this.ha)this.ha=this.Ma.setTimeout(this.bb,this.Ta),this.kb=oa()};
l.stop=function(){this.enabled=!1;if(this.ha)this.Ma.clearTimeout(this.ha),this.ha=i};l.h=function(){od.k.h.call(this);this.stop();delete this.Ma};var qd="tick";function rd(a,c,d){ga(a)?d&&(a=na(a,d)):a&&typeof a.handleEvent=="function"?a=na(a.handleEvent,a):b(Error("Invalid listener argument"));return c>2147483647?-1:pd.setTimeout(a,c||0)};function sd(a,c){this.A=a;this.Ka=c||1}s(sd,md);function td(a,c,d,e,f){cd.call(this,a,c,d,e,f);this.fa=new Ub(this)}s(td,cd);var Ic=document.documentMode&&document.documentMode>=8;function ud(a){return Math.round((parseFloat(a.toString())-0.5)*100)}function y(a){return Math.round(parseFloat(a.toString())*100)}function vd(a,c){var d=a.K.createElement("g_vml_:"+c);d.id="goog_"+Da++;return d}function wd(a){if(Ic&&a.n)a.a().innerHTML=a.a().innerHTML}td.prototype.o=function(a,c){(c||this.l).a().appendChild(a.a());wd(this)};
td.prototype.Za=function(a,c){var d=a.a();d.fillcolor="";for(var e=0;e<d.childNodes.length;e++){var f=d.childNodes[e];f.tagName=="fill"&&d.removeChild(f)}c instanceof sd?c.A=="transparent"?d.filled=!1:c.Ka!=1?(d.filled=!0,e=vd(this,"fill"),e.opacity=Math.round(c.Ka*100)+"%",e.color=c.A,d.appendChild(e)):(d.filled=!0,d.fillcolor=c.A):d.filled=!1;wd(this)};
td.prototype.nb=function(a,c){var d=a.a();if(c){d.stroked=!0;var e=c.tb;q(e)&&e.indexOf("px")==-1?e=parseFloat(e):e*=dd(this);var f=d.getElementsByTagName("stroke")[0];e<1?(f=f||vd(this,"stroke"),f.opacity=e,f.qc="1px",f.color=c.A,d.appendChild(f)):(f&&d.removeChild(f),d.strokecolor=c.A,d.strokeweight=e+"px")}else d.stroked=!1;wd(this)};td.prototype.ob=function(a,c,d,e,f,g){a=a.a();a.style.left=ud(c)+"px";a.style.top=ud(d)+"px";if(e||a.rotation)a.rotation=e,a.coordsize=y(f*2)+" "+y(g*2)};
function Ec(a,c,d,e,f){var g=a.style;g.position="absolute";g.left=ud(c)+"px";g.top=ud(d)+"px";g.width=y(e)+"px";g.height=y(f)+"px";if(a.tagName=="shape")a.coordsize=y(e)+" "+y(f)}try{eval("document.namespaces")}catch(xd){}l=td.prototype;
l.B=function(){var a=this.K.da;if(!a.namespaces.g_vml_)Ic?a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML"):a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml"),a.createStyleSheet().cssText="g_vml_\\:*{behavior:url(#default#VML)}";var a=this.width,c=this.height,d=this.K.B("div",{style:"overflow:hidden;position:relative;width:"+(q(a)&&pa(a)?a:parseFloat(a.toString())+"px")+";height:"+(q(c)&&pa(c)?c:parseFloat(c.toString())+"px")});this.c=d;var e=vd(this,"group"),f=e.style;
f.position="absolute";f.left=f.top=0;f.width=this.width;f.height=this.height;e.coordsize=this.q?y(this.q)+" "+y(this.qa):y(a)+" "+y(c);e.coordorigin=this.T!==h?y(this.T)+" "+y(this.ba):"0 0";d.appendChild(e);this.l=new Cc(e,this);Mb(d,"resize",na(this.ib,this))};
l.ib=function(){var a=Yc(this.a()),c=this.l.a().style;if(a.width)c.width=a.width+"px",c.height=a.height+"px";else{for(a=this.a();a&&a.currentStyle&&a.currentStyle.display!="none";)a=a.parentNode;a&&a.currentStyle&&Xb(this.fa,a,"propertychange",this.ib)}this.dispatchEvent("resize")};l.r=function(){var a=this.a();return new cc(a.style.pixelWidth||a.offsetWidth||1,a.style.pixelHeight||a.offsetHeight||1)};l.clear=function(){this.l.clear()};
l.Fa=function(a,c,d,e,f,g,j){var m=vd(this,"oval");Ec(m,a-d,c-e,d*2,e*2);a=new Dc(m,this,a,c,d,e,f,g);this.o(a,j);return a};l.gb=function(a,c,d,e,f,g,j){var m=vd(this,"rect");Ec(m,a,c,d,e);a=new Fc(m,this,f,g);this.o(a,j);return a};l.drawImage=function(a,c,d,e,f,g){var j=vd(this,"image");Ec(j,a,c,d,e);Ic?j.src=f:j.setAttribute("src",f);a=new Jc(j,this);this.o(a,g);return a};
l.i=function(a,c,d,e){var f=vd(this,"shape"),g=this.q?new cc(this.q,this.qa):this.r();Ec(f,0,0,g.width,g.height);a=Hc(a);Ic?f.path=a:f.setAttribute("path",a);c=new Gc(f,this,c,d);this.o(c,e);return c};
function Hc(a){var c=[];Lc(a,function(a,e){switch(a){case 0:c.push("m");Array.prototype.push.apply(c,Ra(e,y));break;case 1:c.push("l");Array.prototype.push.apply(c,Ra(e,y));break;case 2:c.push("c");Array.prototype.push.apply(c,Ra(e,y));break;case 4:c.push("x");break;case 3:var f=e[2]+e[3];c.push("ae",y(e[4]-e[0]*Math.cos(mc(f))),y(e[5]-e[1]*Math.sin(mc(f))),y(e[0]),y(e[1]),Math.round(e[2]*-65536),Math.round(e[3]*-65536))}});return c.join(" ")}l.U=function(){td.k.U.call(this);this.ib();wd(this)};
l.h=function(){this.l=i;td.k.h.call(this)};function yd(a,c,d,e,f){cd.call(this,a,c,d,e,f)}s(yd,cd);l=yd.prototype;l.Za=function(){Pc(this)};l.nb=function(){Pc(this)};l.ob=function(){Pc(this)};function zd(a,c){var d=a.getContext();d.save();var e=c.rb?c.rb.Qa():new nc,f=e.Z,g=e.$;(f||g)&&d.translate(f,g);(e=e.F)&&d.rotate(Math.asin(e))}l.B=function(){var a=this.K.B("div",{style:"position:relative;overflow:hidden"});this.c=a;this.Ba=this.K.B("canvas");a.appendChild(this.Ba);this.Zb=this.l=new Oc(this);this.cc=0;Ad(this)};
l.getContext=function(){this.a()||this.B();if(!this.pa)this.pa=this.Ba.getContext("2d"),this.pa.save();return this.pa};l.r=function(){var a=this.width,c=this.height,d=q(a)&&a.indexOf("%")!=-1,e=q(c)&&c.indexOf("%")!=-1;if(!this.n&&(d||e))return i;var f,g;if(d)f=this.a().parentNode,g=Yc(f),a=parseFloat(a)*g.width/100;e&&(f=f||this.a().parentNode,g=g||Yc(f),c=parseFloat(c)*g.height/100);return new cc(a,c)};
function Ad(a){Wc(a.a(),a.width,a.height);var c=a.r();if(c)Wc(a.Ba,c.width,c.height),a.Ba.width=c.width,a.Ba.height=c.height,a.pa=i}l.reset=function(){var a=this.getContext();a.restore();var c=this.r();c.width&&c.height&&a.clearRect(0,0,c.width,c.height);a.save()};l.clear=function(){this.reset();this.l.clear();for(var a=this.a();a.childNodes.length>1;)a.removeChild(a.lastChild)};
function Pc(a){if(a.pc)a.oc=!0;else if(a.n){a.reset();if(a.q){var c=a.r();a.getContext().scale(c.width/a.q,c.height/a.qa)}(a.T||a.ba)&&a.getContext().translate(-a.T,-a.ba);zd(a,a.l);a.l.C(a.pa);a.getContext().restore()}}
function Qc(a,c){var d=a.getContext();zd(a,c);if(!c.Sb||!c.Tb)c.C(d);else{var e=c.fill;if(e)if(e instanceof sd){if(e.Ka!=0)d.globalAlpha=e.Ka,d.fillStyle=e.A,c.C(d),d.fill(),d.globalAlpha=1}else{var f=d.createLinearGradient(e.kc(),e.mc(),e.lc(),e.nc());f.addColorStop(0,e.ic());f.addColorStop(1,e.jc());d.fillStyle=f;c.C(d);d.fill()}if(e=c.qb)c.C(d),d.strokeStyle=e.A,e=e.tb,q(e)&&e.indexOf("px")!=-1&&(e=parseFloat(e)/dd(a)),d.lineWidth=e,d.stroke()}a.getContext().restore()}
l.o=function(a,c){c=c||this.l;c.appendChild(a);this.n&&!this.cc&&!(c!=this.l&&c!=this.Zb)&&Qc(this,a)};l.Fa=function(a,c,d,e,f,g,j){a=new Rc(i,this,a,c,d,e,f,g);this.o(a,j);return a};l.gb=function(a,c,d,e,f,g,j){a=new Uc(i,this,a,c,d,e,f,g);this.o(a,j);return a};l.drawImage=function(a,c,d,e,f,g){a=new Vc(i,this,a,c,d,e,f);this.o(a,g);return a};l.i=function(a,c,d,e){a=new Tc(i,this,a,c,d);this.o(a,e);return a};l.h=function(){this.pa=i;yd.k.h.call(this)};
l.U=function(){var a=this.r();yd.k.U.call(this);a||(Ad(this),this.dispatchEvent("resize"));Pc(this)};function Bd(a,c,d,e,f){cd.call(this,a,c,d,e,f);this.Ab={};this.sb=$a&&!lb(526);this.fa=new Ub(this)}var Cd;s(Bd,cd);function Dd(a,c,d){a=a.K.da.createElementNS("http://www.w3.org/2000/svg",c);d&&wc(a,d);return a}function wc(a,c){for(var d in c)a.setAttribute(d,c[d])}l=Bd.prototype;l.o=function(a,c){(c||this.l).a().appendChild(a.a())};l.Za=function(a,c){var d=a.a();c instanceof sd?(d.setAttribute("fill",c.A),d.setAttribute("fill-opacity",c.Ka)):d.setAttribute("fill","none")};
l.nb=function(a,c){var d=a.a();if(c){d.setAttribute("stroke",c.A);var e=c.tb;q(e)&&e.indexOf("px")!=-1?d.setAttribute("stroke-width",parseFloat(e)/dd(this)):d.setAttribute("stroke-width",e)}else d.setAttribute("stroke","none")};l.ob=function(a,c,d,e,f,g){a.a().setAttribute("transform","translate("+c+","+d+") rotate("+e+" "+f+" "+g+")")};
l.B=function(){var a=Dd(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),c=Dd(this,"g");this.fb=Dd(this,"defs");this.l=new uc(c,this);a.appendChild(this.fb);a.appendChild(c);this.c=a;if(this.q||this.T||this.ba)this.a().setAttribute("preserveAspectRatio","none"),this.sb?this.ab():this.a().setAttribute("viewBox",this.T+" "+this.ba+" "+(this.q?this.q+" "+this.qa:""))};
l.ab=function(){if(this.n&&(this.q||this.T||!this.ba)){var a=this.r();if(a.width==0)this.a().style.visibility="hidden";else{this.a().style.visibility="";var c=-this.T,d=-this.ba,e=a.width/this.q,a=a.height/this.qa;this.l.a().setAttribute("transform","scale("+e+" "+a+") translate("+c+" "+d+")")}}};
l.r=function(){if(!Za)return this.n?Yc(this.a()):Bd.k.r.call(this);var a=this.width,c=this.height,d=q(a)&&a.indexOf("%")!=-1,e=q(c)&&c.indexOf("%")!=-1;if(!this.n&&(d||e))return i;var f,g;if(d)f=this.a().parentNode,g=Yc(f),a=parseFloat(a)*g.width/100;e&&(f=f||this.a().parentNode,g=g||Yc(f),c=parseFloat(c)*g.height/100);return new cc(a,c)};l.clear=function(){this.l.clear();ic(this.fb);this.Ab={}};
l.Fa=function(a,c,d,e,f,g,j){a=Dd(this,"ellipse",{cx:a,cy:c,rx:d,ry:e});f=new vc(a,this,f,g);this.o(f,j);return f};l.gb=function(a,c,d,e,f,g,j){a=Dd(this,"rect",{x:a,y:c,width:d,height:e});f=new xc(a,this,f,g);this.o(f,j);return f};l.drawImage=function(a,c,d,e,f,g){a=Dd(this,"image",{x:a,y:c,width:d,height:e,"image-rendering":"optimizeQuality",preserveAspectRatio:"none"});a.setAttributeNS("http://www.w3.org/1999/xlink","href",f);f=new Ac(a,this);this.o(f,g);return f};
l.i=function(a,c,d,e){a=Dd(this,"path",{d:zc(a)});c=new yc(a,this,c,d);this.o(c,e);return c};function zc(a){var c=[];Lc(a,function(a,e){switch(a){case 0:c.push("M");Array.prototype.push.apply(c,e);break;case 1:c.push("L");Array.prototype.push.apply(c,e);break;case 2:c.push("C");Array.prototype.push.apply(c,e);break;case 3:var f=e[3];c.push("A",e[0],e[1],0,Math.abs(f)>180?1:0,f>0?1:0,e[4],e[5]);break;case 4:c.push("Z")}});return c.join(" ")}
l.U=function(){var a=this.r();Bd.k.U.call(this);a||this.dispatchEvent("resize");if(this.sb){var a=this.width,c=this.height;typeof a=="string"&&a.indexOf("%")!=-1&&typeof c=="string"&&c.indexOf("%")!=-1&&Xb(this.fa,Ed(),qd,this.ab);this.ab()}};l.Ga=function(){Bd.k.Ga.call(this);this.sb&&Yb(this.fa,Ed(),qd,this.ab)};l.h=function(){delete this.Ab;delete this.fb;delete this.l;Bd.k.h.call(this)};function Ed(){Cd||(Cd=new od(400),Cd.start());return Cd};function Fd(a,c,d,e,f){a=t&&!lb("9")?new td(a,c,d,e,f):$a&&(!lb("420")||ab)?new yd(a,c,d,e,f):new Bd(a,c,d,e,f);a.B();return a};function z(a){return a!=i&&a!==!1}function Gd(a,c){var d=a[p.call(i,c)];return z(d)?d:(d=a._,z(d)?d:!1)}function Hd(a){return Array.prototype.slice.call(a)}function Id(a){return Array.prototype.slice.call(arguments)}
var Kd=function Jd(c){return z(z(c)?c.ja:c)?c.ja(c):function(){var d=Jd[p.call(i,c)];return z(d)?d:Jd._}().call(i,c)},Md=function Ld(c,d){return z(z(c)?c.O:c)?c.O(c,d):function(){var d=Ld[p.call(i,c)];return z(d)?d:Ld._}().call(i,c,d)},B=function(){function a(a,c,g){return z(z(a)?a.Pa:a)?a.Pa(a,c,g):function(){var c=d[p.call(i,a)];return z(c)?c:d._}().call(i,a,c,g)}function c(a,c){return z(z(a)?a.Pa:a)?a.Pa(a,c):function(){var c=d[p.call(i,a)];return z(c)?c:d._}().call(i,a,c)}var d=i;return d=function(d,
f,g){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return a.call(this,d,f,g)}b("Invalid arity: "+arguments.length)}}(),Nd={},Pd=function Od(c){return z(z(c)?c.la:c)?c.la(c):function(){var d=Od[p.call(i,c)];return z(d)?d:Od._}().call(i,c)},Rd=function Qd(c){return z(z(c)?c.ma:c)?c.ma(c):function(){var d=Qd[p.call(i,c)];return z(d)?d:Qd._}().call(i,c)},C=function(){function a(a,c,g){return z(z(a)?a.ka:a)?a.ka(a,c,g):function(){var c=d[p.call(i,a)];return z(c)?c:d._}().call(i,a,c,g)}
function c(a,c){return z(z(a)?a.ka:a)?a.ka(a,c):function(){var c=d[p.call(i,a)];return z(c)?c:d._}().call(i,a,c)}var d=i;return d=function(d,f,g){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return a.call(this,d,f,g)}b("Invalid arity: "+arguments.length)}}(),Td=function Sd(c,d,e){return z(z(c)?c.Oa:c)?c.Oa(c,d,e):function(){var d=Sd[p.call(i,c)];return z(d)?d:Sd._}().call(i,c,d,e)},Ud={},Vd={},Xd=function Wd(c){return z(z(c)?c.Ob:c)?c.state:function(){var d=Wd[p.call(i,c)];return z(d)?
d:Wd._}().call(i,c)},Yd={},$d=function Zd(c){return z(z(c)?c.R:c)?c.e:function(){var d=Zd[p.call(i,c)];return z(d)?d:Zd._}().call(i,c)},be=function ae(c,d){return z(z(c)?c.S:c)?c.S(c,d):function(){var d=ae[p.call(i,c)];return z(d)?d:ae._}().call(i,c,d)},ce=function(){function a(a,c,g){return z(z(a)?a.Da:a)?a.Da(a,c,g):function(){var c=d[p.call(i,a)];return z(c)?c:d._}().call(i,a,c,g)}function c(a,c){return z(z(a)?a.Da:a)?a.Da(a,c):function(){var c=d[p.call(i,a)];return z(c)?c:d._}().call(i,a,c)}var d=
i;return d=function(d,f,g){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return a.call(this,d,f,g)}b("Invalid arity: "+arguments.length)}}(),ee=function de(c,d){return z(z(c)?c.s:c)?c.s(c,d):function(){var d=de[p.call(i,c)];return z(d)?d:de._}().call(i,c,d)},ge=function fe(c){return z(z(c)?c.P:c)?c.P(c):function(){var d=fe[p.call(i,c)];return z(d)?d:fe._}().call(i,c)},ie=function he(c){return z(z(c)?c.I:c)?c.I(c):function(){var d=he[p.call(i,c)];return z(d)?d:he._}().call(i,c)},je=
{},ke={},me=function le(c,d){return z(z(c)?c.z:c)?c.z(c,d):function(){var d=le[p.call(i,c)];return z(d)?d:le._}().call(i,c,d)};function ne(a,c){return a===c}function D(a,c){return ee.call(i,a,c)}function E(a){return ne.call(i,a,i)}ee["null"]=function(a,c){return E.call(i,c)};Md["null"]=function(a,c){return oe.call(i,c)};Nd["null"]=!0;Pd["null"]=ba(i);Rd["null"]=function(){return oe.call(i)};be["null"]=ba(i);Ud["null"]=!0;
B["null"]=function(){return function(a,c,d){switch(arguments.length){case 2:return i;case 3:return d}b("Invalid arity: "+arguments.length)}}();Yd["null"]=!0;$d["null"]=ba(i);ce["null"]=function(){return function(a,c,d){switch(arguments.length){case 2:return c.call(i);case 3:return d}b("Invalid arity: "+arguments.length)}}();ge["null"]=ba(0);Kd["null"]=ba(0);Td["null"]=function(a,c,d){return pe.call(i,c,d)};
C["null"]=function(){return function(a,c,d){switch(arguments.length){case 2:return i;case 3:return d}b("Invalid arity: "+arguments.length)}}();Date.prototype.s=function(a,c){return ne.call(i,a.toString,c.toString)};ge.number=aa();ee.number=function(a,c){return ne.call(i,a,c)};function F(a){return a+1}function qe(a,c){return a<c}
var re=function(){return function(a,c,d,e){switch(arguments.length){case 2:var f;a:if(z(D.call(i,0,Kd.call(i,a))))f=c.call(i);else for(var g=B.call(i,a,0),j=1;;)if(z(qe.call(i,j,Kd.call(i,a))))g=c.call(i,g,B.call(i,a,j)),j=F.call(i,j);else{f=g;break a}return f;case 3:a:{f=d;for(j=0;;)if(z(qe.call(i,j,Kd.call(i,a))))f=c.call(i,f,B.call(i,a,j)),j=F.call(i,j);else{g=f;break a}}return g;case 4:a:{f=d;for(g=e;;)if(z(qe.call(i,g,Kd.call(i,a))))f=c.call(i,f,B.call(i,a,g)),g=F.call(i,g);else{j=f;break a}}return j}b("Invalid arity: "+
arguments.length)}}();function se(a,c){this.ia=a;this.sa=c}l=se.prototype;l.Da=function(){return function(a,c,d){switch(arguments.length){case 2:return re.call(i,this.ia,c,this.ia[this.sa],F.call(i,this.sa));case 3:return re.call(i,this.ia,c,d,this.sa)}b("Invalid arity: "+arguments.length)}}();l.s=function(a,c){return te.call(i,a,c)};l.na=!0;l.Ea=!0;l.la=function(){return this.ia[this.sa]};
l.ma=function(){return z(qe.call(i,F.call(i,this.sa),Kd.call(i,this.ia)))?new se(this.ia,F.call(i,this.sa)):oe.call(i)};l.I=aa();function ue(a,c){return z(D.call(i,0,Kd.call(i,a)))?i:new se(a,c)}function H(a,c){return ue.call(i,a,c)}ce.array=function(){return function(a,c,d){switch(arguments.length){case 2:return re.call(i,a,c);case 3:return re.call(i,a,c,d)}b("Invalid arity: "+arguments.length)}}();
C.array=function(){return function(a,c,d){switch(arguments.length){case 2:return a[c];case 3:return B.call(i,a,c,d)}b("Invalid arity: "+arguments.length)}}();B.array=function(){return function(a,c,d){switch(arguments.length){case 2:return z(qe.call(i,c,a.length))?a[c]:i;case 3:return z(qe.call(i,c,a.length))?a[c]:d}b("Invalid arity: "+arguments.length)}}();Kd.array=function(a){return a.length};ie.array=function(a){return H.call(i,a,0)};function I(a){return z(a)?ie.call(i,a):i}
function J(a){a=I.call(i,a);return z(a)?Pd.call(i,a):i}function K(a){return Rd.call(i,I.call(i,a))}function L(a){return z(a)?I.call(i,K.call(i,a)):i}function ve(a){return J.call(i,L.call(i,a))}function we(a){return L.call(i,L.call(i,a))}Kd._=function(a){for(var a=I.call(i,a),c=0;;)if(z(a))a=L.call(i,a),c=F.call(i,c);else return c};ee._=function(a,c){return ne.call(i,a,c)};function xe(a){return z(a)?!1:!0}
var ye=function(){function a(a,e,f){for(var g=H(Array.prototype.slice.call(arguments,2),0);;)if(z(g))var j=c.call(i,a,e),m=J.call(i,g),g=L.call(i,g),a=j,e=m;else return c.call(i,a,e)}var c=i,c=function(c,e,f){switch(arguments.length){case 2:return Md.call(i,c,e);default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=2;c.b=function(c){var e=J(c),f=J(L(c)),c=K(L(c));return a.call(i,e,f,c)};return c}();function ze(a){return Kd.call(i,a)}
var M=function(){return function(a,c,d){switch(arguments.length){case 2:return B.call(i,a,c);case 3:return B.call(i,a,c,d)}b("Invalid arity: "+arguments.length)}}(),Ae=function(){return function(a,c,d){switch(arguments.length){case 2:return C.call(i,a,c);case 3:return C.call(i,a,c,d)}b("Invalid arity: "+arguments.length)}}(),Be=function(){function a(a,e,f,g){for(var j=H(Array.prototype.slice.call(arguments,3),0);;){var m=c.call(i,a,e,f);if(z(j))var o=J.call(i,j),r=ve.call(i,j),j=we.call(i,j),a=m,
e=o,f=r;else return m}}var c=i,c=function(c,e,f,g){switch(arguments.length){case 3:return Td.call(i,c,e,f);default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=3;c.b=function(c){var e=J(c),f=J(L(c)),g=J(L(L(c))),c=K(L(L(c)));return a.call(i,e,f,g,c)};return c}();function Ce(a,c){return be.call(i,a,c)}function De(a){return $d.call(i,a)}function Ee(a){return ge.call(i,a)}function Fe(a){return z(z(a)?a.na:a)?!0:Gd.call(i,je,a)}
function Ge(a){return z(E.call(i,a))?!1:z(z(a)?a.wb:a)?!0:Gd.call(i,Ud,a)}function He(a){return z(z(a)?a.Pb:a)?!0:Gd.call(i,Vd,a)}function Ie(){return{}}function Je(a){var c=Id.call(i);Fb.call(i,a,function(a,e){return c.push(e)});return c}var Ke=Ie.call(i);function Le(a){return h===a}function Me(a){return z(E.call(i,a))?!1:z(z(a)?a.Ea:a)?!0:Gd.call(i,Nd,a)}function Ne(a){return z(a)?!0:!1}
function Oe(a){var c=q.call(i,a);return z(c)?xe.call(i,function(){var c=D.call(i,a.charAt(0),"\ufdd0");return z(c)?c:D.call(i,a.charAt(0),"\ufdd1")}()):c}function Pe(a){var c=q.call(i,a);return z(c)?D.call(i,a.charAt(0),"\ufdd0"):c}function Qe(a){var c=q.call(i,a);return z(c)?D.call(i,a.charAt(0),"\ufdd1"):c}function Re(a){return fa.call(i,a)}function Se(a){var c=Re.call(i,a);return z(c)?a==a.toFixed():c}function Te(a,c){return z(ne.call(i,C.call(i,a,c,Ke),Ke))?!1:!0}
var Ue=function(){return function(a,c,d){switch(arguments.length){case 2:return ce.call(i,c,a);case 3:return ce.call(i,d,a,c)}b("Invalid arity: "+arguments.length)}}(),Ve=function(){return function(a,c,d){switch(arguments.length){case 2:var e=I.call(i,c);return z(e)?Ue.call(i,a,J.call(i,e),L.call(i,e)):a.call(i);case 3:a:for(var f=c,g=I.call(i,d);;)if(z(g))f=a.call(i,f,J.call(i,g)),g=L.call(i,g);else{e=f;break a}return e}b("Invalid arity: "+arguments.length)}}();
ce._=function(){return function(a,c,d){switch(arguments.length){case 2:return Ve.call(i,c,a);case 3:return Ve.call(i,c,d,a)}b("Invalid arity: "+arguments.length)}}();
var N=function(){function a(a,e,f){var g=H(Array.prototype.slice.call(arguments,2),0);return Ue.call(i,c,c.call(i,a,e),g)}var c=i,c=function(c,e,f){switch(arguments.length){case 0:return 0;case 1:return c;case 2:return c+e;default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=2;c.b=function(c){var e=J(c),f=J(L(c)),c=K(L(c));return a.call(i,e,f,c)};return c}(),O=function(){function a(a,e,f){var g=H(Array.prototype.slice.call(arguments,2),0);return Ue.call(i,c,c.call(i,a,
e),g)}var c=i,c=function(c,e,f){switch(arguments.length){case 1:return-c;case 2:return c-e;default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=2;c.b=function(c){var e=J(c),f=J(L(c)),c=K(L(c));return a.call(i,e,f,c)};return c}(),We=function(){function a(a,e,f){var g=H(Array.prototype.slice.call(arguments,2),0);return Ue.call(i,c,c.call(i,a,e),g)}var c=i,c=function(c,e,f){switch(arguments.length){case 0:return 1;case 1:return c;case 2:return c*e;default:return a.apply(this,
arguments)}b("Invalid arity: "+arguments.length)};c.f=2;c.b=function(c){var e=J(c),f=J(L(c)),c=K(L(c));return a.call(i,e,f,c)};return c}(),Xe=function(){function a(a,e,f){var g=H(Array.prototype.slice.call(arguments,2),0);return Ue.call(i,c,c.call(i,a,e),g)}var c=i,c=function(c,e,f){switch(arguments.length){case 1:return 1/c;case 2:return c/e;default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=2;c.b=function(c){var e=J(c),f=J(L(c)),c=K(L(c));return a.call(i,e,f,c)};return c}(),
Ye=function(){function a(a,e,f){for(var g=H(Array.prototype.slice.call(arguments,2),0);;)if(z(c.call(i,a,e)))if(z(L.call(i,g)))var j=e,m=J.call(i,g),g=L.call(i,g),a=j,e=m;else return c.call(i,e,J.call(i,g));else return!1}var c=i,c=function(c,e,f){switch(arguments.length){case 1:return!0;case 2:return c<e;default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=2;c.b=function(c){var e=J(c),f=J(L(c)),c=K(L(c));return a.call(i,e,f,c)};return c}(),Ze=function(){function a(a,e,
f){for(var g=H(Array.prototype.slice.call(arguments,2),0);;)if(z(c.call(i,a,e)))if(z(L.call(i,g)))var j=e,m=J.call(i,g),g=L.call(i,g),a=j,e=m;else return c.call(i,e,J.call(i,g));else return!1}var c=i,c=function(c,e,f){switch(arguments.length){case 1:return!0;case 2:return c<=e;default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=2;c.b=function(c){var e=J(c),f=J(L(c)),c=K(L(c));return a.call(i,e,f,c)};return c}(),$e=function(){function a(a,e,f){for(var g=H(Array.prototype.slice.call(arguments,
2),0);;)if(z(c.call(i,a,e)))if(z(L.call(i,g)))var j=e,m=J.call(i,g),g=L.call(i,g),a=j,e=m;else return c.call(i,e,J.call(i,g));else return!1}var c=i,c=function(c,e,f){switch(arguments.length){case 1:return!0;case 2:return c>e;default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=2;c.b=function(c){var e=J(c),f=J(L(c)),c=K(L(c));return a.call(i,e,f,c)};return c}();function af(a){return O.call(i,a,1)}function bf(a,c){return a%c}function cf(a,c){return a^c}
function df(a,c){return a&c}function ef(a,c){return a<<c}function ff(a,c){return a>>c}
var gf=function(){function a(a,e,f){for(var g=H(Array.prototype.slice.call(arguments,2),0);;)if(z(c.call(i,a,e)))if(z(L.call(i,g)))var j=e,m=J.call(i,g),g=L.call(i,g),a=j,e=m;else return c.call(i,e,J.call(i,g));else return!1}var c=i,c=function(c,e,f){switch(arguments.length){case 1:return!0;case 2:return ee.call(i,c,e);default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=2;c.b=function(c){var e=J(c),f=J(L(c)),c=K(L(c));return a.call(i,e,f,c)};return c}();
function hf(a){return Ye.call(i,0,a)}function jf(a){return gf.call(i,0,a)}function kf(a,c){for(var d=c,e=I.call(i,a);;)if(z(function(){var a=e;return z(a)?hf.call(i,d):a}()))var f=af.call(i,d),g=L.call(i,e),d=f,e=g;else return e}B._=function(){return function(a,c,d){switch(arguments.length){case 2:var e;var f=kf.call(i,a,c);z(f)?e=J.call(i,f):b("Index out of bounds");return e;case 3:return e=kf.call(i,a,c),z(e)?J.call(i,e):d}b("Invalid arity: "+arguments.length)}}();
var lf=function(){function a(a,e){var f=H(Array.prototype.slice.call(arguments,1),0);return function(a,d){for(;;)if(z(d))var e=a.append(c.call(i,J.call(i,d))),f=L.call(i,d),a=e,d=f;else return c.call(i,a)}.call(i,new La(c.call(i,a)),f)}var c=i,c=function(c,e){switch(arguments.length){case 0:return"";case 1:return z(E.call(i,c))?"":c.toString();default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=1;c.b=function(c){var e=J(c),c=K(c);return a.call(i,e,c)};return c}(),mf=
function(){return function(a,c,d){switch(arguments.length){case 2:return a.substring(c);case 3:return a.substring(c,d)}b("Invalid arity: "+arguments.length)}}();function te(a,c){return Ne.call(i,z(Fe.call(i,c))?function(){for(var d=I.call(i,a),e=I.call(i,c);;)if(z(E.call(i,d)))return E.call(i,e);else if(z(E.call(i,e)))return!1;else if(z(D.call(i,J.call(i,d),J.call(i,e))))d=L.call(i,d),e=L.call(i,e);else return z("\ufdd0'else")?!1:i}():i)}
function nf(a,c){return cf.call(i,a,N.call(i,c,2654435769,ef.call(i,a,6),ff.call(i,a,2)))}function of(a){return Ue.call(i,function(a,d){return nf.call(i,a,Ee.call(i,d))},Ee.call(i,J.call(i,a)),L.call(i,a))}function pf(a,c,d,e){this.e=a;this.Ha=c;this.xa=d;this.count=e}l=pf.prototype;l.s=function(a,c){return te.call(i,a,c)};l.O=function(a,c){return new pf(this.e,c,a,F.call(i,this.count))};l.Ea=!0;l.la=k("Ha");l.ma=k("xa");l.I=aa();l.S=function(a,c){return new pf(c,this.Ha,this.xa,this.count)};
l.Q=!0;l.R=k("e");l.P=function(a){return of.call(i,a)};l.ja=k("count");l.na=!0;function qf(a){this.e=a}l=qf.prototype;l.s=function(a,c){return te.call(i,a,c)};l.O=function(a,c){return new pf(this.e,c,i,1)};l.Ea=!0;l.la=ba(i);l.ma=ba(i);l.I=ba(i);l.S=function(a,c){return new qf(c)};l.Q=!0;l.R=k("e");l.P=function(a){return of.call(i,a)};l.ja=ba(0);l.na=!0;var rf=new qf(i);function sf(a){return Ue.call(i,ye,rf,a)}
function oe(a){var c=H(Array.prototype.slice.call(arguments,0),0);return Ue.call(i,ye,rf,sf.call(i,c))}function tf(a,c,d){this.e=a;this.Ha=c;this.xa=d}l=tf.prototype;l.I=aa();l.P=function(a){return of.call(i,a)};l.s=function(a,c){return te.call(i,a,c)};l.na=!0;l.O=function(a,c){return new tf(i,c,a)};l.Ea=!0;l.la=k("Ha");l.ma=function(){return z(E.call(i,this.xa))?rf:this.xa};l.Q=!0;l.R=k("e");l.S=function(a,c){return new tf(c,this.Ha,this.xa)};function P(a,c){return new tf(i,a,c)}
ce.string=function(){return function(a,c,d){switch(arguments.length){case 2:return re.call(i,a,c);case 3:return re.call(i,a,c,d)}b("Invalid arity: "+arguments.length)}}();C.string=function(){return function(a,c,d){switch(arguments.length){case 2:return B.call(i,a,c);case 3:return B.call(i,a,c,d)}b("Invalid arity: "+arguments.length)}}();
B.string=function(){return function(a,c,d){switch(arguments.length){case 2:return z(Ye.call(i,c,Kd.call(i,a)))?a.charAt(c):i;case 3:return z(Ye.call(i,c,Kd.call(i,a)))?a.charAt(c):d}b("Invalid arity: "+arguments.length)}}();Kd.string=function(a){return a.length};ie.string=function(a){return ue.call(i,a,0)};ge.string=function(a){return Ca.call(i,a)};
String.prototype.call=function(){return function(a,c,d){switch(arguments.length){case 2:return Ae.call(i,c,this.toString());case 3:return Ae.call(i,c,this.toString(),d)}b("Invalid arity: "+arguments.length)}}();function uf(a){var c=a.x;return z(a.lb)?c:(a.x=c.call(i),a.lb=!0,a.x)}function Q(a,c,d){this.e=a;this.lb=c;this.x=d}l=Q.prototype;l.I=function(a){return I.call(i,uf.call(i,a))};l.P=function(a){return of.call(i,a)};l.s=function(a,c){return te.call(i,a,c)};l.na=!0;
l.O=function(a,c){return P.call(i,c,a)};l.Ea=!0;l.la=function(a){return J.call(i,uf.call(i,a))};l.ma=function(a){return K.call(i,uf.call(i,a))};l.Q=!0;l.R=k("e");l.S=function(a,c){return new Q(c,this.lb,this.x)};function vf(a){for(var c=Id.call(i);;)if(z(I.call(i,a)))c.push(J.call(i,a)),a=L.call(i,a);else return c}function wf(a,c){for(var d=a,e=c,f=0;;)if(z(function(){var a=hf.call(i,e);return z(a)?I.call(i,d):a}()))var g=L.call(i,d),j=af.call(i,e),f=F.call(i,f),d=g,e=j;else return f}
var yf=function xf(c){return z(E.call(i,c))?i:z(E.call(i,L.call(i,c)))?I.call(i,J.call(i,c)):z("\ufdd0'else")?P.call(i,J.call(i,c),xf.call(i,L.call(i,c))):i},zf=function(){function a(a,c,d){var e=H(Array.prototype.slice.call(arguments,2),0);return function A(a,c){return new Q(i,!1,function(){var d=I.call(i,a);return z(d)?P.call(i,J.call(i,d),A.call(i,K.call(i,d),c)):z(c)?A.call(i,J.call(i,c),L.call(i,c)):i})}.call(i,f.call(i,a,c),e)}function c(a,c){return new Q(i,!1,function(){var d=I.call(i,a);return z(d)?
P.call(i,J.call(i,d),f.call(i,K.call(i,d),c)):c})}function d(a){return new Q(i,!1,function(){return a})}function e(){return new Q(i,!1,ba(i))}var f=i,f=function(f,j,m){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,f);case 2:return c.call(this,f,j);default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};f.f=2;f.b=function(c){var d=J(c),e=J(L(c)),c=K(L(c));return a.call(i,d,e,c)};return f}(),Af=function(){function a(a,c,f,g,j){var m=H(Array.prototype.slice.call(arguments,
4),0);return P.call(i,a,P.call(i,c,P.call(i,f,P.call(i,g,yf.call(i,m)))))}var c=i,c=function(c,e,f,g,j){switch(arguments.length){case 1:return I.call(i,c);case 2:return P.call(i,c,e);case 3:return P.call(i,c,P.call(i,e,f));case 4:return P.call(i,c,P.call(i,e,P.call(i,f,g)));default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=4;c.b=function(c){var e=J(c),f=J(L(c)),g=J(L(L(c))),j=J(L(L(L(c)))),c=K(L(L(L(c))));return a.call(i,e,f,g,j,c)};return c}(),Bf=function(){function a(a,
c,f,g,j,m){var o=H(Array.prototype.slice.call(arguments,5),0),o=P.call(i,c,P.call(i,f,P.call(i,g,P.call(i,j,yf.call(i,o))))),r=a.f;return z(a.b)?z(Ze.call(i,wf.call(i,o,r),r))?a.apply(a,vf.call(i,o)):a.b(o):a.apply(a,vf.call(i,o))}var c=i,c=function(c,e,f,g,j,m){switch(arguments.length){case 2:var o=c,r=e,A=o.f;return z(o.b)?z(Ze.call(i,wf.call(i,r,A),A))?o.apply(o,vf.call(i,r)):o.b(r):o.apply(o,vf.call(i,r));case 3:return o=c,r=Af.call(i,e,f),A=o.f,z(o.b)?z(Ze.call(i,wf.call(i,r,A),A))?o.apply(o,
vf.call(i,r)):o.b(r):o.apply(o,vf.call(i,r));case 4:return o=c,r=Af.call(i,e,f,g),A=o.f,z(o.b)?z(Ze.call(i,wf.call(i,r,A),A))?o.apply(o,vf.call(i,r)):o.b(r):o.apply(o,vf.call(i,r));case 5:return o=c,r=Af.call(i,e,f,g,j),A=o.f,z(o.b)?z(Ze.call(i,wf.call(i,r,A),A))?o.apply(o,vf.call(i,r)):o.b(r):o.apply(o,vf.call(i,r));default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=5;c.b=function(c){var e=J(c),f=J(L(c)),g=J(L(L(c))),j=J(L(L(L(c)))),m=J(L(L(L(L(c))))),c=K(L(L(L(L(c)))));
return a.call(i,e,f,g,j,m,c)};return c}(),Cf=function(){function a(a,c,f){var g=H(Array.prototype.slice.call(arguments,2),0);return xe.call(i,Bf.call(i,D,a,c,g))}var c=i,c=function(c,e,f){switch(arguments.length){case 1:return!1;case 2:return xe.call(i,D.call(i,c,e));default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=2;c.b=function(c){var e=J(c),f=J(L(c)),c=K(L(c));return a.call(i,e,f,c)};return c}();
function Df(a,c){for(;;)if(z(E.call(i,I.call(i,c))))return!0;else if(z(a.call(i,J.call(i,c))))var d=a,e=L.call(i,c),a=d,c=e;else return z("\ufdd0'else")?!1:i}function Ef(a){if(z(Se.call(i,a)))return jf.call(i,df.call(i,a,1));else b(lf.call(i,"Argument must be an integer: ",a))}function Ff(a){return a}
function Gf(a){return function(){function c(c,d,g){var j=H(Array.prototype.slice.call(arguments,2),0);return xe.call(i,Bf.call(i,a,c,d,j))}var d=i,d=function(d,f,g){switch(arguments.length){case 0:return xe.call(i,a.call(i));case 1:return xe.call(i,a.call(i,d));case 2:return xe.call(i,a.call(i,d,f));default:return c.apply(this,arguments)}b("Invalid arity: "+arguments.length)};d.f=2;d.b=function(a){var d=J(a),g=J(L(a)),a=K(L(a));return c.call(i,d,g,a)};return d}()}
var Hf=function(){function a(a,c,d,e,r){var A=H(Array.prototype.slice.call(arguments,4),0);return f.call(i,function(c){return Bf.call(i,a,c)},function W(a){return new Q(i,!1,function(){var c=f.call(i,I,a);return z(Df.call(i,Ff,c))?P.call(i,f.call(i,J,c),W.call(i,f.call(i,K,c))):i})}.call(i,ye.call(i,A,e,d,c)))}function c(a,c,d,e){return new Q(i,!1,function(){var r=I.call(i,c),A=I.call(i,d),G=I.call(i,e);return z(z(r)?z(A)?G:A:r)?P.call(i,a.call(i,J.call(i,r),J.call(i,A),J.call(i,G)),f.call(i,a,K.call(i,
r),K.call(i,A),K.call(i,G))):i})}function d(a,c,d){return new Q(i,!1,function(){var e=I.call(i,c),r=I.call(i,d);return z(z(e)?r:e)?P.call(i,a.call(i,J.call(i,e),J.call(i,r)),f.call(i,a,K.call(i,e),K.call(i,r))):i})}function e(a,c){return new Q(i,!1,function(){var d=I.call(i,c);return z(d)?P.call(i,a.call(i,J.call(i,d)),f.call(i,a,K.call(i,d))):i})}var f=i,f=function(f,j,m,o,r){switch(arguments.length){case 2:return e.call(this,f,j);case 3:return d.call(this,f,j,m);case 4:return c.call(this,f,j,m,
o);default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};f.f=4;f.b=function(c){var d=J(c),e=J(L(c)),f=J(L(L(c))),r=J(L(L(L(c)))),c=K(L(L(L(c))));return a.call(i,d,e,f,r,c)};return f}(),Jf=function If(c,d){return new Q(i,!1,function(){if(z(hf.call(i,c))){var e=I.call(i,d);return z(e)?P.call(i,J.call(i,e),If.call(i,af.call(i,c),K.call(i,e))):i}else return i})};
function Kf(a,c){function d(a,c){for(;;){var d=I.call(i,c);if(z(function(){var c=hf.call(i,a);return z(c)?d:c}()))var j=af.call(i,a),m=K.call(i,d),a=j,c=m;else return d}}return new Q(i,!1,function(){return d.call(i,a,c)})}
var Lf=function(){function a(a){return new Q(i,!1,function(){return P.call(i,a,c.call(i,a))})}var c=i;return c=function(d,e){switch(arguments.length){case 1:return a.call(this,d);case 2:return Jf.call(i,d,c.call(i,e))}b("Invalid arity: "+arguments.length)}}(),Mf=function(){function a(a,c,g){var j=H(Array.prototype.slice.call(arguments,2),0);return new Q(i,!1,function(){var g=Hf.call(i,I,ye.call(i,j,c,a));return z(Df.call(i,Ff,g))?zf.call(i,Hf.call(i,J,g),Bf.call(i,d,Hf.call(i,K,g))):i})}function c(a,
c){return new Q(i,!1,function(){var g=I.call(i,a),j=I.call(i,c);return z(z(g)?j:g)?P.call(i,J.call(i,g),P.call(i,J.call(i,j),d.call(i,K.call(i,g),K.call(i,j)))):i})}var d=i,d=function(d,f,g){switch(arguments.length){case 2:return c.call(this,d,f);default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};d.f=2;d.b=function(c){var d=J(c),g=J(L(c)),c=K(L(c));return a.call(i,d,g,c)};return d}();function Nf(a,c){return Kf.call(i,1,Mf.call(i,Lf.call(i,a),c))}
function Of(a){return function d(a,f){return new Q(i,!1,function(){var g=I.call(i,a);return z(g)?P.call(i,J.call(i,g),d.call(i,K.call(i,g),f)):z(I.call(i,f))?d.call(i,J.call(i,f),K.call(i,f)):i})}.call(i,i,a)}
var Pf=function(){function a(a,c,f){var g=H(Array.prototype.slice.call(arguments,2),0);return Of.call(i,Bf.call(i,Hf,a,c,g))}var c=i,c=function(c,e,f){switch(arguments.length){case 2:return Of.call(i,Hf.call(i,c,e));default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=2;c.b=function(c){var e=J(c),f=J(L(c)),c=K(L(c));return a.call(i,e,f,c)};return c}(),Rf=function Qf(c,d){return new Q(i,!1,function(){var e=I.call(i,d);if(z(e)){var f=J.call(i,e),e=K.call(i,e);return z(c.call(i,
f))?P.call(i,f,Qf.call(i,c,e)):Qf.call(i,c,e)}else return i})};function Sf(a,c){return Rf.call(i,Gf.call(i,a),c)}function Tf(a,c){return Ue.call(i,Md,a,c)}
var Uf=function(){function a(a,c,g,j){return new Q(i,!1,function(){var m=I.call(i,j);if(z(m)){var o=Jf.call(i,a,m);return z(D.call(i,a,ze.call(i,o)))?P.call(i,o,d.call(i,a,c,g,Kf.call(i,c,m))):oe.call(i,Jf.call(i,a,zf.call(i,o,g)))}else return i})}function c(a,c,g){return new Q(i,!1,function(){var j=I.call(i,g);if(z(j)){var m=Jf.call(i,a,j);return z(D.call(i,a,ze.call(i,m)))?P.call(i,m,d.call(i,a,c,Kf.call(i,c,j))):i}else return i})}var d=i;return d=function(e,f,g,j){switch(arguments.length){case 2:return d.call(i,
e,e,f);case 3:return c.call(this,e,f,g);case 4:return a.call(this,e,f,g,j)}b("Invalid arity: "+arguments.length)}}(),Vf=function(){return function(a,c,d){switch(arguments.length){case 2:return Ue.call(i,Ae,a,c);case 3:var e;a:for(var f=Ke,g=a,j=I.call(i,c);;)if(z(j))if(g=Ae.call(i,g,J.call(i,j),f),z(ne.call(i,f,g))){e=d;break a}else j=L.call(i,j);else{e=g;break a}return e}b("Invalid arity: "+arguments.length)}}(),Xf=function Wf(c,d,e){var f=M.call(i,d,0,i),d=kf.call(i,d,1);return z(d)?Be.call(i,c,
f,Wf.call(i,Ae.call(i,c,f),d,e)):Be.call(i,c,f,e)};function Yf(a,c){this.e=a;this.p=c}l=Yf.prototype;l.s=function(a,c){return te.call(i,a,c)};l.O=function(a,c){var d=Hd.call(i,this.p);d.push(c);return new Yf(this.e,d)};l.I=function(){var a=this;return z($e.call(i,a.p.length,0))?function d(e){return new Q(i,!1,function(){return z(Ye.call(i,e,a.p.length))?P.call(i,a.p[e],d.call(i,F.call(i,e))):i})}.call(i,0):i};l.Pb=!0;l.S=function(a,c){return new Yf(c,this.p)};
l.Pa=function(){function a(a,c,f){var g=this;return z(function(){var a=Ze.call(i,0,c);return z(a)?Ye.call(i,c,g.p.length):a}())?g.p[c]:f}function c(a,c){var f=this;return z(function(){var a=Ze.call(i,0,c);return z(a)?Ye.call(i,c,f.p.length):a}())?f.p[c]:i}return function(d,e,f){switch(arguments.length){case 2:return c.call(this,0,e);case 3:return a.call(this,0,e,f)}b("Invalid arity: "+arguments.length)}}();l.Q=!0;l.R=k("e");
l.Da=function(){return function(a,c,d){switch(arguments.length){case 2:return re.call(i,this.p,c);case 3:return re.call(i,this.p,c,d)}b("Invalid arity: "+arguments.length)}}();l.P=function(a){return of.call(i,a)};l.ja=function(){return this.p.length};l.na=!0;l.Oa=function(a,c,d){a=Hd.call(i,this.p);a[c]=d;return new Yf(this.e,a)};l.ka=function(){return function(a,c,d){switch(arguments.length){case 2:return B.call(i,a,c,i);case 3:return B.call(i,a,c,d)}b("Invalid arity: "+arguments.length)}}();
var Zf=new Yf(i,Id.call(i));function R(a){return new Yf(i,a)}Yf.prototype.call=function(){return function(a,c,d){switch(arguments.length){case 2:return C.call(i,this,c);case 3:return C.call(i,this,c,d)}b("Invalid arity: "+arguments.length)}}();function $f(a){return Ue.call(i,ye,Zf,a)}function ag(a){var c=H(Array.prototype.slice.call(arguments,0),0);return $f.call(i,c)}function bg(){}bg.prototype.s=ba(!1);var cg=new bg;
function dg(a,c){return Ne.call(i,z(Ge.call(i,c))?z(D.call(i,ze.call(i,a),ze.call(i,c)))?Df.call(i,Ff,Hf.call(i,function(a){return D.call(i,Ae.call(i,c,J.call(i,a),cg),ve.call(i,a))},a)):i:i)}function eg(a,c,d){for(var e=d.length,f=0;;)if(z(Ye.call(i,f,e)))if(z(D.call(i,c,d[f])))return f;else f=N.call(i,f,a);else return i}
var fg=function(){function a(a,c,f,g){return z(function(){var f=q.call(i,a);return z(f)?c.hasOwnProperty(a):f}())?f:g}var c=i;return c=function(d,e,f,g){switch(arguments.length){case 2:return c.call(i,d,e,!0,!1);case 4:return a.call(this,d,e,f,g)}b("Invalid arity: "+arguments.length)}}();function gg(a,c,d){this.e=a;this.keys=c;this.La=d}l=gg.prototype;l.s=function(a,c){return dg.call(i,a,c)};l.O=function(a,c){return z(He.call(i,c))?Td.call(i,a,B.call(i,c,0),B.call(i,c,1)):Ue.call(i,Md,a,c)};
l.I=function(){var a=this;return z(hf.call(i,a.keys.length))?Hf.call(i,function(c){return ag.call(i,c,a.La[c])},a.keys):i};l.S=function(a,c){return new gg(c,this.keys,this.La)};l.wb=!0;l.Q=!0;l.R=k("e");l.P=function(a){return of.call(i,a)};l.ja=function(){return this.keys.length};
l.Oa=function(a,c,d){if(z(q.call(i,c))){var a=Gb.call(i,this.La),e=a.hasOwnProperty(c);a[c]=d;return z(e)?new gg(this.e,this.keys,a):(d=Hd.call(i,this.keys),d.push(c),new gg(this.e,d,a))}else return Ce.call(i,Tf.call(i,pe.call(i,c,d),I.call(i,a)),this.e)};l.ka=function(){return function(a,c,d){switch(arguments.length){case 2:return C.call(i,a,c,i);case 3:return fg.call(i,c,this.La,this.La[c],d)}b("Invalid arity: "+arguments.length)}}();Id.call(i);function S(a,c){return new gg(i,a,c)}
gg.prototype.call=function(){return function(a,c,d){switch(arguments.length){case 2:return C.call(i,this,c);case 3:return C.call(i,this,c,d)}b("Invalid arity: "+arguments.length)}}();function hg(a,c,d){this.e=a;this.count=c;this.ga=d}l=hg.prototype;l.s=function(a,c){return dg.call(i,a,c)};l.O=function(a,c){return z(He.call(i,c))?Td.call(i,a,B.call(i,c,0),B.call(i,c,1)):Ue.call(i,Md,a,c)};
l.I=function(){var a=this;if(z(hf.call(i,a.count))){var c=Je.call(i,a.ga);return Pf.call(i,function(c){return Hf.call(i,$f,Uf.call(i,2,a.ga[c]))},c)}else return i};l.S=function(a,c){return new hg(c,this.count,this.ga)};l.wb=!0;l.Q=!0;l.R=k("e");l.P=function(a){return of.call(i,a)};l.ja=k("count");
l.Oa=function(a,c,d){var a=Ee.call(i,c),e=this.ga[a];if(z(e)){var e=Hd.call(i,e),f=Gb.call(i,this.ga);f[a]=e;a=eg.call(i,2,c,e);return z(a)?(e[F.call(i,a)]=d,new hg(this.e,this.count,f)):(e.push(c,d),new hg(this.e,F.call(i,this.count),f))}else return e=Gb.call(i,this.ga),e[a]=Id.call(i,c,d),new hg(this.e,F.call(i,this.count),e)};
l.ka=function(){return function(a,c,d){switch(arguments.length){case 2:return C.call(i,a,c,i);case 3:var e=this.ga[Ee.call(i,c)],f=z(e)?eg.call(i,2,c,e):i;return z(f)?e[F.call(i,f)]:d}b("Invalid arity: "+arguments.length)}}();var ig=new hg(i,0,Ie.call(i));function jg(){for(var a=[R([-1,17]),R([28,17])],c=[S(["\ufdd0'open"],{"\ufdd0'open":i}),S(["\ufdd0'open"],{"\ufdd0'open":i})],d=a.length,e=0,f=ig;;)if(z(Ye.call(i,e,d)))var g=F.call(i,e),f=Be.call(i,f,a[e],c[e]),e=g;else return f}
hg.prototype.call=function(){return function(a,c,d){switch(arguments.length){case 2:return C.call(i,this,c);case 3:return C.call(i,this,c,d)}b("Invalid arity: "+arguments.length)}}();function pe(a){for(var c=H(Array.prototype.slice.call(arguments,0),0),c=I.call(i,c),d=ig;;)if(z(c))var e=we.call(i,c),d=Be.call(i,d,J.call(i,c),ve.call(i,c)),c=e;else return d}function kg(a){return I.call(i,Hf.call(i,J,a))}pe.call(i);
function lg(a){if(z(Oe.call(i,a)))return a;else if(z(function(){var c=Pe.call(i,a);return z(c)?c:Qe.call(i,a)}())){var c=a.lastIndexOf("/");return z(Ye.call(i,c,0))?mf.call(i,a,2):mf.call(i,a,F.call(i,c))}else return i}function mg(a){if(z(function(){var c=Pe.call(i,a);return z(c)?c:Qe.call(i,a)}())){var c=a.lastIndexOf("/");return z($e.call(i,c,-1))?mf.call(i,a,2,c):i}else return"\ufdd0'else"}
function ng(a,c){for(var d=S([],{}),e=I.call(i,a),f=I.call(i,c);;)if(z(function(){var a=e;return z(a)?f:a}()))var d=Be.call(i,d,J.call(i,e),J.call(i,f)),g=L.call(i,e),j=L.call(i,f),e=g,f=j;else return d}
var og=function(){function a(a,d){for(;;)if(z(function(){var e=I.call(i,d);return z(e)?hf.call(i,a):e}()))var e=af.call(i,a),f=L.call(i,d),a=e,d=f;else return i}return function(c,d){switch(arguments.length){case 1:var e;a:for(var f=c;;)if(z(I.call(i,f)))f=L.call(i,f);else{e=i;break a}return e;case 2:return a.call(this,c,d)}b("Invalid arity: "+arguments.length)}}(),pg=function(){return function(a,c){switch(arguments.length){case 1:return og.call(i,a),a;case 2:return og.call(i,a,c),c}b("Invalid arity: "+
arguments.length)}}();function qg(a,c,d,e,f,g){return zf.call(i,R([c]),Of.call(i,Nf.call(i,R([d]),Hf.call(i,function(c){return a.call(i,c,f)},g))),R([e]))}
var sg=function rg(c,d){return z(E.call(i,c))?oe.call(i,"nil"):z(Le.call(i,c))?oe.call(i,"#<undefined>"):z("\ufdd0'else")?zf.call(i,z(function(){var e=Ae.call(i,d,"\ufdd0'meta");return z(e)?(e=z(z(c)?c.Q:c)?!0:Gd.call(i,Yd,c),z(e)?De.call(i,c):e):e}())?zf.call(i,R(["^"]),rg.call(i,De.call(i,c),d),R([" "])):i,z(z(z(c)?c.H:c)?!0:Gd.call(i,ke,c))?me.call(i,c,d):oe.call(i,"#<",lf.call(i,c),">")):i};
function tg(a,c){for(var d=J.call(i,a),e=new La,f=I.call(i,a);;)if(z(f)){var g=J.call(i,f);z(ne.call(i,g,d))||e.append(" ");for(g=I.call(i,sg.call(i,g,c));;)if(z(g)){var j=J.call(i,g);e.append(j);g=L.call(i,g)}else break;f=L.call(i,f)}else break;return lf.call(i,e)}function ug(){return S(["\ufdd0'flush-on-newline","\ufdd0'readably","\ufdd0'meta","\ufdd0'dup"],{"\ufdd0'flush-on-newline":!0,"\ufdd0'readably":!0,"\ufdd0'meta":!1,"\ufdd0'dup":!1})}
function vg(a){var c=H(Array.prototype.slice.call(arguments,0),0);return tg.call(i,c,ug.call(i))}hg.prototype.H=!0;hg.prototype.z=function(a,c){return qg.call(i,function(a){return qg.call(i,sg,""," ","",c,a)},"{",", ","}",c,a)};ke.number=!0;me.number=function(a){return oe.call(i,lf.call(i,a))};se.prototype.H=!0;se.prototype.z=function(a,c){return qg.call(i,sg,"("," ",")",c,a)};Q.prototype.H=!0;Q.prototype.z=function(a,c){return qg.call(i,sg,"("," ",")",c,a)};ke["boolean"]=!0;
me["boolean"]=function(a){return oe.call(i,lf.call(i,a))};ke.string=!0;me.string=function(a,c){return z(Pe.call(i,a))?oe.call(i,lf.call(i,":",function(){var c=mg.call(i,a);return z(c)?lf.call(i,c,"/"):i}(),lg.call(i,a))):z(Qe.call(i,a))?oe.call(i,lf.call(i,function(){var c=mg.call(i,a);return z(c)?lf.call(i,c,"/"):i}(),lg.call(i,a))):z("\ufdd0'else")?oe.call(i,z("\ufdd0'readably".call(i,c))?za.call(i,a):a):i};Yf.prototype.H=!0;Yf.prototype.z=function(a,c){return qg.call(i,sg,"["," ","]",c,a)};
pf.prototype.H=!0;pf.prototype.z=function(a,c){return qg.call(i,sg,"("," ",")",c,a)};ke.array=!0;me.array=function(a,c){return qg.call(i,sg,"#<Array [",", ","]>",c,a)};qf.prototype.H=!0;qf.prototype.z=function(){return oe.call(i,"()")};tf.prototype.H=!0;tf.prototype.z=function(a,c){return qg.call(i,sg,"("," ",")",c,a)};gg.prototype.H=!0;gg.prototype.z=function(a,c){return qg.call(i,function(a){return qg.call(i,sg,""," ","",c,a)},"{",", ","}",c,a)};
function wg(a,c,d){this.state=a;this.e=c;this.gc=d}l=wg.prototype;l.H=!0;l.z=function(a,c){return zf.call(i,R(["#<Atom: "]),me.call(i,this.state,c),">")};l.Q=!0;l.R=k("e");l.Ob=k("state");l.s=function(a,c){return ne.call(i,a,c)};
var xg=function(){function a(a,c){var f=H(Array.prototype.slice.call(arguments,1),0),g=z(Me.call(i,f))?Bf.call(i,pe,f):f,f=Ae.call(i,g,"\ufdd0'validator"),g=Ae.call(i,g,"\ufdd0'meta");return new wg(a,g,f)}var c=i,c=function(c,e){switch(arguments.length){case 1:return new wg(c,i,i);default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=1;c.b=function(c){var e=J(c),c=K(c);return a.call(i,e,c)};return c}();
function yg(a,c){var d=a.gc;z(d)&&!z(d.call(i,c))&&b("Validator rejected reference state");return a.state=c}
var zg=function(){function a(a,c,f,g,j,m){var o=H(Array.prototype.slice.call(arguments,5),0);return yg.call(i,a,Bf.call(i,c,a.state,f,g,j,o))}var c=i,c=function(c,e,f,g,j,m){switch(arguments.length){case 2:return yg.call(i,c,e.call(i,c.state));case 3:return yg.call(i,c,e.call(i,c.state,f));case 4:return yg.call(i,c,e.call(i,c.state,f,g));case 5:return yg.call(i,c,e.call(i,c.state,f,g,j));default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.f=5;c.b=function(c){var e=J(c),
f=J(L(c)),g=J(L(L(c))),j=J(L(L(L(c)))),m=J(L(L(L(L(c))))),c=K(L(L(L(L(c)))));return a.call(i,e,f,g,j,m,c)};return c}();function Ag(a){return Xd.call(i,a)};function T(a,c){return R([a,c])}function Bg(a){return Hf.call(i,function(a){return We.call(i,8,a)},a)}function Cg(a,c){return Hf.call(i,function(a,c){return N.call(i,a,c)},a,c)}function Dg(a){return Cg.call(i,R([4,4]),Bg.call(i,a))}function U(a){return Cg.call(i,R([0,4]),Bg.call(i,a))}function Eg(a,c){return T.call(i,Math.floor.call(i,Xe.call(i,a,8)),Math.floor.call(i,Xe.call(i,c,8)))}function Fg(a,c){var d=D.call(i,4,bf.call(i,a,8));return z(d)?D.call(i,4,bf.call(i,c,8)):d};function Gg(a){return dc.call(i,"debug").innerHTML=a};function Hg(a){return Cg.call(i,R([0,0]),Bg.call(i,a))}function V(a){return Cg.call(i,R([4,7]),Bg.call(i,a))}function Ig(a){return Cg.call(i,R([0,7]),Bg.call(i,a))}function X(a){return Cg.call(i,R([4,0]),Bg.call(i,a))}function Jg(a){return Cg.call(i,R([7,7]),Bg.call(i,a))}function Kg(a){return Cg.call(i,R([7,0]),Bg.call(i,a))}function Y(a){return Cg.call(i,R([7,4]),Bg.call(i,a))}function Lg(a,c){var d=M.call(i,c,0,i),e=M.call(i,c,1,i);return a.moveTo(d,e)}
function Z(a,c){var d=M.call(i,c,0,i),e=M.call(i,c,1,i);return a.lineTo(d,e)}function $(a,c){var d=M.call(i,c,0,i),e=M.call(i,c,1,i),f=a.m,g=M.call(i,f,0,i),f=M.call(i,f,1,i);return a.arcTo(O.call(i,d,g),O.call(i,e,f),-90,90)}function Mg(a,c){var d=M.call(i,c,0,i),e=M.call(i,c,1,i),f=a.m,g=M.call(i,f,0,i),f=M.call(i,f,1,i);return a.arcTo(O.call(i,d,g),O.call(i,e,f),180,-90)}
function Ng(a,c,d,e){return $.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,Lg.call(i,new x,Y.call(i,T.call(i,a,c))),U.call(i,T.call(i,d,c))),V.call(i,T.call(i,d,c))),X.call(i,T.call(i,d,e))),U.call(i,T.call(i,d,e))),Y.call(i,T.call(i,a,e))),X.call(i,T.call(i,a,e))),V.call(i,T.call(i,a,c))),Y.call(i,T.call(i,a,c)))}
function Og(a,c){return $.call(i,$.call(i,Z.call(i,Mg.call(i,Z.call(i,$.call(i,$.call(i,Z.call(i,Mg.call(i,Z.call(i,$.call(i,$.call(i,Z.call(i,Lg.call(i,new x,Y.call(i,T.call(i,a,c))),U.call(i,T.call(i,N.call(i,7,a),c))),V.call(i,T.call(i,N.call(i,7,a),c))),U.call(i,T.call(i,N.call(i,7,a),N.call(i,1,c)))),Y.call(i,T.call(i,N.call(i,4,a),N.call(i,1,c)))),V.call(i,T.call(i,N.call(i,4,a),N.call(i,1,c)))),X.call(i,T.call(i,N.call(i,4,a),N.call(i,4,c)))),U.call(i,T.call(i,N.call(i,4,a),N.call(i,4,c)))),
X.call(i,T.call(i,13,N.call(i,4,c)))),V.call(i,T.call(i,N.call(i,3,a),N.call(i,1,c)))),U.call(i,T.call(i,N.call(i,3,a),N.call(i,1,c)))),Y.call(i,T.call(i,a,N.call(i,1,c)))),X.call(i,T.call(i,a,N.call(i,1,c)))),Y.call(i,T.call(i,a,c)))}
function Pg(a,c){var d=new nd(c),e=new x;Z.call(i,Z.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,Z.call(i,Z.call(i,Lg.call(i,e,Hg.call(i,T.call(i,0,16))),Hg.call(i,T.call(i,5,16))),Ig.call(i,T.call(i,5,12))),V.call(i,T.call(i,0,12))),U.call(i,T.call(i,0,12))),U.call(i,T.call(i,0,3))),X.call(i,T.call(i,0,3))),X.call(i,T.call(i,27,3))),Y.call(i,T.call(i,27,3))),Y.call(i,T.call(i,27,12))),V.call(i,T.call(i,27,12))),Jg.call(i,T.call(i,22,12))),Kg.call(i,T.call(i,
22,16))),Kg.call(i,T.call(i,27,16)));a.i(e,d);e=new x;Z.call(i,Mg.call(i,Z.call(i,Mg.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,Mg.call(i,Mg.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,Mg.call(i,Z.call(i,Mg.call(i,Z.call(i,Lg.call(i,e,U.call(i,T.call(i,0,16))),U.call(i,T.call(i,5,16))),X.call(i,T.call(i,5,16))),V.call(i,T.call(i,5,12))),U.call(i,T.call(i,5,12))),Y.call(i,T.call(i,0,12))),X.call(i,T.call(i,0,12))),V.call(i,T.call(i,0,3))),Y.call(i,
T.call(i,0,3))),U.call(i,T.call(i,13,3))),V.call(i,T.call(i,13,3))),X.call(i,T.call(i,13,7))),Y.call(i,T.call(i,13,7))),X.call(i,T.call(i,14,7))),V.call(i,T.call(i,14,3))),Y.call(i,T.call(i,14,3))),U.call(i,T.call(i,27,3))),V.call(i,T.call(i,27,3))),X.call(i,T.call(i,27,12))),U.call(i,T.call(i,27,12))),Y.call(i,T.call(i,22,12))),V.call(i,T.call(i,22,12))),X.call(i,T.call(i,22,16))),Y.call(i,T.call(i,22,16))),Y.call(i,T.call(i,27,16)));a.i(e,d);a.i(Ng.call(i,2,5,5,7),d);a.i(Ng.call(i,7,5,11,7),d);
a.i(Ng.call(i,16,5,20,7),d);a.i(Ng.call(i,22,5,25,7),d);a.i(Ng.call(i,2,9,5,10),d);a.i(Ng.call(i,22,9,25,10),d);a.i(Ng.call(i,7,18,8,22),d);a.i(Ng.call(i,19,18,20,22),d);a.i(Ng.call(i,7,24,11,25),d);a.i(Ng.call(i,16,24,20,25),d);e=new x;Z.call(i,Z.call(i,Z.call(i,Z.call(i,Lg.call(i,e,Dg.call(i,T.call(i,10,15))),Dg.call(i,T.call(i,17,15))),Dg.call(i,T.call(i,17,19))),Dg.call(i,T.call(i,10,19))),Dg.call(i,T.call(i,10,15)));a.i(e,d);e=new x;Z.call(i,Z.call(i,Z.call(i,Z.call(i,Lg.call(i,e,Jg.call(i,T.call(i,
10,15))),Ig.call(i,T.call(i,17,15))),Hg.call(i,T.call(i,17,19))),Kg.call(i,T.call(i,10,19))),Jg.call(i,T.call(i,10,15)));a.i(e,d);a.i(Og.call(i,10,9),d);a.i(Og.call(i,10,21),d);a.i(Og.call(i,10,27),d);e=new x;Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,Mg.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,Mg.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Lg.call(i,e,V.call(i,T.call(i,7,9))),Y.call(i,T.call(i,7,9))),U.call(i,T.call(i,8,9))),V.call(i,T.call(i,8,9))),X.call(i,T.call(i,8,12))),Y.call(i,
T.call(i,8,12))),U.call(i,T.call(i,11,12))),V.call(i,T.call(i,11,12))),X.call(i,T.call(i,11,13))),U.call(i,T.call(i,11,13))),Y.call(i,T.call(i,8,13))),V.call(i,T.call(i,8,13))),X.call(i,T.call(i,8,16))),U.call(i,T.call(i,8,16))),Y.call(i,T.call(i,7,16))),X.call(i,T.call(i,7,16))),V.call(i,T.call(i,7,9)));a.i(e,d);e=new x;Z.call(i,Mg.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,Mg.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Lg.call(i,e,V.call(i,T.call(i,19,
9))),Y.call(i,T.call(i,19,9))),U.call(i,T.call(i,20,9))),V.call(i,T.call(i,20,9))),X.call(i,T.call(i,20,16))),U.call(i,T.call(i,20,16))),Y.call(i,T.call(i,19,16))),X.call(i,T.call(i,19,16))),V.call(i,T.call(i,19,13))),U.call(i,T.call(i,19,13))),Y.call(i,T.call(i,16,13))),X.call(i,T.call(i,16,13))),V.call(i,T.call(i,16,12))),Y.call(i,T.call(i,16,12))),U.call(i,T.call(i,19,12))),X.call(i,T.call(i,19,12))),V.call(i,T.call(i,19,9)));a.i(e,d);e=new x;Z.call(i,$.call(i,Z.call(i,Mg.call(i,Z.call(i,$.call(i,
Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,$.call(i,Lg.call(i,e,V.call(i,T.call(i,2,24))),Y.call(i,T.call(i,2,24))),U.call(i,T.call(i,5,24))),V.call(i,T.call(i,5,24))),X.call(i,T.call(i,5,28))),U.call(i,T.call(i,5,28))),Y.call(i,T.call(i,4,28))),X.call(i,T.call(i,4,28))),V.call(i,T.call(i,4,25))),U.call(i,T.call(i,4,25))),Y.call(i,T.call(i,2,25))),X.call(i,T.call(i,2,25))),V.call(i,T.call(i,2,24)));a.i(e,d);e=new x;Z.call(i,$.call(i,Z.call(i,$.call(i,Z.call(i,Mg.call(i,Z.call(i,$.call(i,Z.call(i,
$.call(i,Z.call(i,$.call(i,Lg.call(i,e,V.call(i,T.call(i,22,24))),Y.call(i,T.call(i,22,24))),U.call(i,T.call(i,25,24))),V.call(i,T.call(i,25,24))),X.call(i,T.call(i,25,25))),U.call(i,T.call(i,25,25))),Y.call(i,T.call(i,23,25))),V.call(i,T.call(i,23,25))),X.call(i,T.call(i,23,28))),U.call(i,T.call(i,23,28))),Y.call(i,T.call(i,22,28))),X.call(i,T.call(i,22,28))),V.call(i,T.call(i,22,24)));return a.i(e,d)};var Qg,Rg,Sg,Tg=new sd("#FFB9AF"),Ug=new sd("#000"),Vg=S(["\ufdd0'blinky"],{"\ufdd0'blinky":"#F00"});function Wg(a){return a.gb(0,0,a.width,a.height,i,new sd("#000"))}function Xg(a,c){var d=Dg.call(i,c),e=M.call(i,d,0,i),d=M.call(i,d,1,i);return a.Fa(e,d,1,1,i,Tg,h)}function Yg(a,c){var d=Dg.call(i,c),e=M.call(i,d,0,i),d=M.call(i,d,1,i);return a.Fa(e,d,3,3,i,Tg,h)}
function Zg(a,c,d,e,f){c=kg.call(i,Rf.call(i,function(a){return Te.call(i,ve.call(i,a),d)},c));return pg.call(i,Hf.call(i,function(c){return zg.call(i,f,Be,c,e.call(i,a,c))},c))}function $g(a){a=Qg.call(i,a);z(xe.call(i,E.call(i,a)))?(a.fill=Ug,a.D.Za(a,Ug),a=h):a=i;return a}function ah(a,c){var d=c.call(i,"\ufdd0'pos");M.call(i,d,0,i);M.call(i,d,1,i);d=new x;d.moveTo(4,-4);d.ub(5.6,5.6,-45,270);d.moveTo(4,-4);d.lineTo(0,0);d.lineTo(-4,-4);Rg=a.i(d,new nd("#FF0"))}
var bh=S(["\ufdd0'north","\ufdd0'south","\ufdd0'east","\ufdd0'west","\ufdd0'none"],{"\ufdd0'north":0,"\ufdd0'south":180,"\ufdd0'east":90,"\ufdd0'west":270,"\ufdd0'none":0});function ch(a,c){var d=M.call(i,a,0,i),e=M.call(i,a,1,i),f=Rg,g=bh.call(i,c);f.rb=oc(mc(g),0,0).translate(d,e);f.D.ob(f,d,e,g,0,0)}function dh(a,c){var d=M.call(i,c,0,i),e=M.call(i,c,1,i);return Sg.call(i,a).mb(d,e)}function eh(a,c,d){var e=M.call(i,c,0,i),c=M.call(i,c,1,i);return a.Fa(e,c,4,4,i,new sd(d))}
function fh(a,c){Sg=S(["\ufdd0'blinky"],{"\ufdd0'blinky":eh.call(i,a,c.call(i,"\ufdd0'blinky").call(i,"\ufdd0'pos"),Vg.call(i,"\ufdd0'blinky"))})};var gh,hh=R(["                            ","                            ","                            ","                            "," pppppppppppp  pppppppppppp "," p    p     p  p     p    p "," e    p     p  p     p    e "," p    p     p  p     p    p "," pppppppppppppppppppppppppp "," p    p  p        p  p    p "," p    p  p        p  p    p "," pppppp  pppp  pppp  pppppp ","      p     o  o     p      ","      p     o  o     p      ","      p  oooooooooo  p      ","      p  o        o  p      ",
"      p  o gggggg o  p      ","oooooopooo gggggg ooopoooooo","      p  o gggggg o  p      ","      p  o        o  p      ","      p  oooooooooo  p      ","      p  o        o  p      ","      p  o        o  p      "," pppppppppppp  pppppppppppp "," p    p     p  p     p    p "," p    p     p  p     p    p "," epp  pppppppooppppppp  ppe ","   p  p  p        p  p  p   ","   p  p  p        p  p  p   "," pppppp  pppp  pppp  pppppp "," p          p  p          p "," p          p  p          p "," pppppppppppppppppppppppppp ",
"                            ","                            ","                            "]),ih=function(){var a=i;return a=function(c,d){switch(arguments.length){case 1:return a.call(i,c,rf);case 2:var e;a:for(var f=c,g=d;;)if(z(D.call(i,0,f))){e=g;break a}else var j=af.call(i,f),g=ye.call(i,g,O.call(i,f,1)),f=j;return e}b("Invalid arity: "+arguments.length)}}();function jh(a){var c=M.call(i,a,0,i),a=M.call(i,a,1,i);return Te.call(i,gh.call(i,R([c,a])),"\ufdd0'open")}
function kh(a){var c=M.call(i,a,0,i),a=M.call(i,a,1,i);return Rf.call(i,function(a){return xe.call(i,E.call(i,a))},R([z(jh.call(i,R([N.call(i,c,1),a])))?"\ufdd0'east":i,z(jh.call(i,R([O.call(i,c,1),a])))?"\ufdd0'west":i,z(jh.call(i,R([c,O.call(i,a,1)])))?"\ufdd0'north":i,z(jh.call(i,R([c,N.call(i,a,1)])))?"\ufdd0'south":i]))};var lh=xg.call(i,i);function mh(){return Ag.call(i,lh)}function nh(){return yg.call(i,lh,i)}function oh(a){a=a.keyCode;return z(D.call(i,a,38))?yg.call(i,lh,"\ufdd0'north"):z(D.call(i,a,40))?yg.call(i,lh,"\ufdd0'south"):z(D.call(i,a,37))?yg.call(i,lh,"\ufdd0'west"):z(D.call(i,a,39))?yg.call(i,lh,"\ufdd0'east"):i};var ph=S(["\ufdd0'west","\ufdd0'east","\ufdd0'north","\ufdd0'south"],{"\ufdd0'west":R([-1,0]),"\ufdd0'east":R([1,0]),"\ufdd0'north":R([0,-1]),"\ufdd0'south":R([0,1])});function qh(a,c){var d=M.call(i,a,0,i),e=M.call(i,a,1,i),f=M.call(i,c,0,i),g=M.call(i,c,1,i);return R([N.call(i,d,f),N.call(i,e,g)])}function rh(a,c){var d=M.call(i,a,0,i),e=M.call(i,a,1,i),f=M.call(i,c,0,i),g=M.call(i,c,1,i);return N.call(i,We.call(i,O.call(i,d,f),O.call(i,d,f)),We.call(i,O.call(i,e,g),O.call(i,e,g)))}
function sh(a,c,d){d=ng.call(i,d,Hf.call(i,function(d){return rh.call(i,c,qh.call(i,a,ph.call(i,d)))},d));return J.call(i,Ue.call(i,function(a,c){return z(Ye.call(i,ve.call(i,c),ve.call(i,a)))?c:a},oe("\ufdd0'too-big",1E6),d))};var th=S(["\ufdd0'pacman","\ufdd0'blinky"],{"\ufdd0'pacman":T.call(i,14,26),"\ufdd0'blinky":T.call(i,14,14)}),uh=S(["\ufdd0'west","\ufdd0'east","\ufdd0'north","\ufdd0'south","\ufdd0'none"],{"\ufdd0'west":R([-1,0]),"\ufdd0'east":R([1,0]),"\ufdd0'north":R([0,-1]),"\ufdd0'south":R([0,1]),"\ufdd0'none":R([0,0])}),vh=S(["\ufdd0'pos","\ufdd0'tile","\ufdd0'face","\ufdd0'move-dir"],{"\ufdd0'pos":U.call(i,th.call(i,"\ufdd0'pacman")),"\ufdd0'tile":th.call(i,"\ufdd0'pacman"),"\ufdd0'face":"\ufdd0'west","\ufdd0'move-dir":"\ufdd0'west"}),
wh=S(["\ufdd0'blinky"],{"\ufdd0'blinky":S(["\ufdd0'pos","\ufdd0'tile","\ufdd0'target-tile","\ufdd0'home","\ufdd0'face","\ufdd0'next-turn"],{"\ufdd0'pos":U.call(i,th.call(i,"\ufdd0'blinky")),"\ufdd0'tile":th.call(i,"\ufdd0'blinky"),"\ufdd0'target-tile":T.call(i,27,0),"\ufdd0'home":T.call(i,27,0),"\ufdd0'face":"\ufdd0'west","\ufdd0'next-turn":"\ufdd0'none"})}),xh=S(["\ufdd0'east","\ufdd0'west","\ufdd0'north","\ufdd0'south"],{"\ufdd0'east":"\ufdd0'west","\ufdd0'west":"\ufdd0'east","\ufdd0'north":"\ufdd0'south",
"\ufdd0'south":"\ufdd0'north"});
function yh(a,c,d,e){if(z(D.call(i,e,xh.call(i,d))))return d;else{var f=Eg.call(i,a,c),g=M.call(i,f,0,i),j=M.call(i,f,1,i);return z(Fg.call(i,a,c))?z(function(){var a=D.call(i,"\ufdd0'north",d);return z(a)?jh.call(i,R([g,O.call(i,j,1)])):a}())?(nh.call(i),d):z(function(){var a=D.call(i,"\ufdd0'south",d);return z(a)?jh.call(i,R([g,N.call(i,j,1)])):a}())?(nh.call(i),d):z(function(){var a=D.call(i,"\ufdd0'east",d);return z(a)?jh.call(i,R([N.call(i,g,1),j])):a}())?(nh.call(i),d):z(function(){var a=D.call(i,
"\ufdd0'west",d);return z(a)?jh.call(i,R([O.call(i,g,1),j])):a}())?(nh.call(i),d):z(function(){var a=D.call(i,"\ufdd0'north",e);return z(a)?jh.call(i,R([g,O.call(i,j,1)])):a}())?e:z(function(){var a=D.call(i,"\ufdd0'south",e);return z(a)?jh.call(i,R([g,N.call(i,j,1)])):a}())?e:z(function(){var a=D.call(i,"\ufdd0'east",e);return z(a)?jh.call(i,R([N.call(i,g,1),j])):a}())?e:z(function(){var a=D.call(i,"\ufdd0'west",e);return z(a)?jh.call(i,R([O.call(i,g,1),j])):a}())?e:z("\ufdd0'else")?"\ufdd0'none":
i:e}}
function zh(a,c){var d=a.call(i,"\ufdd0'pos"),e=M.call(i,d,0,i),f=M.call(i,d,1,i),d=yh.call(i,e,f,c,a.call(i,"\ufdd0'move-dir")),g=z(D.call(i,"\ufdd0'none",d))?a.call(i,"\ufdd0'face"):d,j=uh.call(i,d),m=M.call(i,j,0,i),j=M.call(i,j,1,i),f=R([bf.call(i,N.call(i,224,e,m),224),N.call(i,f,j)]),e=M.call(i,f,0,i),f=M.call(i,f,1,i),m=Eg.call(i,e,f);ch.call(i,R([e,f]),g);z(Cf.call(i,a.call(i,"\ufdd0'tile"),m))&&$g.call(i,m);return Be.call(i,a,"\ufdd0'face",g,"\ufdd0'move-dir",d,"\ufdd0'pos",R([e,f]),"\ufdd0'tile",
m)}function Ah(a){var c=a.call(i,"\ufdd0'pos"),d=M.call(i,c,0,i),c=M.call(i,c,1,i);return z(Fg.call(i,d,c))?a.call(i,"\ufdd0'next-turn"):a.call(i,"\ufdd0'face")}
function Bh(a,c){var d=c.call(i,"\ufdd0'pos"),e=M.call(i,d,0,i),f=M.call(i,d,1,i),d=Ah.call(i,c),g=uh.call(i,d),j=M.call(i,g,0,i),g=M.call(i,g,1,i),f=R([N.call(i,e,j),N.call(i,f,g)]),e=M.call(i,f,0,i),f=M.call(i,f,1,i),m=Eg.call(i,e,f);dh.call(i,a,R([e,f]));j=z(Cf.call(i,c.call(i,"\ufdd0'tile"),m))?function(){var a=kh.call(i,m),a=Sf.call(i,function(a){return D.call(i,xh.call(i,c.call(i,"\ufdd0'face")),a)},a);return sh.call(i,m,c.call(i,"\ufdd0'target-tile"),a)}():c.call(i,"\ufdd0'next-turn");return Be.call(i,
c,"\ufdd0'pos",R([e,f]),"\ufdd0'tile",m,"\ufdd0'face",d,"\ufdd0'next-turn",j)}function Ch(a){return Be.call(i,a,"\ufdd0'blinky",Bh.call(i,"\ufdd0'blinky",a.call(i,"\ufdd0'blinky")))}function Dh(a){return Ef.call(i,Math.floor.call(i,Xe.call(i,a,1E3)))}
function Eh(a,c,d){var e=Dh.call(i,d);Gg.call(i,vg.call(i,R([d,e])));return z(e)?Xf.call(i,a,R(["\ufdd0'blinky","\ufdd0'target-tile"]),c.call(i,"\ufdd0'tile")):Xf.call(i,a,R(["\ufdd0'blinky","\ufdd0'target-tile"]),Vf.call(i,a,R(["\ufdd0'blinky","\ufdd0'home"])))}
function Fh(a,c){var d=Eh.call(i,a.call(i,"\ufdd0'ghosts"),a.call(i,"\ufdd0'pacman"),a.call(i,"\ufdd0'tick"));return Be.call(i,a,"\ufdd0'tick",F.call(i,a.call(i,"\ufdd0'tick")),"\ufdd0'ghosts",Ch.call(i,d),"\ufdd0'pacman",zh.call(i,a.call(i,"\ufdd0'pacman"),c,a.call(i,"\ufdd0'board")))}
var Gh=function(){var a=xg.call(i,jg());pg.call(i,function(){return function d(e){return new Q(i,!1,function(){for(var f=e;;)if(z(I.call(i,f))){var g=J.call(i,f),j=I.call(i,function o(d){return new Q(i,!1,function(){for(;;)if(z(I.call(i,d))){var e=J.call(i,d);return P.call(i,function(){var d=Vf.call(i,hh,R([g,e]));return zg.call(i,a,Be,R([e,g]),z(D.call(i,d," "))?S([],{}):z(D.call(i,d,"p"))?S(["\ufdd0'open","\ufdd0'pellet"],{"\ufdd0'open":i,"\ufdd0'pellet":i}):z(D.call(i,d,"o"))?S(["\ufdd0'open"],
{"\ufdd0'open":i}):z(D.call(i,d,"e"))?S(["\ufdd0'open","\ufdd0'energy"],{"\ufdd0'open":i,"\ufdd0'energy":i}):z("\ufdd0'else")?i:i)}(),o.call(i,K.call(i,d)))}else return i})}.call(i,ih.call(i,ze.call(i,hh.call(i,0)))));if(z(j))return zf.call(i,j,d.call(i,K.call(i,f)));else f=K.call(i,f)}else return i})}.call(i,ih.call(i,ze.call(i,hh)))}());gh=Ag.call(i,a);return Ag.call(i,a)}.call(i);Gg.call(i,"starting up");
(function(a,c,d){var e=Fd.call(i,224,288);Wg.call(i,e);Pg.call(i,e,"#00F");var f=xg.call(i,S([],{}));Zg.call(i,e,a,"\ufdd0'pellet",Xg,f);Zg.call(i,e,a,"\ufdd0'energy",Yg,f);Qg=Ag.call(i,f);fh.call(i,e,d);ah.call(i,e,c);a=dc.call(i,"playfield");e.n&&b(Error("Component already rendered"));e.c||e.B();a?a.insertBefore(e.c,i):e.K.da.body.appendChild(e.c);(!e.ua||e.ua.n)&&e.U()}).call(i,Gh,vh,wh);(function(){return Mb.call(i,new gd(document),"key",oh)}).call(i);
(function Hh(c){return rd.call(i,function(){return Hh.call(i,Fh.call(i,c,mh.call(i)))},17)}).call(i,S(["\ufdd0'pacman","\ufdd0'ghosts","\ufdd0'board","\ufdd0'tick"],{"\ufdd0'pacman":vh,"\ufdd0'ghosts":wh,"\ufdd0'board":Gh,"\ufdd0'tick":0}));