function b(a){throw a;}var h=void 0,i=null;function aa(){return function(a){return a}}function k(a){return function(){return this[a]}}function ba(a){return function(){return a}}var m,n=this;function ca(){}
function p(a){var c=typeof a;if(c=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return c;var d=Object.prototype.toString.call(a);if(d=="[object Window]")return"object";if(d=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(d=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(c=="function"&&typeof a.call=="undefined")return"object";return c}function da(a){return p(a)=="array"}function ea(a){var c=p(a);return c=="array"||c=="object"&&typeof a.length=="number"}function q(a){return typeof a=="string"}function fa(a){return typeof a=="number"}function ga(a){return p(a)=="function"}function ha(a){a=p(a);return a=="object"||a=="array"||a=="function"}function ia(a){return a[ja]||(a[ja]=++ka)}var ja="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),ka=0;
function la(a,c,d){return a.call.apply(a.bind,arguments)}function ma(a,c,d){var e=c||n;if(arguments.length>2){var f=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,f);return a.apply(e,c)}}else return function(){return a.apply(e,arguments)}}function na(a,c,d){na=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?la:ma;return na.apply(i,arguments)}var oa=Date.now||function(){return+new Date};
function s(a,c){function d(){}d.prototype=c.prototype;a.k=c.prototype;a.prototype=new d;a.prototype.constructor=a};function pa(a){var c=a.length-1;return c>=0&&a.indexOf("%",c)==c}function qa(a){if(!ra.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(sa,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(ta,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(va,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(wa,"&quot;"));return a}var sa=/&/g,ta=/</g,va=/>/g,wa=/\"/g,ra=/[&<>\"]/,xa={"\000":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\x0B",'"':'\\"',"\\":"\\\\"},ya={"'":"\\'"};
function za(a){var o;a=String(a);if(a.quote)return a.quote();else{for(var c=['"'],d=0;d<a.length;d++){var e=a.charAt(d),f=e.charCodeAt(0),g=c,j=d+1,l;if(!(l=xa[e])){if(!(f>31&&f<127))if(e in ya)e=ya[e];else if(e in xa)o=ya[e]=xa[e],e=o;else{f=e;l=e.charCodeAt(0);if(l>31&&l<127)f=e;else{if(l<256){if(f="\\x",l<16||l>256)f+="0"}else f="\\u",l<4096&&(f+="0");f+=l.toString(16).toUpperCase()}e=ya[e]=f}l=e}g[j]=l}c.push('"');return c.join("")}}
function Aa(a,c){for(var d=0,e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=String(c).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),g=Math.max(e.length,f.length),j=0;d==0&&j<g;j++){var l=e[j]||"",o=f[j]||"",r=RegExp("(\\d*)(\\D*)","g"),x=RegExp("(\\d*)(\\D*)","g");do{var F=r.exec(l)||["","",""],T=x.exec(o)||["","",""];if(F[0].length==0&&T[0].length==0)break;d=Ba(F[1].length==0?0:parseInt(F[1],10),T[1].length==0?0:parseInt(T[1],10))||Ba(F[2].length==0,T[2].length==0)||Ba(F[2],T[2])}while(d==
0)}return d}function Ba(a,c){if(a<c)return-1;else if(a>c)return 1;return 0}function Ca(a){for(var c=0,d=0;d<a.length;++d)c=31*c+a.charCodeAt(d),c%=4294967296;return c}var Da=Math.random()*2147483648|0;var Ea,Fa,Ga,Ha,Ia,Ja,Ka=(Ja="ScriptEngine"in n&&n.ScriptEngine()=="JScript")?n.ScriptEngineMajorVersion()+"."+n.ScriptEngineMinorVersion()+"."+n.ScriptEngineBuildVersion():"0";function La(a,c){this.v=Ja?[]:"";a!=i&&this.append.apply(this,arguments)}Ja?(La.prototype.bb=0,La.prototype.append=function(a,c,d){c==i?this.v[this.bb++]=a:(this.v.push.apply(this.v,arguments),this.bb=this.v.length);return this}):La.prototype.append=function(a,c,d){this.v+=a;if(c!=i)for(var e=1;e<arguments.length;e++)this.v+=arguments[e];return this};La.prototype.clear=function(){Ja?this.bb=this.v.length=0:this.v=""};
La.prototype.toString=function(){if(Ja){var a=this.v.join("");this.clear();a&&this.append(a);return a}else return this.v};var Ma;function Na(){}Na.prototype.zb=!1;Na.prototype.ca=function(){if(!this.zb)this.zb=!0,this.g()};Na.prototype.g=function(){};var Oa=Array.prototype,Pa=Oa.indexOf?function(a,c,d){return Oa.indexOf.call(a,c,d)}:function(a,c,d){d=d==i?0:d<0?Math.max(0,a.length+d):d;if(q(a))return!q(c)||c.length!=1?-1:a.indexOf(c,d);for(;d<a.length;d++)if(d in a&&a[d]===c)return d;return-1},Qa=Oa.forEach?function(a,c,d){Oa.forEach.call(a,c,d)}:function(a,c,d){for(var e=a.length,f=q(a)?a.split(""):a,g=0;g<e;g++)g in f&&c.call(d,f[g],g,a)},Ra=Oa.map?function(a,c,d){return Oa.map.call(a,c,d)}:function(a,c,d){for(var e=a.length,f=Array(e),g=q(a)?
a.split(""):a,j=0;j<e;j++)j in g&&(f[j]=c.call(d,g[j],j,a));return f};function Sa(a){return Oa.concat.apply(Oa,arguments)}function Ta(a){if(da(a))return Sa(a);else{for(var c=[],d=0,e=a.length;d<e;d++)c[d]=a[d];return c}}function Ua(a,c,d){return arguments.length<=2?Oa.slice.call(a,c):Oa.slice.call(a,c,d)};function Va(){return n.navigator?n.navigator.userAgent:i}Ia=Ha=Ga=Fa=Ea=!1;var Wa;if(Wa=Va()){var Xa=n.navigator;Ea=Wa.indexOf("Opera")==0;Fa=!Ea&&Wa.indexOf("MSIE")!=-1;Ha=(Ga=!Ea&&Wa.indexOf("WebKit")!=-1)&&Wa.indexOf("Mobile")!=-1;Ia=!Ea&&!Ga&&Xa.product=="Gecko"}var Ya=Ea,t=Fa,Za=Ia,$a=Ga,ab=Ha,bb=n.navigator,cb=(bb&&bb.platform||"").indexOf("Mac")!=-1,db;
a:{var eb="",fb;if(Ya&&n.opera)var gb=n.opera.version,eb=typeof gb=="function"?gb():gb;else if(Za?fb=/rv\:([^\);]+)(\)|;)/:t?fb=/MSIE\s+([^\);]+)(\)|;)/:$a&&(fb=/WebKit\/(\S+)/),fb)var hb=fb.exec(Va()),eb=hb?hb[1]:"";if(t){var ib,jb=n.document;ib=jb?jb.documentMode:h;if(ib>parseFloat(eb)){db=String(ib);break a}}db=eb}var kb={};function lb(a){return kb[a]||(kb[a]=Aa(db,a)>=0)};!t||lb("9");t&&lb("8");function mb(a,c){this.type=a;this.currentTarget=this.target=c}s(mb,Na);mb.prototype.g=function(){delete this.type;delete this.target;delete this.currentTarget};mb.prototype.va=!1;mb.prototype.Ya=!0;var nb=new Function("a","return a");function ob(a,c){a&&this.Ja(a,c)}s(ob,mb);m=ob.prototype;m.target=i;m.relatedTarget=i;m.offsetX=0;m.offsetY=0;m.clientX=0;m.clientY=0;m.screenX=0;m.screenY=0;m.button=0;m.keyCode=0;m.charCode=0;m.ctrlKey=!1;m.altKey=!1;m.shiftKey=!1;m.metaKey=!1;m.ac=!1;m.gb=i;
m.Ja=function(a,c){var d=this.type=a.type;mb.call(this,d);this.target=a.target||a.srcElement;this.currentTarget=c;var e=a.relatedTarget;if(e){if(Za)try{nb(e.nodeName)}catch(f){e=i}}else if(d=="mouseover")e=a.fromElement;else if(d=="mouseout")e=a.toElement;this.relatedTarget=e;this.offsetX=a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(d=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.ac=cb?a.metaKey:a.ctrlKey;this.state=a.state;this.gb=a;delete this.Ya;delete this.va};m.g=function(){ob.k.g.call(this);this.relatedTarget=this.currentTarget=this.target=this.gb=i};function pb(){}var qb=0;m=pb.prototype;m.key=0;m.wa=!1;m.sb=!1;m.Ja=function(a,c,d,e,f,g){ga(a)?this.Cb=!0:a&&a.handleEvent&&ga(a.handleEvent)?this.Cb=!1:b(Error("Invalid listener argument"));this.ta=a;this.Gb=c;this.src=d;this.type=e;this.capture=!!f;this.Sa=g;this.sb=!1;this.key=++qb;this.wa=!1};m.handleEvent=function(a){return this.Cb?this.ta.call(this.Sa||this.src,a):this.ta.handleEvent.call(this.ta,a)};function rb(a,c){this.Db=c;this.ea=[];a>this.Db&&b(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var d=0;d<a;d++)this.ea.push(this.I?this.I():{})}s(rb,Na);rb.prototype.I=i;rb.prototype.yb=i;rb.prototype.getObject=function(){return this.ea.length?this.ea.pop():this.I?this.I():{}};function sb(a,c){a.ea.length<a.Db?a.ea.push(c):tb(a,c)}function tb(a,c){if(a.yb)a.yb(c);else if(ha(c))if(ga(c.ca))c.ca();else for(var d in c)delete c[d]}
rb.prototype.g=function(){rb.k.g.call(this);for(var a=this.ea;a.length;)tb(this,a.pop());delete this.ea};var ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb;
(function(){function a(){return{f:0,u:0}}function c(){return[]}function d(){function a(c){return j.call(a.src,a.key,c)}return a}function e(){return new pb}function f(){return new ob}var g=Ja&&!(Aa(Ka,"5.7")>=0),j;zb=function(a){j=a};if(g){ub=function(){return l.getObject()};vb=function(a){sb(l,a)};wb=function(){return o.getObject()};xb=function(a){sb(o,a)};yb=function(){return r.getObject()};Ab=function(){sb(r,d())};Bb=function(){return x.getObject()};Cb=function(a){sb(x,a)};Db=function(){return F.getObject()};
Eb=function(a){sb(F,a)};var l=new rb(0,600);l.I=a;var o=new rb(0,600);o.I=c;var r=new rb(0,600);r.I=d;var x=new rb(0,600);x.I=e;var F=new rb(0,600);F.I=f}else ub=a,vb=ca,wb=c,xb=ca,yb=d,Ab=ca,Bb=e,Cb=ca,Db=f,Eb=ca})();function Fb(a,c,d){for(var e in a)c.call(d,a[e],e,a)}function Gb(a){var c={},d;for(d in a)c[d]=a[d];return c}var Hb=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];function Ib(a,c){for(var d,e,f=1;f<arguments.length;f++){e=arguments[f];for(d in e)a[d]=e[d];for(var g=0;g<Hb.length;g++)d=Hb[g],Object.prototype.hasOwnProperty.call(e,d)&&(a[d]=e[d])}};var Jb={},u={},Kb={},Lb={};
function Mb(a,c,d,e,f){if(c)if(da(c)){for(var g=0;g<c.length;g++)Mb(a,c[g],d,e,f);return i}else{var e=!!e,j=u;c in j||(j[c]=ub());j=j[c];e in j||(j[e]=ub(),j.f++);var j=j[e],l=ia(a),o;j.u++;if(j[l]){o=j[l];for(g=0;g<o.length;g++)if(j=o[g],j.ta==d&&j.Sa==f){if(j.wa)break;return o[g].key}}else o=j[l]=wb(),j.f++;g=yb();g.src=a;j=Bb();j.Ja(d,g,a,c,e,f);d=j.key;g.key=d;o.push(j);Jb[d]=j;Kb[l]||(Kb[l]=wb());Kb[l].push(j);a.addEventListener?(a==n||!a.cb)&&a.addEventListener(c,g,e):a.attachEvent(c in Lb?
Lb[c]:Lb[c]="on"+c,g);return d}else b(Error("Invalid event type"))}function Nb(a,c,d,e,f){if(da(c))for(var g=0;g<c.length;g++)Nb(a,c[g],d,e,f);else if(e=!!e,a=Ob(a,c,e))for(g=0;g<a.length;g++)if(a[g].ta==d&&a[g].capture==e&&a[g].Sa==f){Pb(a[g].key);break}}
function Pb(a){if(Jb[a]){var c=Jb[a];if(!c.wa){var d=c.src,e=c.type,f=c.Gb,g=c.capture;d.removeEventListener?(d==n||!d.cb)&&d.removeEventListener(e,f,g):d.detachEvent&&d.detachEvent(e in Lb?Lb[e]:Lb[e]="on"+e,f);d=ia(d);f=u[e][g][d];if(Kb[d]){var j=Kb[d],l=Pa(j,c);l>=0&&Oa.splice.call(j,l,1);j.length==0&&delete Kb[d]}c.wa=!0;f.Eb=!0;Qb(e,g,d,f);delete Jb[a]}}}
function Qb(a,c,d,e){if(!e.Wa&&e.Eb){for(var f=0,g=0;f<e.length;f++)if(e[f].wa){var j=e[f].Gb;j.src=i;Ab(j);Cb(e[f])}else f!=g&&(e[g]=e[f]),g++;e.length=g;e.Eb=!1;g==0&&(xb(e),delete u[a][c][d],u[a][c].f--,u[a][c].f==0&&(vb(u[a][c]),delete u[a][c],u[a].f--),u[a].f==0&&(vb(u[a]),delete u[a]))}}
function Rb(a){var c,d=0,e=c==i;c=!!c;if(a==i)Fb(Kb,function(a){for(var f=a.length-1;f>=0;f--){var g=a[f];if(e||c==g.capture)Pb(g.key),d++}});else if(a=ia(a),Kb[a])for(var a=Kb[a],f=a.length-1;f>=0;f--){var g=a[f];if(e||c==g.capture)Pb(g.key),d++}}function Ob(a,c,d){var e=u;return c in e&&(e=e[c],d in e&&(e=e[d],a=ia(a),e[a]))?e[a]:i}
function Sb(a,c,d,e,f){var g=1,c=ia(c);if(a[c]){a.u--;a=a[c];a.Wa?a.Wa++:a.Wa=1;try{for(var j=a.length,l=0;l<j;l++){var o=a[l];o&&!o.wa&&(g&=Tb(o,f)!==!1)}}finally{a.Wa--,Qb(d,e,c,a)}}return Boolean(g)}function Tb(a,c){var d=a.handleEvent(c);a.sb&&Pb(a.key);return d}
zb(function(a,c){if(!Jb[a])return!0;var d=Jb[a],e=d.type,f=u;if(!(e in f))return!0;var f=f[e],g,j;Ma===h&&(Ma=t&&!n.addEventListener);if(Ma){var l;if(!(l=c))a:{l="window.event".split(".");for(var o=n;g=l.shift();)if(o[g]!=i)o=o[g];else{l=i;break a}l=o}g=l;l=!0 in f;o=!1 in f;if(l){if(g.keyCode<0||g.returnValue!=h)return!0;a:{var r=!1;if(g.keyCode==0)try{g.keyCode=-1;break a}catch(x){r=!0}if(r||g.returnValue==h)g.returnValue=!0}}r=Db();r.Ja(g,this);g=!0;try{if(l){for(var F=wb(),T=r.currentTarget;T;T=
T.parentNode)F.push(T);j=f[!0];j.u=j.f;for(var ua=F.length-1;!r.va&&ua>=0&&j.u;ua--)r.currentTarget=F[ua],g&=Sb(j,F[ua],e,!0,r);if(o){j=f[!1];j.u=j.f;for(ua=0;!r.va&&ua<F.length&&j.u;ua++)r.currentTarget=F[ua],g&=Sb(j,F[ua],e,!1,r)}}else g=Tb(d,r)}finally{if(F)F.length=0,xb(F);r.ca();Eb(r)}return g}e=new ob(c,this);try{g=Tb(d,e)}finally{e.ca()}return g});function Ub(a){this.fa=a}s(Ub,Na);var Vb=new rb(0,100),Wb=[];function Xb(a,c,d,e){da(d)||(Wb[0]=d,d=Wb);for(var f=0;f<d.length;f++){var g=a,j=Mb(c,d[f],e||a,!1,a.fa||a);g.t?g.t[j]=!0:g.X?(g.t=Vb.getObject(),g.t[g.X]=!0,g.X=i,g.t[j]=!0):g.X=j}}
function Yb(a,c,d,e,f,g){if(a.X||a.t)if(da(d))for(var j=0;j<d.length;j++)Yb(a,c,d[j],e,f,g);else{a:{e=e||a;g=g||a.fa||a;f=!!f;if(c=Ob(c,d,f))for(d=0;d<c.length;d++)if(c[d].ta==e&&c[d].capture==f&&c[d].Sa==g){c=c[d];break a}c=i}if(c)if(c=c.key,Pb(c),a.t)a=a.t,c in a&&delete a[c];else if(a.X==c)a.X=i}}function Zb(a){if(a.t){for(var c in a.t)Pb(c),delete a.t[c];sb(Vb,a.t);a.t=i}else a.X&&Pb(a.X)}Ub.prototype.g=function(){Ub.k.g.call(this);Zb(this)};Ub.prototype.handleEvent=function(){b(Error("EventHandler.handleEvent not implemented"))};var $b,ac=!t||lb("9");!Za&&!t||t&&lb("9")||Za&&lb("1.9.1");t&&lb("9");function bc(a,c){var d;d=(d=a.className)&&typeof d.split=="function"?d.split(/\s+/):[];var e=Ua(arguments,1),f;f=d;for(var g=0,j=0;j<e.length;j++)Pa(f,e[j])>=0||(f.push(e[j]),g++);f=g==e.length;a.className=d.join(" ");return f};function cc(a,c){this.width=a;this.height=c}m=cc.prototype;m.Qa=function(){return new cc(this.width,this.height)};m.toString=function(){return"("+this.width+" x "+this.height+")"};m.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};m.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};m.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
m.scale=function(a){this.width*=a;this.height*=a;return this};function dc(a){return q(a)?document.getElementById(a):a}function ec(a,c){Fb(c,function(c,e){e=="style"?a.style.cssText=c:e=="class"?a.className=c:e=="for"?a.htmlFor=c:e in fc?a.setAttribute(fc[e],c):a[e]=c})}var fc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function gc(a,c,d,e){function f(d){d&&c.appendChild(q(d)?a.createTextNode(d):d)}for(;e<d.length;e++){var g=d[e];ea(g)&&!(ha(g)&&g.nodeType>0)?Qa(hc(g)?Ta(g):g,f):f(g)}}function ic(a){for(var c;c=a.firstChild;)a.removeChild(c)}function jc(a){a&&a.parentNode&&a.parentNode.removeChild(a)}function hc(a){if(a&&typeof a.length=="number")if(ha(a))return typeof a.item=="function"||typeof a.item=="string";else if(ga(a))return typeof a.item=="function";return!1}
function kc(a){this.da=a||n.document||document}m=kc.prototype;m.a=function(a){return q(a)?this.da.getElementById(a):a};m.B=function(a,c,d){var e=this.da,f=arguments,g=f[0],j=f[1];if(!ac&&j&&(j.name||j.type)){g=["<",g];j.name&&g.push(' name="',qa(j.name),'"');if(j.type){g.push(' type="',qa(j.type),'"');var l={};Ib(l,j);j=l;delete j.type}g.push(">");g=g.join("")}g=e.createElement(g);if(j)q(j)?g.className=j:da(j)?bc.apply(i,[g].concat(j)):ec(g,j);f.length>2&&gc(e,g,f,2);return g};m.createElement=function(a){return this.da.createElement(a)};
m.createTextNode=function(a){return this.da.createTextNode(a)};m.appendChild=function(a,c){a.appendChild(c)};m.append=function(a,c){gc(a.nodeType==9?a:a.ownerDocument||a.document,a,arguments,1)};function lc(){}s(lc,Na);m=lc.prototype;m.cb=!0;m.Xa=i;m.ob=function(a){this.Xa=a};m.addEventListener=function(a,c,d,e){Mb(this,a,c,d,e)};m.removeEventListener=function(a,c,d,e){Nb(this,a,c,d,e)};
m.dispatchEvent=function(a){var c=a.type||a,d=u;if(c in d){if(q(a))a=new mb(a,this);else if(a instanceof mb)a.target=a.target||this;else{var e=a,a=new mb(c,this);Ib(a,e)}var e=1,f,d=d[c],c=!0 in d,g;if(c){f=[];for(g=this;g;g=g.Xa)f.push(g);g=d[!0];g.u=g.f;for(var j=f.length-1;!a.va&&j>=0&&g.u;j--)a.currentTarget=f[j],e&=Sb(g,f[j],a.type,!0,a)&&a.Ya!=!1}if(!1 in d)if(g=d[!1],g.u=g.f,c)for(j=0;!a.va&&j<f.length&&g.u;j++)a.currentTarget=f[j],e&=Sb(g,f[j],a.type,!1,a)&&a.Ya!=!1;else for(f=this;!a.va&&
f&&g.u;f=f.Xa)a.currentTarget=f,e&=Sb(g,f,a.type,!1,a)&&a.Ya!=!1;a=Boolean(e)}else a=!0;return a};m.g=function(){lc.k.g.call(this);Rb(this);this.Xa=i};function mc(a){return a*Math.PI/180};function nc(a,c,d,e,f,g){arguments.length==6?this.setTransform(a,c,d,e,f,g):arguments.length!=0?b(Error("Insufficient matrix parameters")):(this.K=this.M=1,this.D=this.L=this.Z=this.$=0)}m=nc.prototype;m.Qa=function(){return new nc(this.K,this.D,this.L,this.M,this.Z,this.$)};m.setTransform=function(a,c,d,e,f,g){(!fa(a)||!fa(c)||!fa(d)||!fa(e)||!fa(f)||!fa(g))&&b(Error("Invalid transform parameters"));this.K=a;this.D=c;this.L=d;this.M=e;this.Z=f;this.$=g;return this};
m.scale=function(a,c){this.K*=a;this.D*=a;this.L*=c;this.M*=c;return this};m.translate=function(a,c){this.Z+=a*this.K+c*this.L;this.$+=a*this.D+c*this.M;return this};m.rotate=function(a,c,d){var e=new nc,f=Math.cos(a),a=Math.sin(a),c=e.setTransform(f,a,-a,f,c-c*f+d*a,d-c*a-d*f),d=this.K,e=this.L;this.K=c.K*d+c.D*e;this.L=c.L*d+c.M*e;this.Z+=c.Z*d+c.$*e;d=this.D;e=this.M;this.D=c.K*d+c.D*e;this.M=c.L*d+c.M*e;this.$+=c.Z*d+c.$*e;return this};
m.toString=function(){return"matrix("+[this.K,this.D,this.L,this.M,this.Z,this.$].join(",")+")"};function v(a,c){this.b=a;this.U=c;this.cb=!1}s(v,lc);m=v.prototype;m.U=i;m.b=i;m.Lb=i;m.a=k("b");m.addEventListener=function(a,c,d,e){Mb(this.b,a,c,d,e)};m.removeEventListener=function(a,c,d,e){Nb(this.b,a,c,d,e)};m.g=function(){v.k.g.call(this);Rb(this.b)};function w(a,c,d,e){v.call(this,a,c);this.pb=d;this.U.nb(this,d);this.fill=e;this.U.mb(this,e)}s(w,v);w.prototype.fill=i;w.prototype.pb=i;w.prototype.Rb=k("fill");w.prototype.Sb=k("pb");function oc(a,c,d,e){w.call(this,a,c,d,e)}s(oc,w);function pc(a,c){v.call(this,a,c)}s(pc,v);function qc(a,c){v.call(this,a,c)}s(qc,v);function rc(a,c,d,e){w.call(this,a,c,d,e)}s(rc,w);function sc(a,c,d,e){w.call(this,a,c,d,e)}s(sc,w);function tc(a,c){v.call(this,a,c)}s(tc,pc);tc.prototype.clear=function(){ic(this.a())};function uc(a,c,d,e){w.call(this,a,c,d,e)}s(uc,oc);uc.prototype.lb=function(a,c){vc(this.a(),{cx:a,cy:c})};function wc(a,c,d,e){w.call(this,a,c,d,e)}s(wc,sc);function xc(a,c,d,e){w.call(this,a,c,d,e)}s(xc,rc);xc.prototype.Za=function(a){vc(this.a(),{d:yc(a)})};function zc(a,c){v.call(this,a,c)}s(zc,qc);function Ac(){return this.b=this.U.J.a(this.V)||this.b}function Bc(a,c){this.V=a.id;v.call(this,a,c)}s(Bc,pc);Bc.prototype.a=Ac;Bc.prototype.clear=function(){ic(this.a())};function Cc(a,c,d,e,f,g,j,l){this.V=a.id;w.call(this,a,c,j,l);this.Pb=d;this.Qb=e;this.Hb=f;this.Jb=g}s(Cc,oc);Cc.prototype.a=Ac;Cc.prototype.lb=function(a,c){this.Pb=a;this.Qb=c;Dc(this.a(),a-this.Hb,c-this.Jb,this.Hb*2,this.Jb*2)};function Ec(a,c,d,e){this.V=a.id;w.call(this,a,c,d,e)}s(Ec,sc);Ec.prototype.a=Ac;
function Fc(a,c,d,e){this.V=a.id;w.call(this,a,c,d,e)}s(Fc,rc);Fc.prototype.a=Ac;Fc.prototype.Za=function(a){var c=this.a(),a=Gc(a);Hc?c.path=a:c.setAttribute("path",a)};function Ic(a,c){this.V=a.id;v.call(this,a,c)}s(Ic,qc);Ic.prototype.a=Ac;function y(){this.j=[];this.f=[];this.F=[]}y.prototype.oa=i;y.prototype.m=i;y.prototype.ya=!0;var Jc=[2,2,6,6,0];m=y.prototype;m.clear=function(){this.j.length=0;this.f.length=0;this.F.length=0;delete this.oa;delete this.m;delete this.ya;return this};m.moveTo=function(a,c){this.j[this.j.length-1]==0?this.F.length-=2:(this.j.push(0),this.f.push(1));this.F.push(a,c);this.m=this.oa=[a,c];return this};
m.lineTo=function(a){var c=this.j[this.j.length-1];c==i&&b(Error("Path cannot start with lineTo"));c!=1&&(this.j.push(1),this.f.push(0));for(c=0;c<arguments.length;c+=2){var d=arguments[c],e=arguments[c+1];this.F.push(d,e)}this.f[this.f.length-1]+=c/2;this.m=[d,e];return this};
m.ub=function(a){var c=this.j[this.j.length-1];c==i&&b(Error("Path cannot start with curve"));c!=2&&(this.j.push(2),this.f.push(0));for(c=0;c<arguments.length;c+=6){var d=arguments[c+4],e=arguments[c+5];this.F.push(arguments[c],arguments[c+1],arguments[c+2],arguments[c+3],d,e)}this.f[this.f.length-1]+=c/6;this.m=[d,e];return this};m.close=function(){var a=this.j[this.j.length-1];a==i&&b(Error("Path cannot start with close"));if(a!=4)this.j.push(4),this.f.push(1),this.m=this.oa;return this};
m.arcTo=function(a,c,d,e){var f=this.m[0]-a*Math.cos(mc(d))+a*Math.cos(mc(d+e)),g=this.m[1]-c*Math.sin(mc(d))+c*Math.sin(mc(d+e));this.j.push(3);this.f.push(1);this.F.push(a,c,d,e,f,g);this.ya=!1;this.m=[f,g];return this};
m.Mb=function(a,c,d,e){var f=this.m[0]-a*Math.cos(mc(d)),g=this.m[1]-c*Math.sin(mc(d)),j=mc(e),e=Math.ceil(Math.abs(j)/Math.PI*2);j/=e;for(var d=mc(d),l=0;l<e;l++){var o=Math.cos(d),r=Math.sin(d),x=4/3*Math.sin(j/2)/(1+Math.cos(j/2)),F=f+(o-x*r)*a,T=g+(r+x*o)*c;d+=j;o=Math.cos(d);r=Math.sin(d);this.ub(F,T,f+(o+x*r)*a,g+(r-x*o)*c,f+o*a,g+r*c)}return this};function Kc(a,c){for(var d=a.F,e=0,f=0,g=a.j.length;f<g;f++){var j=a.j[f],l=Jc[j]*a.f[f];c(j,d.slice(e,e+l));e+=l}}
m.Qa=function(){var a=new this.constructor;a.j=this.j.concat();a.f=this.f.concat();a.F=this.F.concat();a.oa=this.oa&&this.oa.concat();a.m=this.m&&this.m.concat();a.ya=this.ya;return a};var Lc={};Lc[0]=y.prototype.moveTo;Lc[1]=y.prototype.lineTo;Lc[4]=y.prototype.close;Lc[2]=y.prototype.ub;Lc[3]=y.prototype.Mb;function Mc(a){if(a.ya)return a.Qa();var c=new y;Kc(a,function(a,e){Lc[a].apply(c,e)});return c};function Nc(a){v.call(this,i,a);this.w=[]}s(Nc,pc);Nc.prototype.clear=function(){if(this.w.length)this.w.length=0,Oc(this.U)};Nc.prototype.appendChild=function(a){this.w.push(a)};Nc.prototype.C=function(){for(var a=0,c=this.w.length;a<c;a++)Pc(this.U,this.w[a])};function Qc(a,c,d,e,f,g,j,l){w.call(this,a,c,j,l);this.vb=d;this.wb=e;this.Ib=f;this.Kb=g;this.aa=new y;Rc(this);this.Fb=new Sc(i,c,this.aa,j,l)}s(Qc,oc);
function Rc(a){a.aa.clear();a.aa.moveTo(a.vb+a.Ib*Math.cos(mc(0)),a.wb+a.Kb*Math.sin(mc(0)));a.aa.arcTo(a.Ib,a.Kb,0,360);a.aa.close()}Qc.prototype.lb=function(a,c){this.vb=a;this.wb=c;Rc(this);this.Fb.Za(this.aa)};Qc.prototype.C=function(a){this.Fb.C(a)};function Tc(a,c,d,e,f,g,j,l){w.call(this,a,c,j,l);this.za=d;this.Aa=e;this.Na=f;this.Ia=g}s(Tc,sc);Tc.prototype.ra=!1;
Tc.prototype.C=function(a){this.ra=!0;a.beginPath();a.moveTo(this.za,this.Aa);a.lineTo(this.za,this.Aa+this.Ia);a.lineTo(this.za+this.Na,this.Aa+this.Ia);a.lineTo(this.za+this.Na,this.Aa);a.closePath()};function Sc(a,c,d,e,f){w.call(this,a,c,e,f);this.Za(d)}s(Sc,rc);Sc.prototype.ra=!1;Sc.prototype.Za=function(a){this.aa=a.ya?a:Mc(a);this.ra&&Oc(this.U)};
Sc.prototype.C=function(a){this.ra=!0;a.beginPath();Kc(this.aa,function(c,d){switch(c){case 0:a.moveTo(d[0],d[1]);break;case 1:for(var e=0;e<d.length;e+=2)a.lineTo(d[e],d[e+1]);break;case 2:for(e=0;e<d.length;e+=6)a.bezierCurveTo(d[e],d[e+1],d[e+2],d[e+3],d[e+4],d[e+5]);break;case 3:b(Error("Canvas paths cannot contain arcs"));case 4:a.closePath()}})};function Uc(a,c,d,e,f,g,j){v.call(this,a,c);this.za=d;this.Aa=e;this.Na=f;this.Ia=g;this.dc=j}s(Uc,qc);Uc.prototype.ra=!1;
Uc.prototype.C=function(a){this.Bb?(this.Na&&this.Ia&&a.drawImage(this.Bb,this.za,this.Aa,this.Na,this.Ia),this.ra=!0):(a=new Image,a.onload=na(this.Tb,this,a),a.src=this.dc)};Uc.prototype.Tb=function(a){this.Bb=a;Oc(this.U)};function Vc(a,c,d){c instanceof cc?(d=c.height,c=c.width):d==h&&b(Error("missing height argument"));a.style.width=Wc(c);a.style.height=Wc(d)}function Wc(a){typeof a=="number"&&(a=Math.round(a)+"px");return a}
function Xc(a){var c;a:{c=a.nodeType==9?a:a.ownerDocument||a.document;if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,i))){c=c.display||c.getPropertyValue("display");break a}c=""}if((c||(a.currentStyle?a.currentStyle.display:i)||a.style.display)!="none")return new cc(a.offsetWidth,a.offsetHeight);c=a.style;var d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";var g=a.offsetWidth,a=a.offsetHeight;c.display=d;
c.position=f;c.visibility=e;return new cc(g,a)};function Yc(){}(function(a){a.Ab=function(){return a.Xb||(a.Xb=new a)}})(Yc);Yc.prototype.$b=0;Yc.Ab();function Zc(a){this.J=a||$b||($b=new kc);this.cc=$c}s(Zc,lc);Zc.prototype.Wb=Yc.Ab();var $c=i;m=Zc.prototype;m.V=i;m.n=!1;m.b=i;m.cc=i;m.Zb=i;m.ua=i;m.w=i;m.Ca=i;m.gc=!1;m.a=k("b");m.ob=function(a){this.ua&&this.ua!=a&&b(Error("Method not supported"));Zc.k.ob.call(this,a)};m.B=function(){this.b=this.J.createElement("div")};m.T=function(){this.n=!0;ad(this,function(a){!a.n&&a.a()&&a.T()})};m.Ga=function(){ad(this,function(a){a.n&&a.Ga()});this.Ra&&Zb(this.Ra);this.n=!1};
m.g=function(){Zc.k.g.call(this);this.n&&this.Ga();this.Ra&&(this.Ra.ca(),delete this.Ra);ad(this,function(a){a.ca()});!this.gc&&this.b&&jc(this.b);this.ua=this.Zb=this.b=this.Ca=this.w=i};function ad(a,c){a.w&&Qa(a.w,c,h)}
m.removeChild=function(a,c){if(a){var d=q(a)?a:a.V||(a.V=":"+(a.Wb.$b++).toString(36)),a=this.Ca&&d?(d in this.Ca?this.Ca[d]:h)||i:i;if(d&&a){var e=this.Ca;d in e&&delete e[d];d=this.w;e=Pa(d,a);e>=0&&Oa.splice.call(d,e,1);c&&(a.Ga(),a.b&&jc(a.b));d=a;d==i&&b(Error("Unable to set parent component"));d.ua=i;Zc.k.ob.call(d,i)}}a||b(Error("Child is not in parent component"));return a};function bd(a,c,d,e,f){Zc.call(this,f);this.width=a;this.height=c;this.q=d||i;this.qa=e||i}s(bd,Zc);bd.prototype.l=i;bd.prototype.S=0;bd.prototype.ba=0;bd.prototype.r=function(){return this.n?Xc(this.a()):fa(this.width)&&fa(this.height)?new cc(this.width,this.height):i};function cd(a){var c=a.r();return c?c.width/(a.q?new cc(a.q,a.qa):a.r()).width:0};function dd(a,c,d,e,f){if(!t&&(!$a||!lb("525")))return!0;if(cb&&f)return ed(a);if(f&&!e)return!1;if(!d&&(c==17||c==18))return!1;if(t&&e&&c==a)return!1;switch(a){case 13:return!0;case 27:return!$a}return ed(a)}
function ed(a){if(a>=48&&a<=57)return!0;if(a>=96&&a<=106)return!0;if(a>=65&&a<=90)return!0;if($a&&a==0)return!0;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}};function fd(a,c){if(a)this.Va&&this.detach(),this.b=a,this.Ua=Mb(this.b,"keypress",this,c),this.ib=Mb(this.b,"keydown",this.Ub,c,this),this.Va=Mb(this.b,"keyup",this.Vb,c,this)}s(fd,lc);m=fd.prototype;m.b=i;m.Ua=i;m.ib=i;m.Va=i;m.Y=-1;m.W=-1;
var gd={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},hd={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},id={61:187,59:186},jd=t||$a&&lb("525");m=fd.prototype;
m.Ub=function(a){if($a&&(this.Y==17&&!a.ctrlKey||this.Y==18&&!a.altKey))this.W=this.Y=-1;jd&&!dd(a.keyCode,this.Y,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):this.W=Za&&a.keyCode in id?id[a.keyCode]:a.keyCode};m.Vb=function(){this.W=this.Y=-1};
m.handleEvent=function(a){var c=a.gb,d,e;t&&a.type=="keypress"?(d=this.W,e=d!=13&&d!=27?c.keyCode:0):$a&&a.type=="keypress"?(d=this.W,e=c.charCode>=0&&c.charCode<63232&&ed(d)?c.charCode:0):Ya?(d=this.W,e=ed(d)?c.keyCode:0):(d=c.keyCode||this.W,e=c.charCode||0,cb&&e==63&&!d&&(d=191));var f=d,g=c.keyIdentifier;d?d>=63232&&d in gd?f=gd[d]:d==25&&a.shiftKey&&(f=9):g&&g in hd&&(f=hd[g]);a=f==this.Y;this.Y=f;c=new kd(f,e,a,c);try{this.dispatchEvent(c)}finally{c.ca()}};m.a=k("b");
m.detach=function(){if(this.Ua)Pb(this.Ua),Pb(this.ib),Pb(this.Va),this.Va=this.ib=this.Ua=i;this.b=i;this.W=this.Y=-1};m.g=function(){fd.k.g.call(this);this.detach()};function kd(a,c,d,e){e&&this.Ja(e,h);this.type="key";this.keyCode=a;this.charCode=c;this.repeat=d}s(kd,ob);function ld(){};function md(a){this.rb=1;this.A=a};function nd(a,c){this.Ta=a||1;this.Ma=c||od;this.ab=na(this.ec,this);this.jb=oa()}s(nd,lc);nd.prototype.enabled=!1;var od=n.window;m=nd.prototype;m.ha=i;m.ec=function(){if(this.enabled){var a=oa()-this.jb;if(a>0&&a<this.Ta*0.8)this.ha=this.Ma.setTimeout(this.ab,this.Ta-a);else if(this.dispatchEvent(pd),this.enabled)this.ha=this.Ma.setTimeout(this.ab,this.Ta),this.jb=oa()}};m.start=function(){this.enabled=!0;if(!this.ha)this.ha=this.Ma.setTimeout(this.ab,this.Ta),this.jb=oa()};
m.stop=function(){this.enabled=!1;if(this.ha)this.Ma.clearTimeout(this.ha),this.ha=i};m.g=function(){nd.k.g.call(this);this.stop();delete this.Ma};var pd="tick";function qd(a,c,d){ga(a)?d&&(a=na(a,d)):a&&typeof a.handleEvent=="function"?a=na(a.handleEvent,a):b(Error("Invalid listener argument"));return c>2147483647?-1:od.setTimeout(a,c||0)};function rd(a,c){this.A=a;this.Ka=c||1}s(rd,ld);function sd(a,c,d,e,f){bd.call(this,a,c,d,e,f);this.fa=new Ub(this)}s(sd,bd);var Hc=document.documentMode&&document.documentMode>=8;function z(a){return Math.round(parseFloat(a.toString())*100)}function td(a,c){var d=a.J.createElement("g_vml_:"+c);d.id="goog_"+Da++;return d}function ud(a){if(Hc&&a.n)a.a().innerHTML=a.a().innerHTML}sd.prototype.o=function(a,c){(c||this.l).a().appendChild(a.a());ud(this)};
sd.prototype.mb=function(a,c){var d=a.a();d.fillcolor="";for(var e=0;e<d.childNodes.length;e++){var f=d.childNodes[e];f.tagName=="fill"&&d.removeChild(f)}c instanceof rd?c.A=="transparent"?d.filled=!1:c.Ka!=1?(d.filled=!0,e=td(this,"fill"),e.opacity=Math.round(c.Ka*100)+"%",e.color=c.A,d.appendChild(e)):(d.filled=!0,d.fillcolor=c.A):d.filled=!1;ud(this)};
sd.prototype.nb=function(a,c){var d=a.a();if(c){d.stroked=!0;var e=c.rb;q(e)&&e.indexOf("px")==-1?e=parseFloat(e):e*=cd(this);var f=d.getElementsByTagName("stroke")[0];e<1?(f=f||td(this,"stroke"),f.opacity=e,f.pc="1px",f.color=c.A,d.appendChild(f)):(f&&d.removeChild(f),d.strokecolor=c.A,d.strokeweight=e+"px")}else d.stroked=!1;ud(this)};
function Dc(a,c,d,e,f){var g=a.style;g.position="absolute";g.left=Math.round((parseFloat(c.toString())-0.5)*100)+"px";g.top=Math.round((parseFloat(d.toString())-0.5)*100)+"px";g.width=z(e)+"px";g.height=z(f)+"px";if(a.tagName=="shape")a.coordsize=z(e)+" "+z(f)}try{eval("document.namespaces")}catch(vd){}m=sd.prototype;
m.B=function(){var a=this.J.da;if(!a.namespaces.g_vml_)Hc?a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML"):a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml"),a.createStyleSheet().cssText="g_vml_\\:*{behavior:url(#default#VML)}";var a=this.width,c=this.height,d=this.J.B("div",{style:"overflow:hidden;position:relative;width:"+(q(a)&&pa(a)?a:parseFloat(a.toString())+"px")+";height:"+(q(c)&&pa(c)?c:parseFloat(c.toString())+"px")});this.b=d;var e=td(this,"group"),f=e.style;
f.position="absolute";f.left=f.top=0;f.width=this.width;f.height=this.height;e.coordsize=this.q?z(this.q)+" "+z(this.qa):z(a)+" "+z(c);e.coordorigin=this.S!==h?z(this.S)+" "+z(this.ba):"0 0";d.appendChild(e);this.l=new Bc(e,this);Mb(d,"resize",na(this.hb,this))};
m.hb=function(){var a=Xc(this.a()),c=this.l.a().style;if(a.width)c.width=a.width+"px",c.height=a.height+"px";else{for(a=this.a();a&&a.currentStyle&&a.currentStyle.display!="none";)a=a.parentNode;a&&a.currentStyle&&Xb(this.fa,a,"propertychange",this.hb)}this.dispatchEvent("resize")};m.r=function(){var a=this.a();return new cc(a.style.pixelWidth||a.offsetWidth||1,a.style.pixelHeight||a.offsetHeight||1)};m.clear=function(){this.l.clear()};
m.Fa=function(a,c,d,e,f,g,j){var l=td(this,"oval");Dc(l,a-d,c-e,d*2,e*2);a=new Cc(l,this,a,c,d,e,f,g);this.o(a,j);return a};m.fb=function(a,c,d,e,f,g,j){var l=td(this,"rect");Dc(l,a,c,d,e);a=new Ec(l,this,f,g);this.o(a,j);return a};m.drawImage=function(a,c,d,e,f,g){var j=td(this,"image");Dc(j,a,c,d,e);Hc?j.src=f:j.setAttribute("src",f);a=new Ic(j,this);this.o(a,g);return a};
m.h=function(a,c,d,e){var f=td(this,"shape"),g=this.q?new cc(this.q,this.qa):this.r();Dc(f,0,0,g.width,g.height);a=Gc(a);Hc?f.path=a:f.setAttribute("path",a);c=new Fc(f,this,c,d);this.o(c,e);return c};
function Gc(a){var c=[];Kc(a,function(a,e){switch(a){case 0:c.push("m");Array.prototype.push.apply(c,Ra(e,z));break;case 1:c.push("l");Array.prototype.push.apply(c,Ra(e,z));break;case 2:c.push("c");Array.prototype.push.apply(c,Ra(e,z));break;case 4:c.push("x");break;case 3:var f=e[2]+e[3];c.push("ae",z(e[4]-e[0]*Math.cos(mc(f))),z(e[5]-e[1]*Math.sin(mc(f))),z(e[0]),z(e[1]),Math.round(e[2]*-65536),Math.round(e[3]*-65536))}});return c.join(" ")}m.T=function(){sd.k.T.call(this);this.hb();ud(this)};
m.g=function(){this.l=i;sd.k.g.call(this)};function wd(a,c,d,e,f){bd.call(this,a,c,d,e,f)}s(wd,bd);m=wd.prototype;m.mb=function(){Oc(this)};m.nb=function(){Oc(this)};function xd(a,c){var d=a.getContext();d.save();var e=c.Lb?c.Lb.Qa():new nc,f=e.Z,g=e.$;(f||g)&&d.translate(f,g);(e=e.D)&&d.rotate(Math.asin(e))}m.B=function(){var a=this.J.B("div",{style:"position:relative;overflow:hidden"});this.b=a;this.Ba=this.J.B("canvas");a.appendChild(this.Ba);this.Yb=this.l=new Nc(this);this.bc=0;yd(this)};
m.getContext=function(){this.a()||this.B();if(!this.pa)this.pa=this.Ba.getContext("2d"),this.pa.save();return this.pa};m.r=function(){var a=this.width,c=this.height,d=q(a)&&a.indexOf("%")!=-1,e=q(c)&&c.indexOf("%")!=-1;if(!this.n&&(d||e))return i;var f,g;if(d)f=this.a().parentNode,g=Xc(f),a=parseFloat(a)*g.width/100;e&&(f=f||this.a().parentNode,g=g||Xc(f),c=parseFloat(c)*g.height/100);return new cc(a,c)};
function yd(a){Vc(a.a(),a.width,a.height);var c=a.r();if(c)Vc(a.Ba,c.width,c.height),a.Ba.width=c.width,a.Ba.height=c.height,a.pa=i}m.reset=function(){var a=this.getContext();a.restore();var c=this.r();c.width&&c.height&&a.clearRect(0,0,c.width,c.height);a.save()};m.clear=function(){this.reset();this.l.clear();for(var a=this.a();a.childNodes.length>1;)a.removeChild(a.lastChild)};
function Oc(a){if(a.oc)a.nc=!0;else if(a.n){a.reset();if(a.q){var c=a.r();a.getContext().scale(c.width/a.q,c.height/a.qa)}(a.S||a.ba)&&a.getContext().translate(-a.S,-a.ba);xd(a,a.l);a.l.C(a.pa);a.getContext().restore()}}
function Pc(a,c){var d=a.getContext();xd(a,c);if(!c.Rb||!c.Sb)c.C(d);else{var e=c.fill;if(e)if(e instanceof rd){if(e.Ka!=0)d.globalAlpha=e.Ka,d.fillStyle=e.A,c.C(d),d.fill(),d.globalAlpha=1}else{var f=d.createLinearGradient(e.jc(),e.lc(),e.kc(),e.mc());f.addColorStop(0,e.hc());f.addColorStop(1,e.ic());d.fillStyle=f;c.C(d);d.fill()}if(e=c.pb)c.C(d),d.strokeStyle=e.A,e=e.rb,q(e)&&e.indexOf("px")!=-1&&(e=parseFloat(e)/cd(a)),d.lineWidth=e,d.stroke()}a.getContext().restore()}
m.o=function(a,c){c=c||this.l;c.appendChild(a);this.n&&!this.bc&&!(c!=this.l&&c!=this.Yb)&&Pc(this,a)};m.Fa=function(a,c,d,e,f,g,j){a=new Qc(i,this,a,c,d,e,f,g);this.o(a,j);return a};m.fb=function(a,c,d,e,f,g,j){a=new Tc(i,this,a,c,d,e,f,g);this.o(a,j);return a};m.drawImage=function(a,c,d,e,f,g){a=new Uc(i,this,a,c,d,e,f);this.o(a,g);return a};m.h=function(a,c,d,e){a=new Sc(i,this,a,c,d);this.o(a,e);return a};m.g=function(){this.pa=i;wd.k.g.call(this)};
m.T=function(){var a=this.r();wd.k.T.call(this);a||(yd(this),this.dispatchEvent("resize"));Oc(this)};function zd(a,c,d,e,f){bd.call(this,a,c,d,e,f);this.xb={};this.qb=$a&&!lb(526);this.fa=new Ub(this)}var Ad;s(zd,bd);function Bd(a,c,d){a=a.J.da.createElementNS("http://www.w3.org/2000/svg",c);d&&vc(a,d);return a}function vc(a,c){for(var d in c)a.setAttribute(d,c[d])}m=zd.prototype;m.o=function(a,c){(c||this.l).a().appendChild(a.a())};m.mb=function(a,c){var d=a.a();c instanceof rd?(d.setAttribute("fill",c.A),d.setAttribute("fill-opacity",c.Ka)):d.setAttribute("fill","none")};
m.nb=function(a,c){var d=a.a();if(c){d.setAttribute("stroke",c.A);var e=c.rb;q(e)&&e.indexOf("px")!=-1?d.setAttribute("stroke-width",parseFloat(e)/cd(this)):d.setAttribute("stroke-width",e)}else d.setAttribute("stroke","none")};
m.B=function(){var a=Bd(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),c=Bd(this,"g");this.eb=Bd(this,"defs");this.l=new tc(c,this);a.appendChild(this.eb);a.appendChild(c);this.b=a;if(this.q||this.S||this.ba)this.a().setAttribute("preserveAspectRatio","none"),this.qb?this.$a():this.a().setAttribute("viewBox",this.S+" "+this.ba+" "+(this.q?this.q+" "+this.qa:""))};
m.$a=function(){if(this.n&&(this.q||this.S||!this.ba)){var a=this.r();if(a.width==0)this.a().style.visibility="hidden";else{this.a().style.visibility="";var c=-this.S,d=-this.ba,e=a.width/this.q,a=a.height/this.qa;this.l.a().setAttribute("transform","scale("+e+" "+a+") translate("+c+" "+d+")")}}};
m.r=function(){if(!Za)return this.n?Xc(this.a()):zd.k.r.call(this);var a=this.width,c=this.height,d=q(a)&&a.indexOf("%")!=-1,e=q(c)&&c.indexOf("%")!=-1;if(!this.n&&(d||e))return i;var f,g;if(d)f=this.a().parentNode,g=Xc(f),a=parseFloat(a)*g.width/100;e&&(f=f||this.a().parentNode,g=g||Xc(f),c=parseFloat(c)*g.height/100);return new cc(a,c)};m.clear=function(){this.l.clear();ic(this.eb);this.xb={}};
m.Fa=function(a,c,d,e,f,g,j){a=Bd(this,"ellipse",{cx:a,cy:c,rx:d,ry:e});f=new uc(a,this,f,g);this.o(f,j);return f};m.fb=function(a,c,d,e,f,g,j){a=Bd(this,"rect",{x:a,y:c,width:d,height:e});f=new wc(a,this,f,g);this.o(f,j);return f};m.drawImage=function(a,c,d,e,f,g){a=Bd(this,"image",{x:a,y:c,width:d,height:e,"image-rendering":"optimizeQuality",preserveAspectRatio:"none"});a.setAttributeNS("http://www.w3.org/1999/xlink","href",f);f=new zc(a,this);this.o(f,g);return f};
m.h=function(a,c,d,e){a=Bd(this,"path",{d:yc(a)});c=new xc(a,this,c,d);this.o(c,e);return c};function yc(a){var c=[];Kc(a,function(a,e){switch(a){case 0:c.push("M");Array.prototype.push.apply(c,e);break;case 1:c.push("L");Array.prototype.push.apply(c,e);break;case 2:c.push("C");Array.prototype.push.apply(c,e);break;case 3:var f=e[3];c.push("A",e[0],e[1],0,Math.abs(f)>180?1:0,f>0?1:0,e[4],e[5]);break;case 4:c.push("Z")}});return c.join(" ")}
m.T=function(){var a=this.r();zd.k.T.call(this);a||this.dispatchEvent("resize");if(this.qb){var a=this.width,c=this.height;typeof a=="string"&&a.indexOf("%")!=-1&&typeof c=="string"&&c.indexOf("%")!=-1&&Xb(this.fa,Cd(),pd,this.$a);this.$a()}};m.Ga=function(){zd.k.Ga.call(this);this.qb&&Yb(this.fa,Cd(),pd,this.$a)};m.g=function(){delete this.xb;delete this.eb;delete this.l;zd.k.g.call(this)};function Cd(){Ad||(Ad=new nd(400),Ad.start());return Ad};function Dd(a,c,d,e,f){a=t&&!lb("9")?new sd(a,c,d,e,f):$a&&(!lb("420")||ab)?new wd(a,c,d,e,f):new zd(a,c,d,e,f);a.B();return a};function A(a){return a!=i&&a!==!1}function Ed(a,c){var d=a[p.call(i,c)];return A(d)?d:(d=a._,A(d)?d:!1)}function Fd(a){return Array.prototype.slice.call(a)}function Gd(a){return Array.prototype.slice.call(arguments)}
var B=function Hd(c){return A(A(c)?c.ja:c)?c.ja(c):function(){var d=Hd[p.call(i,c)];return A(d)?d:Hd._}().call(i,c)},Jd=function Id(c,d){return A(A(c)?c.N:c)?c.N(c,d):function(){var d=Id[p.call(i,c)];return A(d)?d:Id._}().call(i,c,d)},C=function(){function a(a,c,g){return A(A(a)?a.Pa:a)?a.Pa(a,c,g):function(){var c=d[p.call(i,a)];return A(c)?c:d._}().call(i,a,c,g)}function c(a,c){return A(A(a)?a.Pa:a)?a.Pa(a,c):function(){var c=d[p.call(i,a)];return A(c)?c:d._}().call(i,a,c)}var d=i;return d=function(d,
f,g){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return a.call(this,d,f,g)}b("Invalid arity: "+arguments.length)}}(),Kd={},Md=function Ld(c){return A(A(c)?c.la:c)?c.la(c):function(){var d=Ld[p.call(i,c)];return A(d)?d:Ld._}().call(i,c)},Od=function Nd(c){return A(A(c)?c.ma:c)?c.ma(c):function(){var d=Nd[p.call(i,c)];return A(d)?d:Nd._}().call(i,c)},D=function(){function a(a,c,g){return A(A(a)?a.ka:a)?a.ka(a,c,g):function(){var c=d[p.call(i,a)];return A(c)?c:d._}().call(i,a,c,g)}
function c(a,c){return A(A(a)?a.ka:a)?a.ka(a,c):function(){var c=d[p.call(i,a)];return A(c)?c:d._}().call(i,a,c)}var d=i;return d=function(d,f,g){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return a.call(this,d,f,g)}b("Invalid arity: "+arguments.length)}}(),Qd=function Pd(c,d,e){return A(A(c)?c.Oa:c)?c.Oa(c,d,e):function(){var d=Pd[p.call(i,c)];return A(d)?d:Pd._}().call(i,c,d,e)},Rd={},Sd={},Ud=function Td(c){return A(A(c)?c.Nb:c)?c.state:function(){var d=Td[p.call(i,c)];return A(d)?
d:Td._}().call(i,c)},Vd={},Xd=function Wd(c){return A(A(c)?c.Q:c)?c.e:function(){var d=Wd[p.call(i,c)];return A(d)?d:Wd._}().call(i,c)},Zd=function Yd(c,d){return A(A(c)?c.R:c)?c.R(c,d):function(){var d=Yd[p.call(i,c)];return A(d)?d:Yd._}().call(i,c,d)},$d=function(){function a(a,c,g){return A(A(a)?a.Da:a)?a.Da(a,c,g):function(){var c=d[p.call(i,a)];return A(c)?c:d._}().call(i,a,c,g)}function c(a,c){return A(A(a)?a.Da:a)?a.Da(a,c):function(){var c=d[p.call(i,a)];return A(c)?c:d._}().call(i,a,c)}var d=
i;return d=function(d,f,g){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return a.call(this,d,f,g)}b("Invalid arity: "+arguments.length)}}(),be=function ae(c,d){return A(A(c)?c.s:c)?c.s(c,d):function(){var d=ae[p.call(i,c)];return A(d)?d:ae._}().call(i,c,d)},de=function ce(c){return A(A(c)?c.O:c)?c.O(c):function(){var d=ce[p.call(i,c)];return A(d)?d:ce._}().call(i,c)},fe=function ee(c){return A(A(c)?c.H:c)?c.H(c):function(){var d=ee[p.call(i,c)];return A(d)?d:ee._}().call(i,c)},ge=
{},he={},je=function ie(c,d){return A(A(c)?c.z:c)?c.z(c,d):function(){var d=ie[p.call(i,c)];return A(d)?d:ie._}().call(i,c,d)};function ke(a,c){return a===c}function E(a,c){return be.call(i,a,c)}function le(a){return ke.call(i,a,i)}be["null"]=function(a,c){return le.call(i,c)};Jd["null"]=function(a,c){return G.call(i,c)};Kd["null"]=!0;Md["null"]=ba(i);Od["null"]=function(){return G.call(i)};Zd["null"]=ba(i);Rd["null"]=!0;
C["null"]=function(){return function(a,c,d){switch(arguments.length){case 2:return i;case 3:return d}b("Invalid arity: "+arguments.length)}}();Vd["null"]=!0;Xd["null"]=ba(i);$d["null"]=function(){return function(a,c,d){switch(arguments.length){case 2:return c.call(i);case 3:return d}b("Invalid arity: "+arguments.length)}}();de["null"]=ba(0);B["null"]=ba(0);Qd["null"]=function(a,c,d){return me.call(i,c,d)};
D["null"]=function(){return function(a,c,d){switch(arguments.length){case 2:return i;case 3:return d}b("Invalid arity: "+arguments.length)}}();Date.prototype.s=function(a,c){return ke.call(i,a.toString,c.toString)};de.number=aa();be.number=function(a,c){return ke.call(i,a,c)};function H(a){return a+1}function ne(a,c){return a<c}
var oe=function(){return function(a,c,d,e){switch(arguments.length){case 2:var f;a:if(A(E.call(i,0,B.call(i,a))))f=c.call(i);else for(var g=C.call(i,a,0),j=1;;)if(A(ne.call(i,j,B.call(i,a))))g=c.call(i,g,C.call(i,a,j)),j=H.call(i,j);else{f=g;break a}return f;case 3:a:{f=d;for(j=0;;)if(A(ne.call(i,j,B.call(i,a))))f=c.call(i,f,C.call(i,a,j)),j=H.call(i,j);else{g=f;break a}}return g;case 4:a:{f=d;for(g=e;;)if(A(ne.call(i,g,B.call(i,a))))f=c.call(i,f,C.call(i,a,g)),g=H.call(i,g);else{j=f;break a}}return j}b("Invalid arity: "+
arguments.length)}}();function pe(a,c){this.ia=a;this.sa=c}m=pe.prototype;m.Da=function(){return function(a,c,d){switch(arguments.length){case 2:return oe.call(i,this.ia,c,this.ia[this.sa],H.call(i,this.sa));case 3:return oe.call(i,this.ia,c,d,this.sa)}b("Invalid arity: "+arguments.length)}}();m.s=function(a,c){return qe.call(i,a,c)};m.na=!0;m.Ea=!0;m.la=function(){return this.ia[this.sa]};m.ma=function(){return A(ne.call(i,H.call(i,this.sa),B.call(i,this.ia)))?new pe(this.ia,H.call(i,this.sa)):G.call(i)};
m.H=aa();function re(a,c){return A(E.call(i,0,B.call(i,a)))?i:new pe(a,c)}function I(a,c){return re.call(i,a,c)}$d.array=function(){return function(a,c,d){switch(arguments.length){case 2:return oe.call(i,a,c);case 3:return oe.call(i,a,c,d)}b("Invalid arity: "+arguments.length)}}();D.array=function(){return function(a,c,d){switch(arguments.length){case 2:return a[c];case 3:return C.call(i,a,c,d)}b("Invalid arity: "+arguments.length)}}();
C.array=function(){return function(a,c,d){switch(arguments.length){case 2:return A(ne.call(i,c,a.length))?a[c]:i;case 3:return A(ne.call(i,c,a.length))?a[c]:d}b("Invalid arity: "+arguments.length)}}();B.array=function(a){return a.length};fe.array=function(a){return I.call(i,a,0)};function J(a){return A(a)?fe.call(i,a):i}function K(a){a=J.call(i,a);return A(a)?Md.call(i,a):i}function L(a){return Od.call(i,J.call(i,a))}function M(a){return A(a)?J.call(i,L.call(i,a)):i}
function se(a){return K.call(i,M.call(i,a))}function te(a){return M.call(i,M.call(i,a))}B._=function(a){for(var a=J.call(i,a),c=0;;)if(A(a))a=M.call(i,a),c=H.call(i,c);else return c};be._=function(a,c){return ke.call(i,a,c)};function ue(a){return A(a)?!1:!0}
var ve=function(){function a(a,e,f){for(var g=I(Array.prototype.slice.call(arguments,2),0);;)if(A(g))var j=c.call(i,a,e),l=K.call(i,g),g=M.call(i,g),a=j,e=l;else return c.call(i,a,e)}var c=i,c=function(c,e,f){switch(arguments.length){case 2:return Jd.call(i,c,e);default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.i=2;c.c=function(c){var e=K(c),f=K(M(c)),c=L(M(c));return a.call(i,e,f,c)};return c}();function we(a){return B.call(i,a)}
var N=function(){return function(a,c,d){switch(arguments.length){case 2:return C.call(i,a,c);case 3:return C.call(i,a,c,d)}b("Invalid arity: "+arguments.length)}}(),xe=function(){return function(a,c,d){switch(arguments.length){case 2:return D.call(i,a,c);case 3:return D.call(i,a,c,d)}b("Invalid arity: "+arguments.length)}}(),ye=function(){function a(a,e,f,g){for(var j=I(Array.prototype.slice.call(arguments,3),0);;){var l=c.call(i,a,e,f);if(A(j))var o=K.call(i,j),r=se.call(i,j),j=te.call(i,j),a=l,
e=o,f=r;else return l}}var c=i,c=function(c,e,f,g){switch(arguments.length){case 3:return Qd.call(i,c,e,f);default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.i=3;c.c=function(c){var e=K(c),f=K(M(c)),g=K(M(M(c))),c=L(M(M(c)));return a.call(i,e,f,g,c)};return c}();function ze(a,c){return Zd.call(i,a,c)}function Ae(a){return Xd.call(i,a)}function Be(a){return de.call(i,a)}function Ce(a){return A(A(a)?a.na:a)?!0:Ed.call(i,ge,a)}
function De(a){return A(le.call(i,a))?!1:A(A(a)?a.tb:a)?!0:Ed.call(i,Rd,a)}function Ee(a){return A(A(a)?a.Ob:a)?!0:Ed.call(i,Sd,a)}function Fe(){return{}}function Ge(a){var c=Gd.call(i);Fb.call(i,a,function(a,e){return c.push(e)});return c}var He=Fe.call(i);function Ie(a){return h===a}function Je(a){return A(le.call(i,a))?!1:A(A(a)?a.Ea:a)?!0:Ed.call(i,Kd,a)}function Ke(a){return A(a)?!0:!1}
function Le(a){var c=q.call(i,a);return A(c)?ue.call(i,function(){var c=E.call(i,a.charAt(0),"\ufdd0");return A(c)?c:E.call(i,a.charAt(0),"\ufdd1")}()):c}function Me(a){var c=q.call(i,a);return A(c)?E.call(i,a.charAt(0),"\ufdd0"):c}function Ne(a){var c=q.call(i,a);return A(c)?E.call(i,a.charAt(0),"\ufdd1"):c}function Oe(a,c){return A(ke.call(i,D.call(i,a,c,He),He))?!1:!0}
var Pe=function(){return function(a,c,d){switch(arguments.length){case 2:return $d.call(i,c,a);case 3:return $d.call(i,d,a,c)}b("Invalid arity: "+arguments.length)}}(),Qe=function(){return function(a,c,d){switch(arguments.length){case 2:var e=J.call(i,c);return A(e)?Pe.call(i,a,K.call(i,e),M.call(i,e)):a.call(i);case 3:a:for(var f=c,g=J.call(i,d);;)if(A(g))f=a.call(i,f,K.call(i,g)),g=M.call(i,g);else{e=f;break a}return e}b("Invalid arity: "+arguments.length)}}();
$d._=function(){return function(a,c,d){switch(arguments.length){case 2:return Qe.call(i,c,a);case 3:return Qe.call(i,c,d,a)}b("Invalid arity: "+arguments.length)}}();
var O=function(){function a(a,e,f){var g=I(Array.prototype.slice.call(arguments,2),0);return Pe.call(i,c,c.call(i,a,e),g)}var c=i,c=function(c,e,f){switch(arguments.length){case 0:return 0;case 1:return c;case 2:return c+e;default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.i=2;c.c=function(c){var e=K(c),f=K(M(c)),c=L(M(c));return a.call(i,e,f,c)};return c}(),Re=function(){function a(a,e,f){var g=I(Array.prototype.slice.call(arguments,2),0);return Pe.call(i,c,c.call(i,
a,e),g)}var c=i,c=function(c,e,f){switch(arguments.length){case 1:return-c;case 2:return c-e;default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.i=2;c.c=function(c){var e=K(c),f=K(M(c)),c=L(M(c));return a.call(i,e,f,c)};return c}(),Se=function(){function a(a,e,f){var g=I(Array.prototype.slice.call(arguments,2),0);return Pe.call(i,c,c.call(i,a,e),g)}var c=i,c=function(c,e,f){switch(arguments.length){case 0:return 1;case 1:return c;case 2:return c*e;default:return a.apply(this,
arguments)}b("Invalid arity: "+arguments.length)};c.i=2;c.c=function(c){var e=K(c),f=K(M(c)),c=L(M(c));return a.call(i,e,f,c)};return c}(),Te=function(){function a(a,e,f){var g=I(Array.prototype.slice.call(arguments,2),0);return Pe.call(i,c,c.call(i,a,e),g)}var c=i,c=function(c,e,f){switch(arguments.length){case 1:return 1/c;case 2:return c/e;default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.i=2;c.c=function(c){var e=K(c),f=K(M(c)),c=L(M(c));return a.call(i,e,f,c)};return c}(),
Ue=function(){function a(a,e,f){for(var g=I(Array.prototype.slice.call(arguments,2),0);;)if(A(c.call(i,a,e)))if(A(M.call(i,g)))var j=e,l=K.call(i,g),g=M.call(i,g),a=j,e=l;else return c.call(i,e,K.call(i,g));else return!1}var c=i,c=function(c,e,f){switch(arguments.length){case 1:return!0;case 2:return c<e;default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.i=2;c.c=function(c){var e=K(c),f=K(M(c)),c=L(M(c));return a.call(i,e,f,c)};return c}(),Ve=function(){function a(a,e,
f){for(var g=I(Array.prototype.slice.call(arguments,2),0);;)if(A(c.call(i,a,e)))if(A(M.call(i,g)))var j=e,l=K.call(i,g),g=M.call(i,g),a=j,e=l;else return c.call(i,e,K.call(i,g));else return!1}var c=i,c=function(c,e,f){switch(arguments.length){case 1:return!0;case 2:return c<=e;default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.i=2;c.c=function(c){var e=K(c),f=K(M(c)),c=L(M(c));return a.call(i,e,f,c)};return c}(),We=function(){function a(a,e,f){for(var g=I(Array.prototype.slice.call(arguments,
2),0);;)if(A(c.call(i,a,e)))if(A(M.call(i,g)))var j=e,l=K.call(i,g),g=M.call(i,g),a=j,e=l;else return c.call(i,e,K.call(i,g));else return!1}var c=i,c=function(c,e,f){switch(arguments.length){case 1:return!0;case 2:return c>e;default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.i=2;c.c=function(c){var e=K(c),f=K(M(c)),c=L(M(c));return a.call(i,e,f,c)};return c}();function Xe(a){return Re.call(i,a,1)}function Ye(a,c){return a%c}function Ze(a,c){return a^c}
function $e(a,c){return a<<c}function af(a,c){return a>>c}function bf(a){return Ue.call(i,0,a)}function cf(a,c){for(var d=c,e=J.call(i,a);;)if(A(function(){var a=e;return A(a)?bf.call(i,d):a}()))var f=Xe.call(i,d),g=M.call(i,e),d=f,e=g;else return e}C._=function(){return function(a,c,d){switch(arguments.length){case 2:var e;var f=cf.call(i,a,c);A(f)?e=K.call(i,f):b("Index out of bounds");return e;case 3:return e=cf.call(i,a,c),A(e)?K.call(i,e):d}b("Invalid arity: "+arguments.length)}}();
var df=function(){function a(a,e){var f=I(Array.prototype.slice.call(arguments,1),0);return function(a,d){for(;;)if(A(d))var e=a.append(c.call(i,K.call(i,d))),f=M.call(i,d),a=e,d=f;else return c.call(i,a)}.call(i,new La(c.call(i,a)),f)}var c=i,c=function(c,e){switch(arguments.length){case 0:return"";case 1:return A(le.call(i,c))?"":c.toString();default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.i=1;c.c=function(c){var e=K(c),c=L(c);return a.call(i,e,c)};return c}(),ef=
function(){return function(a,c,d){switch(arguments.length){case 2:return a.substring(c);case 3:return a.substring(c,d)}b("Invalid arity: "+arguments.length)}}();function qe(a,c){return Ke.call(i,A(Ce.call(i,c))?function(){for(var d=J.call(i,a),e=J.call(i,c);;)if(A(le.call(i,d)))return le.call(i,e);else if(A(le.call(i,e)))return!1;else if(A(E.call(i,K.call(i,d),K.call(i,e))))d=M.call(i,d),e=M.call(i,e);else return A("\ufdd0'else")?!1:i}():i)}
function ff(a,c){return Ze.call(i,a,O.call(i,c,2654435769,$e.call(i,a,6),af.call(i,a,2)))}function gf(a){return Pe.call(i,function(a,d){return ff.call(i,a,Be.call(i,d))},Be.call(i,K.call(i,a)),M.call(i,a))}function hf(a,c,d,e){this.e=a;this.Ha=c;this.xa=d;this.count=e}m=hf.prototype;m.s=function(a,c){return qe.call(i,a,c)};m.N=function(a,c){return new hf(this.e,c,a,H.call(i,this.count))};m.Ea=!0;m.la=k("Ha");m.ma=k("xa");m.H=aa();m.R=function(a,c){return new hf(c,this.Ha,this.xa,this.count)};
m.P=!0;m.Q=k("e");m.O=function(a){return gf.call(i,a)};m.ja=k("count");m.na=!0;function jf(a){this.e=a}m=jf.prototype;m.s=function(a,c){return qe.call(i,a,c)};m.N=function(a,c){return new hf(this.e,c,i,1)};m.Ea=!0;m.la=ba(i);m.ma=ba(i);m.H=ba(i);m.R=function(a,c){return new jf(c)};m.P=!0;m.Q=k("e");m.O=function(a){return gf.call(i,a)};m.ja=ba(0);m.na=!0;var kf=new jf(i);function lf(a){return Pe.call(i,ve,kf,a)}
function G(a){var c=I(Array.prototype.slice.call(arguments,0),0);return Pe.call(i,ve,kf,lf.call(i,c))}function mf(a,c,d){this.e=a;this.Ha=c;this.xa=d}m=mf.prototype;m.H=aa();m.O=function(a){return gf.call(i,a)};m.s=function(a,c){return qe.call(i,a,c)};m.na=!0;m.N=function(a,c){return new mf(i,c,a)};m.Ea=!0;m.la=k("Ha");m.ma=function(){return A(le.call(i,this.xa))?kf:this.xa};m.P=!0;m.Q=k("e");m.R=function(a,c){return new mf(c,this.Ha,this.xa)};function P(a,c){return new mf(i,a,c)}
$d.string=function(){return function(a,c,d){switch(arguments.length){case 2:return oe.call(i,a,c);case 3:return oe.call(i,a,c,d)}b("Invalid arity: "+arguments.length)}}();D.string=function(){return function(a,c,d){switch(arguments.length){case 2:return C.call(i,a,c);case 3:return C.call(i,a,c,d)}b("Invalid arity: "+arguments.length)}}();
C.string=function(){return function(a,c,d){switch(arguments.length){case 2:return A(Ue.call(i,c,B.call(i,a)))?a.charAt(c):i;case 3:return A(Ue.call(i,c,B.call(i,a)))?a.charAt(c):d}b("Invalid arity: "+arguments.length)}}();B.string=function(a){return a.length};fe.string=function(a){return re.call(i,a,0)};de.string=function(a){return Ca.call(i,a)};
String.prototype.call=function(){return function(a,c,d){switch(arguments.length){case 2:return xe.call(i,c,this.toString());case 3:return xe.call(i,c,this.toString(),d)}b("Invalid arity: "+arguments.length)}}();function nf(a){var c=a.x;return A(a.kb)?c:(a.x=c.call(i),a.kb=!0,a.x)}function Q(a,c,d){this.e=a;this.kb=c;this.x=d}m=Q.prototype;m.H=function(a){return J.call(i,nf.call(i,a))};m.O=function(a){return gf.call(i,a)};m.s=function(a,c){return qe.call(i,a,c)};m.na=!0;
m.N=function(a,c){return P.call(i,c,a)};m.Ea=!0;m.la=function(a){return K.call(i,nf.call(i,a))};m.ma=function(a){return L.call(i,nf.call(i,a))};m.P=!0;m.Q=k("e");m.R=function(a,c){return new Q(c,this.kb,this.x)};function of(a){for(var c=Gd.call(i);;)if(A(J.call(i,a)))c.push(K.call(i,a)),a=M.call(i,a);else return c}function pf(a,c){for(var d=a,e=c,f=0;;)if(A(function(){var a=bf.call(i,e);return A(a)?J.call(i,d):a}()))var g=M.call(i,d),j=Xe.call(i,e),f=H.call(i,f),d=g,e=j;else return f}
var rf=function qf(c){return A(le.call(i,c))?i:A(le.call(i,M.call(i,c)))?J.call(i,K.call(i,c)):A("\ufdd0'else")?P.call(i,K.call(i,c),qf.call(i,M.call(i,c))):i},sf=function(){function a(a,c,d){var e=I(Array.prototype.slice.call(arguments,2),0);return function x(a,c){return new Q(i,!1,function(){var d=J.call(i,a);return A(d)?P.call(i,K.call(i,d),x.call(i,L.call(i,d),c)):A(c)?x.call(i,K.call(i,c),M.call(i,c)):i})}.call(i,f.call(i,a,c),e)}function c(a,c){return new Q(i,!1,function(){var d=J.call(i,a);
return A(d)?P.call(i,K.call(i,d),f.call(i,L.call(i,d),c)):c})}function d(a){return new Q(i,!1,function(){return a})}function e(){return new Q(i,!1,ba(i))}var f=i,f=function(f,j,l){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,f);case 2:return c.call(this,f,j);default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};f.i=2;f.c=function(c){var d=K(c),e=K(M(c)),c=L(M(c));return a.call(i,d,e,c)};return f}(),tf=function(){function a(a,c,f,g,j){var l=
I(Array.prototype.slice.call(arguments,4),0);return P.call(i,a,P.call(i,c,P.call(i,f,P.call(i,g,rf.call(i,l)))))}var c=i,c=function(c,e,f,g,j){switch(arguments.length){case 1:return J.call(i,c);case 2:return P.call(i,c,e);case 3:return P.call(i,c,P.call(i,e,f));case 4:return P.call(i,c,P.call(i,e,P.call(i,f,g)));default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.i=4;c.c=function(c){var e=K(c),f=K(M(c)),g=K(M(M(c))),j=K(M(M(M(c)))),c=L(M(M(M(c))));return a.call(i,e,f,g,
j,c)};return c}(),uf=function(){function a(a,c,f,g,j,l){var o=I(Array.prototype.slice.call(arguments,5),0),o=P.call(i,c,P.call(i,f,P.call(i,g,P.call(i,j,rf.call(i,o))))),r=a.i;return A(a.c)?A(Ve.call(i,pf.call(i,o,r),r))?a.apply(a,of.call(i,o)):a.c(o):a.apply(a,of.call(i,o))}var c=i,c=function(c,e,f,g,j,l){switch(arguments.length){case 2:var o=c,r=e,x=o.i;return A(o.c)?A(Ve.call(i,pf.call(i,r,x),x))?o.apply(o,of.call(i,r)):o.c(r):o.apply(o,of.call(i,r));case 3:return o=c,r=tf.call(i,e,f),x=o.i,A(o.c)?
A(Ve.call(i,pf.call(i,r,x),x))?o.apply(o,of.call(i,r)):o.c(r):o.apply(o,of.call(i,r));case 4:return o=c,r=tf.call(i,e,f,g),x=o.i,A(o.c)?A(Ve.call(i,pf.call(i,r,x),x))?o.apply(o,of.call(i,r)):o.c(r):o.apply(o,of.call(i,r));case 5:return o=c,r=tf.call(i,e,f,g,j),x=o.i,A(o.c)?A(Ve.call(i,pf.call(i,r,x),x))?o.apply(o,of.call(i,r)):o.c(r):o.apply(o,of.call(i,r));default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.i=5;c.c=function(c){var e=K(c),f=K(M(c)),g=K(M(M(c))),j=K(M(M(M(c)))),
l=K(M(M(M(M(c))))),c=L(M(M(M(M(c)))));return a.call(i,e,f,g,j,l,c)};return c}();function vf(a,c){for(;;)if(A(le.call(i,J.call(i,c))))return!0;else if(A(a.call(i,K.call(i,c))))var d=a,e=M.call(i,c),a=d,c=e;else return A("\ufdd0'else")?!1:i}function wf(a){return a}
var xf=function(){function a(a,c,d,e,r){var x=I(Array.prototype.slice.call(arguments,4),0);return f.call(i,function(c){return uf.call(i,a,c)},function T(a){return new Q(i,!1,function(){var c=f.call(i,J,a);return A(vf.call(i,wf,c))?P.call(i,f.call(i,K,c),T.call(i,f.call(i,L,c))):i})}.call(i,ve.call(i,x,e,d,c)))}function c(a,c,d,e){return new Q(i,!1,function(){var r=J.call(i,c),x=J.call(i,d),F=J.call(i,e);return A(A(r)?A(x)?F:x:r)?P.call(i,a.call(i,K.call(i,r),K.call(i,x),K.call(i,F)),f.call(i,a,L.call(i,
r),L.call(i,x),L.call(i,F))):i})}function d(a,c,d){return new Q(i,!1,function(){var e=J.call(i,c),r=J.call(i,d);return A(A(e)?r:e)?P.call(i,a.call(i,K.call(i,e),K.call(i,r)),f.call(i,a,L.call(i,e),L.call(i,r))):i})}function e(a,c){return new Q(i,!1,function(){var d=J.call(i,c);return A(d)?P.call(i,a.call(i,K.call(i,d)),f.call(i,a,L.call(i,d))):i})}var f=i,f=function(f,j,l,o,r){switch(arguments.length){case 2:return e.call(this,f,j);case 3:return d.call(this,f,j,l);case 4:return c.call(this,f,j,l,
o);default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};f.i=4;f.c=function(c){var d=K(c),e=K(M(c)),f=K(M(M(c))),r=K(M(M(M(c)))),c=L(M(M(M(c))));return a.call(i,d,e,f,r,c)};return f}(),zf=function yf(c,d){return new Q(i,!1,function(){if(A(bf.call(i,c))){var e=J.call(i,d);return A(e)?P.call(i,K.call(i,e),yf.call(i,Xe.call(i,c),L.call(i,e))):i}else return i})};
function Af(a,c){function d(a,c){for(;;){var d=J.call(i,c);if(A(function(){var c=bf.call(i,a);return A(c)?d:c}()))var j=Xe.call(i,a),l=L.call(i,d),a=j,c=l;else return d}}return new Q(i,!1,function(){return d.call(i,a,c)})}
var Bf=function(){function a(a){return new Q(i,!1,function(){return P.call(i,a,c.call(i,a))})}var c=i;return c=function(d,e){switch(arguments.length){case 1:return a.call(this,d);case 2:return zf.call(i,d,c.call(i,e))}b("Invalid arity: "+arguments.length)}}(),Cf=function(){function a(a,c,g){var j=I(Array.prototype.slice.call(arguments,2),0);return new Q(i,!1,function(){var g=xf.call(i,J,ve.call(i,j,c,a));return A(vf.call(i,wf,g))?sf.call(i,xf.call(i,K,g),uf.call(i,d,xf.call(i,L,g))):i})}function c(a,
c){return new Q(i,!1,function(){var g=J.call(i,a),j=J.call(i,c);return A(A(g)?j:g)?P.call(i,K.call(i,g),P.call(i,K.call(i,j),d.call(i,L.call(i,g),L.call(i,j)))):i})}var d=i,d=function(d,f,g){switch(arguments.length){case 2:return c.call(this,d,f);default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};d.i=2;d.c=function(c){var d=K(c),g=K(M(c)),c=L(M(c));return a.call(i,d,g,c)};return d}();function Df(a,c){return Af.call(i,1,Cf.call(i,Bf.call(i,a),c))}
function Ef(a){return function d(a,f){return new Q(i,!1,function(){var g=J.call(i,a);return A(g)?P.call(i,K.call(i,g),d.call(i,L.call(i,g),f)):A(J.call(i,f))?d.call(i,K.call(i,f),L.call(i,f)):i})}.call(i,i,a)}
var Ff=function(){function a(a,c,f){var g=I(Array.prototype.slice.call(arguments,2),0);return Ef.call(i,uf.call(i,xf,a,c,g))}var c=i,c=function(c,e,f){switch(arguments.length){case 2:return Ef.call(i,xf.call(i,c,e));default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.i=2;c.c=function(c){var e=K(c),f=K(M(c)),c=L(M(c));return a.call(i,e,f,c)};return c}(),Hf=function Gf(c,d){return new Q(i,!1,function(){var e=J.call(i,d);if(A(e)){var f=K.call(i,e),e=L.call(i,e);return A(c.call(i,
f))?P.call(i,f,Gf.call(i,c,e)):Gf.call(i,c,e)}else return i})};function If(a,c){return Pe.call(i,Jd,a,c)}
var Jf=function(){function a(a,c,g,j){return new Q(i,!1,function(){var l=J.call(i,j);if(A(l)){var o=zf.call(i,a,l);return A(E.call(i,a,we.call(i,o)))?P.call(i,o,d.call(i,a,c,g,Af.call(i,c,l))):G.call(i,zf.call(i,a,sf.call(i,o,g)))}else return i})}function c(a,c,g){return new Q(i,!1,function(){var j=J.call(i,g);if(A(j)){var l=zf.call(i,a,j);return A(E.call(i,a,we.call(i,l)))?P.call(i,l,d.call(i,a,c,Af.call(i,c,j))):i}else return i})}var d=i;return d=function(e,f,g,j){switch(arguments.length){case 2:return d.call(i,
e,e,f);case 3:return c.call(this,e,f,g);case 4:return a.call(this,e,f,g,j)}b("Invalid arity: "+arguments.length)}}(),Kf=function(){return function(a,c,d){switch(arguments.length){case 2:return Pe.call(i,xe,a,c);case 3:var e;a:for(var f=He,g=a,j=J.call(i,c);;)if(A(j))if(g=xe.call(i,g,K.call(i,j),f),A(ke.call(i,f,g))){e=d;break a}else j=M.call(i,j);else{e=g;break a}return e}b("Invalid arity: "+arguments.length)}}();function Lf(a,c){this.e=a;this.p=c}m=Lf.prototype;
m.s=function(a,c){return qe.call(i,a,c)};m.N=function(a,c){var d=Fd.call(i,this.p);d.push(c);return new Lf(this.e,d)};m.H=function(){var a=this;return A(We.call(i,a.p.length,0))?function d(e){return new Q(i,!1,function(){return A(Ue.call(i,e,a.p.length))?P.call(i,a.p[e],d.call(i,H.call(i,e))):i})}.call(i,0):i};m.Ob=!0;m.R=function(a,c){return new Lf(c,this.p)};
m.Pa=function(){function a(a,c,f){var g=this;return A(function(){var a=Ve.call(i,0,c);return A(a)?Ue.call(i,c,g.p.length):a}())?g.p[c]:f}function c(a,c){var f=this;return A(function(){var a=Ve.call(i,0,c);return A(a)?Ue.call(i,c,f.p.length):a}())?f.p[c]:i}return function(d,e,f){switch(arguments.length){case 2:return c.call(this,0,e);case 3:return a.call(this,0,e,f)}b("Invalid arity: "+arguments.length)}}();m.P=!0;m.Q=k("e");
m.Da=function(){return function(a,c,d){switch(arguments.length){case 2:return oe.call(i,this.p,c);case 3:return oe.call(i,this.p,c,d)}b("Invalid arity: "+arguments.length)}}();m.O=function(a){return gf.call(i,a)};m.ja=function(){return this.p.length};m.na=!0;m.Oa=function(a,c,d){a=Fd.call(i,this.p);a[c]=d;return new Lf(this.e,a)};m.ka=function(){return function(a,c,d){switch(arguments.length){case 2:return C.call(i,a,c,i);case 3:return C.call(i,a,c,d)}b("Invalid arity: "+arguments.length)}}();
var Mf=new Lf(i,Gd.call(i));function R(a){return new Lf(i,a)}Lf.prototype.call=function(){return function(a,c,d){switch(arguments.length){case 2:return D.call(i,this,c);case 3:return D.call(i,this,c,d)}b("Invalid arity: "+arguments.length)}}();function Nf(a){return Pe.call(i,ve,Mf,a)}function Of(a){var c=I(Array.prototype.slice.call(arguments,0),0);return Nf.call(i,c)}function Pf(){}Pf.prototype.s=ba(!1);var Qf=new Pf;
function Rf(a,c){return Ke.call(i,A(De.call(i,c))?A(E.call(i,we.call(i,a),we.call(i,c)))?vf.call(i,wf,xf.call(i,function(a){return E.call(i,xe.call(i,c,K.call(i,a),Qf),se.call(i,a))},a)):i:i)}function Sf(a,c,d){for(var e=d.length,f=0;;)if(A(Ue.call(i,f,e)))if(A(E.call(i,c,d[f])))return f;else f=O.call(i,f,a);else return i}
var Tf=function(){function a(a,c,f,g){return A(function(){var f=q.call(i,a);return A(f)?c.hasOwnProperty(a):f}())?f:g}var c=i;return c=function(d,e,f,g){switch(arguments.length){case 2:return c.call(i,d,e,!0,!1);case 4:return a.call(this,d,e,f,g)}b("Invalid arity: "+arguments.length)}}();function Uf(a,c,d){this.e=a;this.keys=c;this.La=d}m=Uf.prototype;m.s=function(a,c){return Rf.call(i,a,c)};m.N=function(a,c){return A(Ee.call(i,c))?Qd.call(i,a,C.call(i,c,0),C.call(i,c,1)):Pe.call(i,Jd,a,c)};
m.H=function(){var a=this;return A(bf.call(i,a.keys.length))?xf.call(i,function(c){return Of.call(i,c,a.La[c])},a.keys):i};m.R=function(a,c){return new Uf(c,this.keys,this.La)};m.tb=!0;m.P=!0;m.Q=k("e");m.O=function(a){return gf.call(i,a)};m.ja=function(){return this.keys.length};
m.Oa=function(a,c,d){if(A(q.call(i,c))){var a=Gb.call(i,this.La),e=a.hasOwnProperty(c);a[c]=d;return A(e)?new Uf(this.e,this.keys,a):(d=Fd.call(i,this.keys),d.push(c),new Uf(this.e,d,a))}else return ze.call(i,If.call(i,me.call(i,c,d),J.call(i,a)),this.e)};m.ka=function(){return function(a,c,d){switch(arguments.length){case 2:return D.call(i,a,c,i);case 3:return Tf.call(i,c,this.La,this.La[c],d)}b("Invalid arity: "+arguments.length)}}();Gd.call(i);function Vf(a,c){return new Uf(i,a,c)}
Uf.prototype.call=function(){return function(a,c,d){switch(arguments.length){case 2:return D.call(i,this,c);case 3:return D.call(i,this,c,d)}b("Invalid arity: "+arguments.length)}}();function Wf(a,c,d){this.e=a;this.count=c;this.ga=d}m=Wf.prototype;m.s=function(a,c){return Rf.call(i,a,c)};m.N=function(a,c){return A(Ee.call(i,c))?Qd.call(i,a,C.call(i,c,0),C.call(i,c,1)):Pe.call(i,Jd,a,c)};
m.H=function(){var a=this;if(A(bf.call(i,a.count))){var c=Ge.call(i,a.ga);return Ff.call(i,function(c){return xf.call(i,Nf,Jf.call(i,2,a.ga[c]))},c)}else return i};m.R=function(a,c){return new Wf(c,this.count,this.ga)};m.tb=!0;m.P=!0;m.Q=k("e");m.O=function(a){return gf.call(i,a)};m.ja=k("count");
m.Oa=function(a,c,d){var a=Be.call(i,c),e=this.ga[a];if(A(e)){var e=Fd.call(i,e),f=Gb.call(i,this.ga);f[a]=e;a=Sf.call(i,2,c,e);return A(a)?(e[H.call(i,a)]=d,new Wf(this.e,this.count,f)):(e.push(c,d),new Wf(this.e,H.call(i,this.count),f))}else return e=Gb.call(i,this.ga),e[a]=Gd.call(i,c,d),new Wf(this.e,H.call(i,this.count),e)};
m.ka=function(){return function(a,c,d){switch(arguments.length){case 2:return D.call(i,a,c,i);case 3:var e=this.ga[Be.call(i,c)],f=A(e)?Sf.call(i,2,c,e):i;return A(f)?e[H.call(i,f)]:d}b("Invalid arity: "+arguments.length)}}();var Xf=new Wf(i,0,Fe.call(i));function Yf(){for(var a=[R([-1,17]),R([28,17])],c=[Vf(["\ufdd0'open"],{"\ufdd0'open":i}),Vf(["\ufdd0'open"],{"\ufdd0'open":i})],d=a.length,e=0,f=Xf;;)if(A(Ue.call(i,e,d)))var g=H.call(i,e),f=ye.call(i,f,a[e],c[e]),e=g;else return f}
Wf.prototype.call=function(){return function(a,c,d){switch(arguments.length){case 2:return D.call(i,this,c);case 3:return D.call(i,this,c,d)}b("Invalid arity: "+arguments.length)}}();function me(a){for(var c=I(Array.prototype.slice.call(arguments,0),0),c=J.call(i,c),d=Xf;;)if(A(c))var e=te.call(i,c),d=ye.call(i,d,K.call(i,c),se.call(i,c)),c=e;else return d}function Zf(a){return J.call(i,xf.call(i,K,a))}me.call(i);
function $f(a){if(A(Le.call(i,a)))return a;else if(A(function(){var c=Me.call(i,a);return A(c)?c:Ne.call(i,a)}())){var c=a.lastIndexOf("/");return A(Ue.call(i,c,0))?ef.call(i,a,2):ef.call(i,a,H.call(i,c))}else return i}function ag(a){if(A(function(){var c=Me.call(i,a);return A(c)?c:Ne.call(i,a)}())){var c=a.lastIndexOf("/");return A(We.call(i,c,-1))?ef.call(i,a,2,c):i}else return"\ufdd0'else"}
var bg=function(){function a(a,d){for(;;)if(A(function(){var e=J.call(i,d);return A(e)?bf.call(i,a):e}()))var e=Xe.call(i,a),f=M.call(i,d),a=e,d=f;else return i}return function(c,d){switch(arguments.length){case 1:var e;a:for(var f=c;;)if(A(J.call(i,f)))f=M.call(i,f);else{e=i;break a}return e;case 2:return a.call(this,c,d)}b("Invalid arity: "+arguments.length)}}(),cg=function(){return function(a,c){switch(arguments.length){case 1:return bg.call(i,a),a;case 2:return bg.call(i,a,c),c}b("Invalid arity: "+
arguments.length)}}();function dg(a,c,d,e,f,g){return sf.call(i,R([c]),Ef.call(i,Df.call(i,R([d]),xf.call(i,function(c){return a.call(i,c,f)},g))),R([e]))}
var fg=function eg(c,d){return A(le.call(i,c))?G.call(i,"nil"):A(Ie.call(i,c))?G.call(i,"#<undefined>"):A("\ufdd0'else")?sf.call(i,A(function(){var e=xe.call(i,d,"\ufdd0'meta");return A(e)?(e=A(A(c)?c.P:c)?!0:Ed.call(i,Vd,c),A(e)?Ae.call(i,c):e):e}())?sf.call(i,R(["^"]),eg.call(i,Ae.call(i,c),d),R([" "])):i,A(A(A(c)?c.G:c)?!0:Ed.call(i,he,c))?je.call(i,c,d):G.call(i,"#<",df.call(i,c),">")):i};Wf.prototype.G=!0;
Wf.prototype.z=function(a,c){return dg.call(i,function(a){return dg.call(i,fg,""," ","",c,a)},"{",", ","}",c,a)};he.number=!0;je.number=function(a){return G.call(i,df.call(i,a))};pe.prototype.G=!0;pe.prototype.z=function(a,c){return dg.call(i,fg,"("," ",")",c,a)};Q.prototype.G=!0;Q.prototype.z=function(a,c){return dg.call(i,fg,"("," ",")",c,a)};he["boolean"]=!0;je["boolean"]=function(a){return G.call(i,df.call(i,a))};he.string=!0;
je.string=function(a,c){return A(Me.call(i,a))?G.call(i,df.call(i,":",function(){var c=ag.call(i,a);return A(c)?df.call(i,c,"/"):i}(),$f.call(i,a))):A(Ne.call(i,a))?G.call(i,df.call(i,function(){var c=ag.call(i,a);return A(c)?df.call(i,c,"/"):i}(),$f.call(i,a))):A("\ufdd0'else")?G.call(i,A("\ufdd0'readably".call(i,c))?za.call(i,a):a):i};Lf.prototype.G=!0;Lf.prototype.z=function(a,c){return dg.call(i,fg,"["," ","]",c,a)};hf.prototype.G=!0;
hf.prototype.z=function(a,c){return dg.call(i,fg,"("," ",")",c,a)};he.array=!0;je.array=function(a,c){return dg.call(i,fg,"#<Array [",", ","]>",c,a)};jf.prototype.G=!0;jf.prototype.z=function(){return G.call(i,"()")};mf.prototype.G=!0;mf.prototype.z=function(a,c){return dg.call(i,fg,"("," ",")",c,a)};Uf.prototype.G=!0;Uf.prototype.z=function(a,c){return dg.call(i,function(a){return dg.call(i,fg,""," ","",c,a)},"{",", ","}",c,a)};function gg(a,c,d){this.state=a;this.e=c;this.fc=d}m=gg.prototype;
m.G=!0;m.z=function(a,c){return sf.call(i,R(["#<Atom: "]),je.call(i,this.state,c),">")};m.P=!0;m.Q=k("e");m.Nb=k("state");m.s=function(a,c){return ke.call(i,a,c)};
var hg=function(){function a(a,c){var f=I(Array.prototype.slice.call(arguments,1),0),g=A(Je.call(i,f))?uf.call(i,me,f):f,f=xe.call(i,g,"\ufdd0'validator"),g=xe.call(i,g,"\ufdd0'meta");return new gg(a,g,f)}var c=i,c=function(c,e){switch(arguments.length){case 1:return new gg(c,i,i);default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.i=1;c.c=function(c){var e=K(c),c=L(c);return a.call(i,e,c)};return c}();
function ig(a,c){var d=a.fc;A(d)&&!A(d.call(i,c))&&b("Validator rejected reference state");return a.state=c}
var jg=function(){function a(a,c,f,g,j,l){var o=I(Array.prototype.slice.call(arguments,5),0);return ig.call(i,a,uf.call(i,c,a.state,f,g,j,o))}var c=i,c=function(c,e,f,g,j,l){switch(arguments.length){case 2:return ig.call(i,c,e.call(i,c.state));case 3:return ig.call(i,c,e.call(i,c.state,f));case 4:return ig.call(i,c,e.call(i,c.state,f,g));case 5:return ig.call(i,c,e.call(i,c.state,f,g,j));default:return a.apply(this,arguments)}b("Invalid arity: "+arguments.length)};c.i=5;c.c=function(c){var e=K(c),
f=K(M(c)),g=K(M(M(c))),j=K(M(M(M(c)))),l=K(M(M(M(M(c))))),c=L(M(M(M(M(c)))));return a.call(i,e,f,g,j,l,c)};return c}();function kg(a){return Ud.call(i,a)};function S(a,c){return R([a,c])}function lg(a){return xf.call(i,function(a){return Se.call(i,8,a)},a)}function mg(a,c){return xf.call(i,function(a,c){return O.call(i,a,c)},a,c)}function ng(a){return mg.call(i,R([4,4]),lg.call(i,a))}function U(a){return mg.call(i,R([0,4]),lg.call(i,a))}function og(a,c){return S.call(i,Math.floor.call(i,Te.call(i,a,8)),Math.floor.call(i,Te.call(i,c,8)))}function pg(a,c){var d=E.call(i,4,Ye.call(i,a,8));return A(d)?E.call(i,4,Ye.call(i,c,8)):d};function qg(a){return mg.call(i,R([0,0]),lg.call(i,a))}function V(a){return mg.call(i,R([4,7]),lg.call(i,a))}function rg(a){return mg.call(i,R([0,7]),lg.call(i,a))}function W(a){return mg.call(i,R([4,0]),lg.call(i,a))}function sg(a){return mg.call(i,R([7,7]),lg.call(i,a))}function tg(a){return mg.call(i,R([7,0]),lg.call(i,a))}function X(a){return mg.call(i,R([7,4]),lg.call(i,a))}function ug(a,c){return a.moveTo(K.call(i,c),se.call(i,c))}function Y(a,c){return a.lineTo(K.call(i,c),se.call(i,c))}
function Z(a,c){var d=a.m;return a.arcTo(Re.call(i,K.call(i,c),K.call(i,d)),Re.call(i,se.call(i,c),se.call(i,d)),-90,90)}function $(a,c){var d=a.m;return a.arcTo(Re.call(i,K.call(i,c),K.call(i,d)),Re.call(i,se.call(i,c),se.call(i,d)),180,-90)}
function vg(a,c,d,e){return Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,ug.call(i,new y,X.call(i,S.call(i,a,c))),U.call(i,S.call(i,d,c))),V.call(i,S.call(i,d,c))),W.call(i,S.call(i,d,e))),U.call(i,S.call(i,d,e))),X.call(i,S.call(i,a,e))),W.call(i,S.call(i,a,e))),V.call(i,S.call(i,a,c))),X.call(i,S.call(i,a,c)))}
function wg(a,c){return Z.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Z.call(i,Y.call(i,ug.call(i,new y,X.call(i,S.call(i,a,c))),U.call(i,S.call(i,O.call(i,7,a),c))),V.call(i,S.call(i,O.call(i,7,a),c))),U.call(i,S.call(i,O.call(i,7,a),O.call(i,1,c)))),X.call(i,S.call(i,O.call(i,4,a),O.call(i,1,c)))),V.call(i,S.call(i,O.call(i,4,a),O.call(i,1,c)))),W.call(i,S.call(i,O.call(i,4,a),O.call(i,4,c)))),U.call(i,S.call(i,O.call(i,4,a),O.call(i,4,c)))),
W.call(i,S.call(i,13,O.call(i,4,c)))),V.call(i,S.call(i,O.call(i,3,a),O.call(i,1,c)))),U.call(i,S.call(i,O.call(i,3,a),O.call(i,1,c)))),X.call(i,S.call(i,a,O.call(i,1,c)))),W.call(i,S.call(i,a,O.call(i,1,c)))),X.call(i,S.call(i,a,c)))}
function xg(a,c){var d=new md(c),e=new y;Y.call(i,Y.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Y.call(i,Y.call(i,ug.call(i,e,qg.call(i,S.call(i,0,16))),qg.call(i,S.call(i,5,16))),rg.call(i,S.call(i,5,12))),V.call(i,S.call(i,0,12))),U.call(i,S.call(i,0,12))),U.call(i,S.call(i,0,3))),W.call(i,S.call(i,0,3))),W.call(i,S.call(i,27,3))),X.call(i,S.call(i,27,3))),X.call(i,S.call(i,27,12))),V.call(i,S.call(i,27,12))),sg.call(i,S.call(i,22,12))),tg.call(i,S.call(i,
22,16))),tg.call(i,S.call(i,27,16)));a.h(e,d);e=new y;Y.call(i,$.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,$.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,$.call(i,Y.call(i,ug.call(i,e,U.call(i,S.call(i,0,16))),U.call(i,S.call(i,5,16))),W.call(i,S.call(i,5,16))),V.call(i,S.call(i,5,12))),U.call(i,S.call(i,5,12))),X.call(i,S.call(i,0,12))),W.call(i,S.call(i,0,12))),V.call(i,S.call(i,0,3))),X.call(i,S.call(i,
0,3))),U.call(i,S.call(i,13,3))),V.call(i,S.call(i,13,3))),W.call(i,S.call(i,13,7))),X.call(i,S.call(i,13,7))),W.call(i,S.call(i,14,7))),V.call(i,S.call(i,14,3))),X.call(i,S.call(i,14,3))),U.call(i,S.call(i,27,3))),V.call(i,S.call(i,27,3))),W.call(i,S.call(i,27,12))),U.call(i,S.call(i,27,12))),X.call(i,S.call(i,22,12))),V.call(i,S.call(i,22,12))),W.call(i,S.call(i,22,16))),X.call(i,S.call(i,22,16))),X.call(i,S.call(i,27,16)));a.h(e,d);a.h(vg.call(i,2,5,5,7),d);a.h(vg.call(i,7,5,11,7),d);a.h(vg.call(i,
16,5,20,7),d);a.h(vg.call(i,22,5,25,7),d);a.h(vg.call(i,2,9,5,10),d);a.h(vg.call(i,22,9,25,10),d);a.h(vg.call(i,7,18,8,22),d);a.h(vg.call(i,19,18,20,22),d);a.h(vg.call(i,7,24,11,25),d);a.h(vg.call(i,16,24,20,25),d);e=new y;Y.call(i,Y.call(i,Y.call(i,Y.call(i,ug.call(i,e,ng.call(i,S.call(i,10,15))),ng.call(i,S.call(i,17,15))),ng.call(i,S.call(i,17,19))),ng.call(i,S.call(i,10,19))),ng.call(i,S.call(i,10,15)));a.h(e,d);e=new y;Y.call(i,Y.call(i,Y.call(i,Y.call(i,ug.call(i,e,sg.call(i,S.call(i,10,15))),
rg.call(i,S.call(i,17,15))),qg.call(i,S.call(i,17,19))),tg.call(i,S.call(i,10,19))),sg.call(i,S.call(i,10,15)));a.h(e,d);a.h(wg.call(i,10,9),d);a.h(wg.call(i,10,21),d);a.h(wg.call(i,10,27),d);e=new y;Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,ug.call(i,e,V.call(i,S.call(i,7,9))),X.call(i,S.call(i,7,9))),U.call(i,S.call(i,8,9))),V.call(i,S.call(i,8,9))),W.call(i,S.call(i,8,12))),X.call(i,S.call(i,8,
12))),U.call(i,S.call(i,11,12))),V.call(i,S.call(i,11,12))),W.call(i,S.call(i,11,13))),U.call(i,S.call(i,11,13))),X.call(i,S.call(i,8,13))),V.call(i,S.call(i,8,13))),W.call(i,S.call(i,8,16))),U.call(i,S.call(i,8,16))),X.call(i,S.call(i,7,16))),W.call(i,S.call(i,7,16))),V.call(i,S.call(i,7,9)));a.h(e,d);e=new y;Y.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,ug.call(i,e,V.call(i,S.call(i,19,9))),X.call(i,
S.call(i,19,9))),U.call(i,S.call(i,20,9))),V.call(i,S.call(i,20,9))),W.call(i,S.call(i,20,16))),U.call(i,S.call(i,20,16))),X.call(i,S.call(i,19,16))),W.call(i,S.call(i,19,16))),V.call(i,S.call(i,19,13))),U.call(i,S.call(i,19,13))),X.call(i,S.call(i,16,13))),W.call(i,S.call(i,16,13))),V.call(i,S.call(i,16,12))),X.call(i,S.call(i,16,12))),U.call(i,S.call(i,19,12))),W.call(i,S.call(i,19,12))),V.call(i,S.call(i,19,9)));a.h(e,d);e=new y;Y.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,
Y.call(i,Z.call(i,Y.call(i,Z.call(i,ug.call(i,e,V.call(i,S.call(i,2,24))),X.call(i,S.call(i,2,24))),U.call(i,S.call(i,5,24))),V.call(i,S.call(i,5,24))),W.call(i,S.call(i,5,28))),U.call(i,S.call(i,5,28))),X.call(i,S.call(i,4,28))),W.call(i,S.call(i,4,28))),V.call(i,S.call(i,4,25))),U.call(i,S.call(i,4,25))),X.call(i,S.call(i,2,25))),W.call(i,S.call(i,2,25))),V.call(i,S.call(i,2,24)));a.h(e,d);e=new y;Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,$.call(i,Y.call(i,Z.call(i,Y.call(i,Z.call(i,Y.call(i,
Z.call(i,ug.call(i,e,V.call(i,S.call(i,22,24))),X.call(i,S.call(i,22,24))),U.call(i,S.call(i,25,24))),V.call(i,S.call(i,25,24))),W.call(i,S.call(i,25,25))),U.call(i,S.call(i,25,25))),X.call(i,S.call(i,23,25))),V.call(i,S.call(i,23,25))),W.call(i,S.call(i,23,28))),U.call(i,S.call(i,23,28))),X.call(i,S.call(i,22,28))),W.call(i,S.call(i,22,28))),V.call(i,S.call(i,22,24)));return a.h(e,d)};var yg,zg=new rd("#FF0");function Ag(a){return a.fb(0,0,a.width,a.height,i,new rd("#000"))}function Bg(a,c){var d=new md("#FFB9AF"),e=new rd("#FFB9AF"),f=ng.call(i,c),g=N.call(i,f,0,i),f=N.call(i,f,1,i);return a.Fa(g,f,1,1,d,e,h)}function Cg(a,c){var d=new md("#FFB9AF"),e=new rd("#FFB9AF"),f=ng.call(i,c),g=N.call(i,f,0,i),f=N.call(i,f,1,i);return a.Fa(g,f,3,3,d,e,h)}
function Dg(a,c,d,e){c=Zf.call(i,Hf.call(i,function(a){return Oe.call(i,se.call(i,a),d)},c));return cg.call(i,xf.call(i,function(c){return e.call(i,a,c)},c))}function Eg(a,c){var d=c.call(i,"\ufdd0'pos"),e=N.call(i,d,0,i),d=N.call(i,d,1,i);yg=a.Fa(e,d,6,6,i,zg,h)}function Fg(a){var c=N.call(i,a,0,i),a=N.call(i,a,1,i);return yg.lb(c,a)};var Gg=R(["                            ","                            ","                            ","                            "," pppppppppppp  pppppppppppp "," p    p     p  p     p    p "," e    p     p  p     p    e "," p    p     p  p     p    p "," pppppppppppppppppppppppppp "," p    p  p        p  p    p "," p    p  p        p  p    p "," pppppp  pppp  pppp  pppppp ","      p     o  o     p      ","      p     o  o     p      ","      p  oooooooooo  p      ","      p  o        o  p      ",
"      p  o gggggg o  p      ","oooooopooo gggggg ooopoooooo","      p  o gggggg o  p      ","      p  o        o  p      ","      p  oooooooooo  p      ","      p  o        o  p      ","      p  o        o  p      "," pppppppppppp  pppppppppppp "," p    p     p  p     p    p "," p    p     p  p     p    p "," epp  pppppppooppppppp  ppe ","   p  p  p        p  p  p   ","   p  p  p        p  p  p   "," pppppp  pppp  pppp  pppppp "," p          p  p          p "," p          p  p          p "," pppppppppppppppppppppppppp ",
"                            ","                            ","                            "]),Hg=function(){var a=i;return a=function(c,d){switch(arguments.length){case 1:return a.call(i,c,kf);case 2:var e;a:for(var f=c,g=d;;)if(A(E.call(i,0,f))){e=g;break a}else var j=Xe.call(i,f),g=ve.call(i,g,Re.call(i,f,1)),f=j;return e}b("Invalid arity: "+arguments.length)}}();var Ig=hg.call(i,i);function Jg(){return kg.call(i,Ig)}function Kg(){return ig.call(i,Ig,i)}function Lg(a){a=a.keyCode;return A(E.call(i,a,38))?ig.call(i,Ig,"\ufdd0'north"):A(E.call(i,a,40))?ig.call(i,Ig,"\ufdd0'south"):A(E.call(i,a,37))?ig.call(i,Ig,"\ufdd0'west"):A(E.call(i,a,39))?ig.call(i,Ig,"\ufdd0'east"):i};var Mg=Vf(["\ufdd0'west","\ufdd0'east","\ufdd0'north","\ufdd0'south","\ufdd0'none"],{"\ufdd0'west":R([-1,0]),"\ufdd0'east":R([1,0]),"\ufdd0'north":R([0,-1]),"\ufdd0'south":R([0,1]),"\ufdd0'none":R([0,0])}),Ng=Vf(["\ufdd0'pos","\ufdd0'face"],{"\ufdd0'pos":U.call(i,S.call(i,14,26)),"\ufdd0'face":"\ufdd0'west"});
function Og(a,c,d,e,f){var g=og.call(i,a,c),j=N.call(i,g,0,i),l=N.call(i,g,1,i);return A(pg.call(i,a,c))?A(function(){var a=E.call(i,"\ufdd0'north",d);return A(a)?Oe.call(i,f.call(i,R([j,Re.call(i,l,1)])),"\ufdd0'open"):a}())?(Kg.call(i),d):A(function(){var a=E.call(i,"\ufdd0'south",d);return A(a)?Oe.call(i,f.call(i,R([j,O.call(i,l,1)])),"\ufdd0'open"):a}())?(Kg.call(i),d):A(function(){var a=E.call(i,"\ufdd0'east",d);return A(a)?Oe.call(i,f.call(i,R([O.call(i,j,1),l])),"\ufdd0'open"):a}())?(Kg.call(i),
d):A(function(){var a=E.call(i,"\ufdd0'west",d);return A(a)?Oe.call(i,f.call(i,R([Re.call(i,j,1),l])),"\ufdd0'open"):a}())?(Kg.call(i),d):A(function(){var a=E.call(i,"\ufdd0'north",e);return A(a)?Oe.call(i,f.call(i,R([j,Re.call(i,l,1)])),"\ufdd0'open"):a}())?e:A(function(){var a=E.call(i,"\ufdd0'south",e);return A(a)?Oe.call(i,f.call(i,R([j,O.call(i,l,1)])),"\ufdd0'open"):a}())?e:A(function(){var a=E.call(i,"\ufdd0'east",e);return A(a)?Oe.call(i,f.call(i,R([O.call(i,j,1),l])),"\ufdd0'open"):a}())?
e:A(function(){var a=E.call(i,"\ufdd0'west",e);return A(a)?Oe.call(i,f.call(i,R([Re.call(i,j,1),l])),"\ufdd0'open"):a}())?e:A("\ufdd0'else")?"\ufdd0'none":i:e}function Pg(a,c,d){var e=a.call(i,"\ufdd0'pos"),f=N.call(i,e,0,i),e=N.call(i,e,1,i),c=Og.call(i,f,e,c,a.call(i,"\ufdd0'face"),d),g=Mg.call(i,c),d=N.call(i,g,0,i),g=N.call(i,g,1,i),f=R([Ye.call(i,O.call(i,224,f,d),224),O.call(i,e,g)]);Fg.call(i,f);return ye.call(i,a,"\ufdd0'face",c,"\ufdd0'pos",f)}
function Qg(a,c){return ye.call(i,a,"\ufdd0'tick",H.call(i,a.call(i,"\ufdd0'tick")),"\ufdd0'pacman",Pg.call(i,a.call(i,"\ufdd0'pacman"),c,a.call(i,"\ufdd0'board")))}
var Rg=function(){var a=hg.call(i,Yf());cg.call(i,function(){return function d(e){return new Q(i,!1,function(){for(var f=e;;)if(A(J.call(i,f))){var g=K.call(i,f),j=J.call(i,function o(d){return new Q(i,!1,function(){for(;;)if(A(J.call(i,d))){var e=K.call(i,d);return P.call(i,function(){var d=Kf.call(i,Gg,R([g,e]));return jg.call(i,a,ye,R([e,g]),A(E.call(i,d," "))?Vf([],{}):A(E.call(i,d,"p"))?Vf(["\ufdd0'open","\ufdd0'pellet"],{"\ufdd0'open":i,"\ufdd0'pellet":i}):A(E.call(i,d,"o"))?Vf(["\ufdd0'open"],
{"\ufdd0'open":i}):A(E.call(i,d,"e"))?Vf(["\ufdd0'open","\ufdd0'energy"],{"\ufdd0'open":i,"\ufdd0'energy":i}):A("\ufdd0'else")?i:i)}(),o.call(i,L.call(i,d)))}else return i})}.call(i,Hg.call(i,we.call(i,Gg.call(i,0)))));if(A(j))return sf.call(i,j,d.call(i,L.call(i,f)));else f=L.call(i,f)}else return i})}.call(i,Hg.call(i,we.call(i,Gg)))}());return kg.call(i,a)}.call(i);(function(a){return dc.call(i,"log").innerHTML=df.call(i,a,"<br/>",dc.call(i,"log").innerHTML)}).call(i,"starting up");
(function(a,c){var d=Dd.call(i,224,288);Ag.call(i,d);xg.call(i,d,"#00F");Dg.call(i,d,a,"\ufdd0'pellet",Bg);Dg.call(i,d,a,"\ufdd0'energy",Cg);Eg.call(i,d,c);var e=dc.call(i,"playfield");d.n&&b(Error("Component already rendered"));d.b||d.B();e?e.insertBefore(d.b,i):d.J.da.body.appendChild(d.b);(!d.ua||d.ua.n)&&d.T()}).call(i,Rg,Ng);(function(){return Mb.call(i,new fd(document),"key",Lg)}).call(i);
(function Sg(c){return qd.call(i,function(){return Sg.call(i,Qg.call(i,c,Jg.call(i)))},17)}).call(i,Vf(["\ufdd0'pacman","\ufdd0'board","\ufdd0'tick"],{"\ufdd0'pacman":Ng,"\ufdd0'board":Rg,"\ufdd0'tick":0}));